### DISCUSSION TITLE
taint nodes

### DISCUSSION THREAD

**Discussion by AkakievKD** [kubesphere/kubekey#1927] [General]
hello, can i to taint nodes like here ?

```
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node2, address: 172.16.0.3, internalAddress: 172.16.0.3, password: "Qcloud@123", labels: {disk: SSD, role: backend}}
 ```
