### DISCUSSION TITLE
implement cluster-api using kubekey

### DISCUSSION THREAD

**Discussion by lxm** [kubesphere/kubekey#862] [Ideas]
currently functions that available in `KubeKey` are very close to the interfaces that `cluster api` needs to implement.
How about creating a `cluster-api-provider-kubekey` based on `KubeKey`.

**Comment by pixiake** [comment]
I think kubekey can implement some custom resources of cluster-api to improve kubekey's operator mode.
 
Examples:
```
## cluster
---
apiVersion: kubekey.kubesphere.io/v1alpha3
kind: Cluster
metadata:
  name: demo
  namespace: default
spec:
  hosts:
  - {name: node1, address: 172.16.0.2, internalAddress: 172.16.0.2, user: ubuntu, password: "Qcloud@123"}
  - {name: node2, address: 172.16.0.3, internalAddress: 172.16.0.3, user: ubuntu, password: "Qcloud@123"}
  roleGroups:
    etcd:
    - node1
    control-plane:
    - node1
    worker:
    - node1
    - node2
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.21.5
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    plainHTTP: false
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []


## Machine
---
apiVersion: kubekey.kubesphere.io/v1alpha3
kind: Machine
metadata:
  name: demo-control-plane-0
  namespace: default
spec:
  template:
    spec:
      hostName: node1
      address: 172.16.0.2
      internalAddress: 172.16.0.2
      port: 8022
      user: ubuntu
      password: "Qcloud@123"


## KubeadmConfigTemplate
---
apiVersion: kubekey.kubesphere.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: qc-test-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          criSocket: unix:///run/containerd/containerd.sock
      kubeletConfiguration:
        evictionHard:
          memory.available: 5%
          pid.available: 10%


## KubeadmConfig
apiVersion: kubekey.kubesphere.io/v1alpha3
kind: KubeadmConfig
metadata:
  name: demo-machine-pool
  namespace: default
spec:
  joinConfiguration:
    # auto generate
    discovery:
      bootstrapToken:
        apiServerEndpoint: 192.168.6.6:6443
        caCertHashes:
        - sha256:395195d485ea240446262675ff95c29b467cf887e29cf9dc0b15653a0f4e64a4
        token: z1y8uh.4id68l5x13uv8k2d
    nodeRegistration:
      kubeletExtraArgs:
        criSocket: unix:///run/containerd/containerd.sock
  kubeletConfiguration:
    evictionHard:
      memory.available: 5%
      pid.available: 10%



## ControlPlane
---
apiVersion: kubekey.kubesphere.io/v1alpha3
kind: ControlPlane
metadata:
  name: demo-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        criSocket: unix:///run/containerd/containerd.sock
    joinConfiguration:
      nodeRegistration:
        criSocket: unix:///run/containerd/containerd.sock
    kubeletConfiguration:
      evictionHard:
        memory.available: 5%
        pid.available: 10%
  machines:
    infrastructureRef:
    - apiVersion: kubekey.kubesphere.io/v1alpha3
      kind: Machine
      name: demo-control-plane-0
    - apiVersion: kubekey.kubesphere.io/v1alpha3
      kind: Machine
      name: demo-control-plane-1
  version: v1.21.5


## MachinePool
---
apiVersion: kubekey.kubesphere.io/v1alpha3
kind: MachinePool
metadata:
  name: demo-machine-pool
  namespace: default
spec:
  clusterName: demo
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: kubekey.kubesphere.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: demo-machine-pool
      clusterName: qc-test
      infrastructureRef:
      - apiVersion: kubekey.kubesphere.io/v1alpha3
        kind: Machine
        name: demo-worker-0
      - apiVersion: kubekey.kubesphere.io/v1alpha3
        kind: Machine
        name: demo-worker-1
      version: v1.21.5

```

https://www.processon.com/view/link/6274f36cf346fb18e7c03dc3

**Comment by 24sama** [comment]
```
apiVersion: kubekey.kubesphere.io/v1alpha3
kind: MachineSet
metadata:
  name: demo1
spec:
  auth:
    user: ubuntu
    password: "Qcloud@123"
  machines:
    - name: node1
      address: 172.16.0.2
      internalAddress: 172.16.0.2
    - name: node2
      address: 172.16.0.3
      internalAddress: 172.16.0.3
      auth:
        user: root
        password: "Qcloud@12345"

---
apiVersion: kubekey.kubesphere.io/v1alpha3
kind: MachineDeployment
metadata:
  name: demo1-md
spec:
  replicas: 3
  auth:
    user: ubuntu
    password: "Qcloud@123"
  machines: 
    - addressCIDR: 172.16.0.0/24
      policy: asc

## Machine
---
apiVersion: kubekey.kubesphere.io/v1alpha3
kind: Machine
metadata:
  name: demo-control-plane-0
  namespace: default
spec:
  hostName: node1
  address: 172.16.0.2
  internalAddress: 172.16.0.2
  port: 8022
  user: ubuntu
  password: "Qcloud@123"

## KubeadmConfigTemplate
---
apiVersion: kubekey.kubesphere.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: qc-test-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          criSocket: unix:///run/containerd/containerd.sock
      kubeletConfiguration:
        evictionHard:
          memory.available: 5%
          pid.available: 10%

## ControlPlane
---
apiVersion: kubekey.kubesphere.io/v1alpha3
kind: ControlPlane
metadata:
  name: demo-control-plane
  namespace: default
spec:
  kubeadmConfigTemplateSpec:
    template:
      spec:
        initConfiguration:
          nodeRegistration:
            criSocket: unix:///run/containerd/containerd.sock
        joinConfiguration:
          nodeRegistration:
            criSocket: unix:///run/containerd/containerd.sock
        kubeletConfiguration:
          evictionHard:
            memory.available: 5%
            pid.available: 10%
  machines:
    - infrastructureRef:
        apiVersion: kubekey.kubesphere.io/v1alpha3
        kind: Machine
        name: demo-control-plane-0
    - infrastructureRef:
        apiVersion: kubekey.kubesphere.io/v1alpha3
        kind: Machine
        name: demo-control-plane-1
  version: v1.21.5
  
## Worker
---
apiVersion: kubekey.kubesphere.io/v1alpha3
kind: Worker
metadata:
  name: demo-machine-pool
  namespace: default
spec:
  kubeadmConfigTemplateSpec:
    template:
      spec:
        initConfiguration:
          nodeRegistration:
            criSocket: unix:///run/containerd/containerd.sock
        joinConfiguration:
          nodeRegistration:
            criSocket: unix:///run/containerd/containerd.sock
        kubeletConfiguration:
          evictionHard:
            memory.available: 5%
            pid.available: 10%
  machines:
    - infrastructureRef:
        apiVersion: kubekey.kubesphere.io/v1alpha3
        kind: MachineDeployment
        name: demo1-md
  version: v1.21.5

## Cluster
# https://cluster-api.sigs.k8s.io/developer/architecture/controllers/cluster.html
---
apiVersion: kubekey.kubesphere.io/v1alpha3
kind: Cluster
metadata:
  name: demo1
spec:
  etcdRef:
    apiVersion: kubekey.kubesphere.io/v1alpha3
    kind: Etcd
    name: demo-Etcd
  controlPlaneRef: 
    apiVersion: kubekey.kubesphere.io/v1alpha3
    kind: ControlPlane
    name: demo-control-plane
  workerRef: 
    apiVersion: kubekey.kubesphere.io/v1alpha3
    kind: Worker
    name: demo-worker
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    multusCNI:
      enabled: false
status:
  phase: running
```
