### ISSUE TITLE
Integrate OpenELB in KubeKey as an addon

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubekey#1039]
### Your current KubeKey version

2.0.0

### Describe this feature

OpenELB is an open-source load balancer implementation designed for exposing the LoadBalancer type of Kubernetes services in on-premises environments, it can help KubeSphere users to easily resolve this issue.

My expectation:

Make OpenELB work like Cloud Controller Manager, it can automatically assign EIP to the K8s services when switching to LoadBalancer.
When users choose OpenELB, it will automatically assign EIP to the K8s services/KubeSphere gateway and configure the annotations, users don't need to install and configure it manually.

See this issue for more context:
https://github.com/kubesphere/kubesphere/issues/4574

### Describe the solution you'd like

Develop an addon for OpenELB in KubeKey

**Comment by chaunceyjiang** [comment]
Hi, maybe I don't need to make any changes to kubekey


```
# cat config.yaml

apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
   ....
  addons:
    - name: openelb
      namespace: kube-system
      sources:
        chart:
          name: openelb
          repo: https://charts.kubesphere.io/test

```
Reference 
[kubekey addons](https://github.com/kubesphere/kubekey/blob/master/docs/addons.md)
