### ISSUE TITLE
Install CNI as an optional feature while using containerd 

### ISSUE THREAD

**Issue by x86cloud** [kubesphere/kubekey#1095]
### Your current KubeKey version

./kk create cluster  --container-manage containerd 

### Describe this feature

using containerd as the container manager, Containerd official has provided CNI plugin in the package. cni plugin can be an optional feature.

### Describe the solution you'd like

tools add an option like `--skip-cni-install` to skip cni installation

**Comment by liangyuanpeng** [comment]
I don't think we need the param `--skip-cni-install`, it will let the user confused.

**Comment by 24sama** [comment]
You can install the cluster using the kubekey config that sets up the `.spec.networks.plugin` as `none` and sets up addons to deploy your CNI plugin.

For example, the following is a kubekey config example:
```
network:
    plugin: none
addons:
  - name: calico
    namespace: kube-system
    sources: 
      yaml: 
        path: 
        - /mycluster/calico/calico.yaml
```

Links:
1. https://github.com/kubesphere/kubekey/blob/master/docs/addons.md
2. https://github.com/kubesphere/kubekey/blob/master/docs/config-example.md
