### ISSUE TITLE
Support the use of kubeadm to manage etcd and use of existing etcd

### ISSUE THREAD

**Issue by pixiake** [kubesphere/kubekey#1122]
### Describe this feature

At present, kubekey only supports the separate installation of etcd cluster for k8s.
It should also support the use of existing etcd and etcd managed by kubeadm.

### Describe the solution you'd like

Add some parameters to the configuration file to select etcd cluster installation mode.
Support the choice of three etcd cluster types: `kubekey`, `kubeadm` and `external`.
When the type is set to external, `endpoints`、`caFile`、`certFile` and `keyFile` should be set..
If TLS authentication is not enabled for the existing etcd, `caFile`、`certFile` and `keyFile`  need not be set.

```
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  ...
  etcd:
    type: external   (kubekey / kubeadm / external)   # default: kubekey
    external:
      endpoints:
      - 192.168.6.6:2379
      caFile: /pki/etcd/ca.crt
      certFile: /pki/etcd/etcd.crt
      keyFile: /pki/etcd/etcd.key
  ...     
```
