### ISSUE TITLE
Unable to uninstall single-node k3s cluster

### ISSUE THREAD

**Issue by pixiake** [kubesphere/kubekey#1148]
### What is version of KubeKey has the issue?

v2.0.0

### What is your os environment?

Ubuntu20.04

### A clear and concise description of what happend.

I installed k3s cluster with `./kk create cluster --with-kubernetes v1.21.6-k3s`. But if I don't specify the configuration file, I can't uninstall k3s cluster with `./kk delete cluster`.

I think we can check whether `k3s-uninstall.sh` exists in the delete cluster pipeline, and if so, uninstall k3s first.

**Comment by xiaods** [comment]
This is designed to be like this, not a bug. we need discussion here and give a good choice then do action.

please read the file: 
# /kubekey/pkg/pipelines/delete_cluster.go
```
func DeleteCluster(args common.Argument) error {
	var loaderType string
	if args.FilePath != "" {
		loaderType = common.File
	} else {
		loaderType = common.AllInOne
	}

	runtime, err := common.NewKubeRuntime(loaderType, args)
	if err != nil {
		return err
	}

	switch runtime.Cluster.Kubernetes.Type {
	case common.K3s:  <--- follow this logic, runtime read kubeconfig and get runtime, it will know the type is k3s.
		if err := NewK3sDeleteClusterPipeline(runtime); err != nil {
			return err
		}
	case common.Kubernetes:
		if err := NewDeleteClusterPipeline(runtime); err != nil {
			return err
		}
	default:  
		if err := NewDeleteClusterPipeline(runtime); err != nil {
			return err
		}
	}
	return nil
}
```

are you sure uninstall k3s failed?

**Comment by xiaods** [comment]
@pixiake any update on this issue.

**Comment by pixiake** [comment]
@xiaods 
There should be no problem if we use the configuration file，because the `Kubernetes.Type` is specified in the configuration file.

If we use `allinone` mode, kk will automatically generate a default configuration, in which no  `Kubernetes.Type`  is specified.

**Comment by xiaods** [comment]
> with-kubernetes

@pixiake  cloud you please give a Kubernetes.Type sample case in your configfile. i read the config template, don't found any type for specified the k8s type. Maybe I have not totally understand your case. please let me know.

/kubekey/config/templates/cluster.go  --- this is default kk config.
```
// Cluster defines the template of cluster configuration file default.
var Cluster = template.Must(template.New("Cluster").Parse(
	dedent.Dedent(`
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: {{ .Options.Name }}
spec:
  hosts:
  - {name: node1, address: 172.16.0.2, internalAddress: 172.16.0.2, user: ubuntu, password: "Qcloud@123"}
  - {name: node2, address: 172.16.0.3, internalAddress: 172.16.0.3, user: ubuntu, password: "Qcloud@123"}
  roleGroups:
    etcd:
    - node1
    control-plane: 
    - node1
    worker:
    - node1
    - node2
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: {{ .Options.KubeVersion }}
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: {{ .Options.ContainerManager }}
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []

{{ if .Options.KubeSphereEnabled }}
{{ .Options.KubeSphereConfigMap }}
{{ end }}
    `)))
```
