### ISSUE TITLE
in master1 node,kk certs check-expiration failed by connect to localhost

### ISSUE THREAD

**Issue by zj452008181** [kubesphere/kubekey#1201]
### What is version of KubeKey has the issue?

1.1，1.2.1，2.0

### What is your os environment?

centos7.9

### KubeKey config file

```yaml
---
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: test
spec:
  hosts:
  - {name: k8s-master1, address: 10.0.1.147, internalAddress: 10.0.1.147, user: ops, password: }
  - {name: k8s-master2, address: 10.0.1.148, internalAddress: 10.0.1.148, user: ops, password: }
  - {name: k8s-master3, address: 10.0.1.149, internalAddress: 10.0.1.149, user: ops, password: }
  - {name: k8s-node1, address: 10.0.1.150, internalAddress: 10.0.1.150, user: ops, password: }
  - {name: k8s-node2, address: 10.0.1.151, internalAddress: 10.0.1.151, user: ops, password: }
  - {name: k8s-node3, address: 10.0.1.153, internalAddress: 10.0.1.153, user: ops, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: k8s-node4, address: 10.0.1.154, internalAddress: 10.0.1.154, user: ops, password: }
  - {name: k8s-node5, address: 10.0.1.155, internalAddress: 10.0.1.155, user: ops, password: }
  - {name: k8s-node6, address: 10.0.1.156, internalAddress: 10.0.1.156, user: ops, password: }
  roleGroups:
    etcd:
    - k8s-master1
    - k8s-master2
    - k8s-master3
    master: 
    - k8s-master1
    - k8s-master2
    - k8s-master3
    worker:
    - k8s-node1
    - k8s-node2
    - k8s-node3
    - k8s-node4
    - k8s-node5
    - k8s-node6
  controlPlaneEndpoint:
    internalLoadbalancer: haproxy
    domain: lb.kubesphere.local
#    address: ""
    port: 6443
  kubernetes:
    version: v1.20.4
    imageRepo: kubesphere
    clusterName: cluster.local
    maxPods: 60
  network:
    plugin: calico
    kubePodsCIDR: 172.18.64.0/18
    kubeServiceCIDR: 172.18.0.0/18
  registry:
    registryMirrors: ["https://6ab7z4a4.mirror.aliyuncs.com"]
    insecure-registries: [""]
    privateRegistry: ""
  addons:
  - name: nfs-client
    namespace: kube-system
    sources: 
      chart: 
        name: nfs-client-provisioner
        repo: https://charts.kubesphere.io/main
        valuesFile: nfs-client-provider.yaml
```

### A clear and concise description of what happend.

kk certs check-expiration failed，it tips Failed to connect to 10.0.1.147，but i can ssh to 10.0.1.147 in k8s-master1 node，the sshd_config i have no power to change，and the KubeKey config file is ok for kk added nodes，how to resolve this issue

### Relevant log output

```shell
INFO[16:27:05 CST] Listing cluster certs ...                    
ERRO[16:27:05 CST] Failed to connect to 10.0.1.147: could not establish connection to 10.0.1.147:22: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain  node=10.0.1.147
WARN[16:27:05 CST] Task failed ...                              
WARN[16:27:05 CST] error: interrupted by error                  
INFO[16:27:05 CST] Successful.
```

### Additional information

sshd_config：
```
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
SyslogFacility AUTHPRIV
PermitRootLogin yes 
AuthorizedKeysFile	.ssh/authorized_keys
PermitEmptyPasswords no
PasswordAuthentication yes
ChallengeResponseAuthentication no
GSSAPIAuthentication no 
GSSAPICleanupCredentials no
UsePAM yes
X11Forwarding yes
UseDNS no
AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
AcceptEnv XMODIFIERS
Subsystem	sftp	/usr/libexec/openssh/sftp-server
```
