### ISSUE TITLE
新版kk 2.1.0 推送私服报错

### ISSUE THREAD

**Issue by ndkings3001** [kubesphere/kubekey#1213]
### What is version of KubeKey has the issue?

2.1.0

### What is your os environment?

centos7

### KubeKey config file

```yaml
registry:
    type: harbor 
    privateRegistry: 10.168.2.239
    auths:
      "10.168.2.239":
        username: admin
        password: 
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
```

### A clear and concise description of what happend.

推送私服好像没有区找harbor
![image](https://user-images.githubusercontent.com/103571380/163509645-3b01e5aa-ddfd-4879-8fe6-e0736b6164ce.png)
 这个是harbor正常登录的提示。
![image](https://user-images.githubusercontent.com/103571380/163509709-c7140654-2e62-4241-bc47-07352c62ce8d.png)
这个是执行
./kk artifact image push -f config-sample.yaml -a kubesphere.tar.gz
的报错
