### ISSUE TITLE
kk3.0离线安装 卡在 Init operating system

### ISSUE THREAD

**Issue by MissYBYue** [kubesphere/kubekey#1215]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"v1.0.1-alpha.1", GitCommit:"d62e7a12a593390ea1ee52096248901fe7571a22", GitTreeState:"clean", GoVersion:"go1.14.7"}

### What is your os environment?

Ubuntu 18.04.5 LTS

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master, address: 172.28.81.183, internalAddress: 172.28.81.183, user: yueyb, password: a158900}
  - {name: node1, address: 172.28.81.146, internalAddress: 172.28.81.146, user: nhj, password: root12300.}
  roleGroups:
    etcd:
    - master
    master: 
    - master
    worker:
    - node1
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: "6443"
  kubernetes:
    version: v1.18.6
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 192.168.0.0/16
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
    privateRegistry: 172.16.1.10:8900
  addons: []


---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.0.0
spec:
  local_registry: ""
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  etcd:
    monitoring: true
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    es:
      elasticsearchDataVolumeSize: 20Gi
      elasticsearchMasterVolumeSize: 4Gi
      elkPrefix: logstash
      logMaxAge: 7
    mysqlVolumeSize: 20Gi
    minioVolumeSize: 20Gi
    etcdVolumeSize: 20Gi
    openldapVolumeSize: 2Gi
    redisVolumSize: 2Gi
  console:
    enableMultiLogin: false  # enable/disable multi login
    port: 30880
  alerting:
    enabled: false
  auditing:
    enabled: false
  devops:
    enabled: false
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 512m
    jenkinsJavaOpts_Xmx: 512m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: false
    ruler:
      enabled: true
      replicas: 2
  logging:
    enabled: false
    logsidecarReplicas: 2
  metrics_server:
    enabled: true
  monitoring:
    prometheusMemoryRequest: 400Mi
    prometheusVolumeSize: 20Gi
  multicluster:
    clusterRole: none  # host | member | none
  networkpolicy:
    enabled: false
  notification:
    enabled: false
  openpitrix:
    enabled: false
  servicemesh:
    enabled: false
```

### A clear and concise description of what happend.

使用https://kubesphere-installer.pek3b.qingstor.com/offline/v3.0.0/kubesphere-all-v3.0.0-offline-linux-amd64.tar.gz
安装卡在
root@yueyb-chaosuan:/opt/release/kubesphere/kubesphere-all-v3.0.0-offline-linux-amd64# ./kk init os -f config-sample.yaml -s ./dependencies/
INFO[18:52:00 CST] Init operating system                        
FATA[20:52:00 CST] Execute task timeout, Timeout=120s  

### Relevant log output

```shell
INFO[18:52:00 CST] Init operating system                        
FATA[20:52:00 CST] Execute task timeout, Timeout=120s
```
