### ISSUE TITLE
kubekey上传私服必须是https协议么？

### ISSUE THREAD

**Issue by ndkings3001** [kubesphere/kubekey#1229]
### What is version of KubeKey has the issue?

2.1.0

### What is your os environment?

centos7

### KubeKey config file

```yaml
registry:
    type: harbor
    privateRegistry: 10.168.2.239
    plainHTTP: true
    auths:
      "10.168.2.239":
        username: admin
        password: 123456
        #skipTLSVerify: false
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
```

### A clear and concise description of what happend.

上传修改什么配置可以然他上传为 http协议的私服？
![image](https://user-images.githubusercontent.com/103571380/164165054-48accba9-1efb-48ce-816b-c929a1be18bc.png)

**Comment by ndkings3001** [comment]
![image](https://user-images.githubusercontent.com/103571380/164169130-086c908a-1c5a-45ad-9f7c-8e439590c95f.png)
其他包都正常http长传！ 后面着几个包又变成https了

**Comment by 24sama** [comment]
Make sure:
```
registry:
    type: harbor
    privateRegistry: 10.168.2.239
    plainHTTP: true
    auths:
      "10.168.2.239":
        username: admin
        password: 123456
        skipTLSVerify: true
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
```
