### ISSUE TITLE
离线安装只能最小化安装，配置文件的插件设置为 true 不生效

### ISSUE THREAD

**Issue by athlonreg** [kubesphere/kubekey#1238]
### What is version of KubeKey has the issue?

2.1.0-alpha.1

### What is your os environment?

CentOS 7.6.1810 amd64

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: 192.168.21.101, internalAddress: 192.168.21.101, user: root, password: "123456"}
  - {name: node2, address: 192.168.21.102, internalAddress: 192.168.21.102, user: root, password: "123456"}
  - {name: node3, address: 192.168.21.103, internalAddress: 192.168.21.103, user: root, password: "123456"}
  roleGroups:
    etcd:
    - node[1:3]
    control-plane:
    - node[1:3]
    worker:
    - node[1:3]
    registry:
    - node1
  controlPlaneEndpoint:
    internalLoadbalancer: haproxy
    domain: lb.cluster.local
    address: ""
    port: 6443
  system:
    ntpServers:
      - ntp.aliyun.com
    timezone: "Asia/Shanghai"
  kubernetes:
    version: v1.21.5
    imageRepo: ""
    clusterName: cluster.local
    maxPods: 300
    apiserverArgs:
      - service-node-port-range=10000-65535
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    multusCNI:
      enabled: false
  registry:
    registryMirrors: ["https://registry.docker-cn.com"]
    insecureRegistries: ["https://hub.test.com"]
    privateRegistry: "hub.test.com"
    namespaceOverride: "library"
  addons: 
  - name: glusterfs
    namespace: kube-system
    sources: 
      yaml:
        path: 
        - /root/glusterfs.yaml

---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.2.1
spec:
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  zone: "cn"
  local_registry: "hub.test.com"
  namespace_override: "library"
  etcd:
    monitoring: true
    endpointIps: '192.168.21.101,192.168.21.102,192.168.21.103'
    port: 2379
    tlsEnable: true
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    redis:
      enabled: false
      volumeSize: 2Gi
    openldap:
      enabled: false
      volumeSize: 2Gi
    minio:
      volumeSize: 20Gi
    monitoring:
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      GPUMonitoring:
        enabled: true
    gpu:
      kinds:
        - resourceName: "nvidia.com/gpu"
          resourceType: "GPU"
          default: true
    es:
      logMaxAge: 7
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchUrl: ""
      externalElasticsearchPort: ""
  alerting:
    enabled: true
  auditing:
    enabled: true
  devops:
    enabled: false
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 512m
    jenkinsJavaOpts_Xmx: 512m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: true
  logging:
    enabled: true
    logsidecar:
      enabled: true
      replicas: 2
  metrics_server:
    enabled: true
  monitoring:
    storageClass: ""
    gpu:
      nvidia_dcgm_exporter:
        enabled: false
  multicluster:
    clusterRole: none 
  network:
    networkpolicy:
      enabled: true
    ippool:
      type: calico
    topology:
      type: weave-scope
  openpitrix:
    store:
      enabled: true
  servicemesh:
    enabled: true
  kubeedge:
    enabled: false
    cloudCore:
      nodeSelector: { "node-role.kubernetes.io/worker": "" }
      tolerations: [ ]
      cloudhubPort: "10000"
      cloudhubQuicPort: "10001"
      cloudhubHttpsPort: "10002"
      cloudstreamPort: "10003"
      tunnelPort: "10004"
      cloudHub:
        advertiseAddress:
          - ""
        nodeLimit: "100"
      service:
        cloudhubNodePort: "30000"
        cloudhubQuicNodePort: "30001"
        cloudhubHttpsNodePort: "30002"
        cloudstreamNodePort: "30003"
        tunnelNodePort: "30004"
    edgeWatcher:
      nodeSelector: { "node-role.kubernetes.io/worker": "" }
      tolerations: [ ]
      edgeWatcherAgent:
        nodeSelector: { "node-role.kubernetes.io/worker": "" }
        tolerations: [ ]
```

### A clear and concise description of what happend.

kubekey 配置文件如上，使用的外部离线 registry ，问题如下：

1. 安装结果为最小化 kubesphere，配置文件中启用的 auditing、alerting 等插件未成功安装
2. 设置的 apiserverArgs 和 maxPods 参数在安装过程中也未生效
