### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by walt008** [kubesphere/kubekey#1246]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"2.0.0", GitCommit:"ff9d30b7", GitTreeState:"", GoVersion:"go1.17.7"}

### What is your os environment?

centos7.9

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master1, address: 10.100.3.78, internalAddress: 10.100.3.78, user: root, privateKeyPath: "~/.ssh/id_rsa"}
  roleGroups:
    etcd:
    - master1
    control-plane: 
    - master1
    worker:
    - master1
    registry:
    - master1
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    internalLoadbalancer: haproxy
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.21.5
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    plainHTTP: false
    type:  "harbor"
    privateRegistry: "dockerhub.kubekey.local"
    auths:
      "dockerhub.kubekey.local":
        username: admin
        password: Harbor12345
    namespaceOverride: "library"
    registryMirrors: []
    insecureRegistries: []
  addons: []



---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.2.1
spec:
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  zone: cn
  local_registry: "dockerhub.kubekey.local"
  namespace_override: "library"
  # dev_tag: ""
  etcd:
    monitoring: true
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    # apiserver:
    #  resources: {}
    # controllerManager:
    #  resources: {}
    redis:
      enabled: true
      volumeSize: 2Gi
    openldap:
      enabled: false
      volumeSize: 2Gi
    minio:
      volumeSize: 20Gi
    monitoring:
      # type: external
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      GPUMonitoring:
        enabled: true
    gpu:
      kinds:         
      - resourceName: "nvidia.com/gpu"
        resourceType: "GPU"
        default: true
    es:
      # master:
      #   volumeSize: 4Gi
      #   replicas: 1
      #   resources: {}
      # data:
      #   volumeSize: 20Gi
      #   replicas: 1
      #   resources: {}
      logMaxAge: 7
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchHost: ""
      externalElasticsearchPort: ""
  alerting:
    enabled: false
    # thanosruler:
    #   replicas: 1
    #   resources: {}
  auditing:
    enabled: false
    # operator:
    #   resources: {}
    # webhook:
    #   resources: {}
  devops:
    enabled: false
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 512m
    jenkinsJavaOpts_Xmx: 512m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: false
    # operator:
    #   resources: {}
    # exporter:
    #   resources: {}
    # ruler:
    #   enabled: true
    #   replicas: 2
    #   resources: {}
  logging:
    enabled: false
    containerruntime: docker
    logsidecar:
      enabled: true
      replicas: 2
      # resources: {}
  metrics_server:
    enabled: false
  monitoring:
    storageClass: ""
    # kube_rbac_proxy:
    #   resources: {}
    # kube_state_metrics:
    #   resources: {}
    # prometheus:
    #   replicas: 1
    #   volumeSize: 20Gi
    #   resources: {}
    #   operator:
    #     resources: {}
    #   adapter:
    #     resources: {}
    # node_exporter:
    #   resources: {}
    # alertmanager:
    #   replicas: 1
    #   resources: {}
    # notification_manager:
    #   resources: {}
    #   operator:
    #     resources: {}
    #   proxy:
    #     resources: {}
    gpu:
      nvidia_dcgm_exporter:
        enabled: true
        # resources: {}
  multicluster:
    clusterRole: none 
  network:
    networkpolicy:
      enabled: false
    ippool:
      type: none
    topology:
      type: none
  openpitrix:
    store:
      enabled: false
  servicemesh:
    enabled: false
  kubeedge:
    enabled: false   
    cloudCore:
      nodeSelector: {"node-role.kubernetes.io/worker": ""}
      tolerations: []
      cloudhubPort: "10000"
      cloudhubQuicPort: "10001"
      cloudhubHttpsPort: "10002"
      cloudstreamPort: "10003"
      tunnelPort: "10004"
      cloudHub:
        advertiseAddress:
          - ""
        nodeLimit: "100"
      service:
        cloudhubNodePort: "30000"
        cloudhubQuicNodePort: "30001"
        cloudhubHttpsNodePort: "30002"
        cloudstreamNodePort: "30003"
        tunnelNodePort: "30004"
    edgeWatcher:
      nodeSelector: {"node-role.kubernetes.io/worker": ""}
      tolerations: []
      edgeWatcherAgent:
        nodeSelector: {"node-role.kubernetes.io/worker": ""}
```

### A clear and concise description of what happend.

kk 2.0   打包离线安装包后，使用离线包安装， 初始化私有镜像仓库成功，但是安装kk create cluster -f config-sample.yaml -a kubesphere.tar.gz 报错

### Relevant log output

```shell
02:44:53 UTC [InstallContainerModule] Add auths to container runtime
02:44:54 UTC success: [master1]
02:44:54 UTC [PushModule] Push images to private registry
panic: runtime error: index out of range [1] with length 1

goroutine 248 [running]:
github.com/kubesphere/kubekey/pkg/images.parseImageName({0xc0006ba380, 0x468e8e})
        /home/runner/work/kubekey/kubekey/pkg/images/images.go:191 +0x1c6
github.com/kubesphere/kubekey/pkg/images.CmdPush({0xc0006ba380, 0x5}, {0xc00042f680, 0x1f}, 0xc0003037a0, {0xc00071af40, 0x1, 0x1})
        /home/runner/work/kubekey/kubekey/pkg/images/images.go:129 +0x6e
github.com/kubesphere/kubekey/pkg/images.(*PushImage).Execute(0xc000481e60, {0x257c0c0, 0xc000494900})
        /home/runner/work/kubekey/kubekey/pkg/images/tasks.go:163 +0x425
github.com/kubesphere/kubekey/pkg/core/task.(*LocalTask).ExecuteWithRetry(0xc000214000, {0x257c0c0, 0xc000494900}, {0x2584d48, 0xc0002144d0})
        /home/runner/work/kubekey/kubekey/pkg/core/task/local_task.go:203 +0x137
github.com/kubesphere/kubekey/pkg/core/task.(*LocalTask).Run(0xc000214000, {0x257c0c0, 0xc000494900}, {0x2584d48, 0xc0002144d0}, 0x0)
        /home/runner/work/kubekey/kubekey/pkg/core/task/local_task.go:157 +0x225
created by github.com/kubesphere/kubekey/pkg/core/task.(*LocalTask).RunWithTimeout
        /home/runner/work/kubekey/kubekey/pkg/core/task/local_task.go:119 +0x16f
```
