### ISSUE TITLE
When use containerd as container runtime, containerd does not apply the configuration of insecureRegistrys.

### ISSUE THREAD

**Issue by hellocn9** [kubesphere/kubekey#1268]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"2.1.0", GitCommit:"8c7bb1d6", GitTreeState:"", GoVersion:"go1.17.9"}

### What is your os environment?

Centos7

### KubeKey config file

```yaml
registry:
        registryMirrors: []
        insecureRegistries: ["192.168.239.130:5000"] 
        privateRegistry: 192.168.239.130:5000 
        namespaceOverride: "google_containers" 
        auths: # if docker add by `docker login`, if containerd append to `/etc/containerd/config.toml`
          "192.168.239.130:5000":
            plainHTTP: true
            skipTLSVerify: true # Allow contacting registries over HTTP, or HTTPS with failed TLS verification.
```

### A clear and concise description of what happend.

When use containerd as container runtime, and the plainHTTP and skipTLSVerify is true, and insecureRegistries is configured, the /etc/containerd/config.toml which generated by kk does not apply the insecureRegistries configuration.

the kk config is
```
      registry:
        registryMirrors: []
        insecureRegistries: ["192.168.239.130:5000"] 
        privateRegistry: 192.168.239.130:5000 
        namespaceOverride: "google_containers" 
        auths: # if docker add by `docker login`, if containerd append to `/etc/containerd/config.toml`
          "192.168.239.130:5000":
            plainHTTP: true
            skipTLSVerify: true # Allow contacting registries over HTTP, or HTTPS with failed TLS verification.
```

the generated /etc/containerd/config.toml is 
```
    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
        [plugins."io.containerd.grpc.v1.cri".registry.configs]
          [plugins."io.containerd.grpc.v1.cri".registry.configs."192.168.239.130:5000".auth]
            username = ""
            password = ""
            [plugins."io.containerd.grpc.v1.cri".registry.configs."192.168.239.130:5000".tls]
              ca_file = ""
              cert_file = ""
              key_file = ""
              insecure_skip_verify = true
```

so when use crictl to pull images, it will meet following error
```
downloading image: 192.168.239.130:5000/google_containers/etcd:v3.4.13
04:35:08 UTC command: [m-192-168-239-133]
sudo -E /bin/bash -c "env PATH=$PATH crictl pull 192.168.239.130:5000/google_containers/etcd:v3.4.13"
04:35:08 UTC stdout: [m-192-168-239-133]
FATA[0000] pulling image: rpc error: code = Unknown desc = failed to pull and unpack image "192.168.239.130:5000/google_containers/etcd:v3.4.13": failed to resolve reference "192.168.239.130:5000/google_containers/etcd:v3.4.13": failed to do request: Head "https://192.168.239.130:5000/v2/google_containers/etcd/manifests/v3.4.13": http: server gave HTTP response to HTTPS client
```
