### ISSUE TITLE
There is an error during install kubernetes v1.24.0

### ISSUE THREAD

**Issue by elmerzeng** [kubesphere/kubekey#1274]
### What is version of KubeKey has the issue?

v2.1.0

### What is your os environment?

CentOS 7

### A clear and concise description of what happend.

There is a pre-flight check error during installing kubernetes v1.24.0:  "crictl not found in system path"

Because crictl does not exist in docker-20.10.8.tgz package.

`init kubernetes cluster failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubeadm init --config=/etc/kubernetes/kubeadm-config.yaml --ignore-preflight-errors=FileExisting-crictl" 
W0510 16:03:28.832263   41499 common.go:83] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta2". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0510 16:03:28.833177   41499 common.go:83] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta2". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0510 16:03:28.834322   41499 utils.go:69] The recommended value for "clusterDNS" in "KubeletConfiguration" is: [10.233.0.10]; the provided value is: [169.254.25.10]
[init] Using Kubernetes version: v1.24.0
[preflight] Running pre-flight checks
W0510 16:03:28.838402   41499 checks.go:1021] [preflight] WARNING: Couldn't create the interface used for talking to the container runtime: crictl is required by the container runtime: exec: "crictl": executable file not found in $PATH
	[WARNING FileExisting-crictl]: crictl not found in system path
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: crictl is required by the container runtime: exec: "crictl": executable file not found in $PATH
To see the stack trace of this error execute with --v=5 or higher: Process exited with status 1`

**Comment by 24sama** [comment]
Hi @life- 
Please make sure you set up the field `.spec.kubernetes.containerManager: containerd` in the config file or use the flag `--containerManager containerd` in your create cluster command.

**Comment by life-** [comment]
`./kk create config --with-kubernetes v1.24.0`   generate the default config-sample.yaml, but it does not work.

**Comment by 24sama** [comment]
> `./kk create config --with-kubernetes v1.24.0` generate the default config-sample.yaml, but it does not work.

Sorry, this may be a little bug, it doesn't set up the `.spec.kubernetes.containerManager: containerd` automatically. For now, you need to set up it manually.

**Comment by yangyuw** [comment]
> `./kk create config --with-kubernetes v1.24.0` generate the default config-sample.yaml, but it does not work.

this works for me, tks

**Comment by willzhang** [comment]
this works for me

```
root@ubuntu:/data/kubekey# cat config-sample.yaml 

apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master, address: 192.168.72.30, internalAddress: 192.168.72.30, user: root, password: "123456"}
  - {name: node1, address: 192.168.72.31, internalAddress: 192.168.72.31, user: root, password: "123456"}
  - {name: node2, address: 192.168.72.32, internalAddress: 192.168.72.32, user: root, password: "123456"}
  roleGroups:
    etcd:
    - master
    control-plane: 
    - master
    worker:
    - node1
    - node2
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.24.0
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: true
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```
