### ISSUE TITLE
install in VirtualMachine but pod error: calico-controller pod crash

### ISSUE THREAD

**Issue by starComingup** [kubesphere/kubekey#1287]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"2.0.0", GitCommit:"ff9d30b7", GitTreeState:"", GoVersion:"go1.17.7"}

### What is your os environment?

Ubuntu 18.04.6 LTS

### KubeKey config file

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EVXlNVEExTURZd05Gb1hEVE15TURVeE9EQTFNRFl3TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTm9uClBNNWdoTUdWZnNMSTdDSjFJaldSUVZEV1hKWDB1TTdoTHJoMTgzUGFBL0QyaWczT2k3OHBtc3dwWjVYVTF6blkKcmNrOU9yTjR1dk51bWpSUUNVaTkwcHRyeXdQNWsvVDErMlozU2VSaXFyMHVyYWtpWlZBdmpmU3FGSlU3aU9IRwpoYjBXZ1BjdWRIeDlBKzZvbytzUHBQZkRJMVcwMm5KNm1pak1zL3RYNFdhTkh3RzZqMnpaTXROUXVJUEtwVHlTCjcyQXJRSkFkYXFhd0UyeSt0YlF6OFlBalpERitTWm5sRkZSYUZTMDYrN3F1MThTOURIeERteWRwSkpoZHJIL2UKR3RYWFYrd1VUbkprRUNVRndMTnJsSDljY1VWQUFIdTRMTlVFRzdBYVNFMC9tN2taZmtSaXBNNFZpL2huQXQ3KwpjTXorcC9KcEk3SjFxTFpHZk5rQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCaThGZWtWNldlbTdNcWl0dVhXd2FvbU1tak5NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFESTkwMFgwdG1YaWl4UlhKMExKNDNNTUZJNlh1YjVNa25hYkRLVklIMGxTUlduN3A2NwpFQ3VoNFVVNGpsandJM2RoOVBQU2RoSnk2bTlScENiYndVTmdiV3JCRXYxbXRtanVxd1I4MGRJL0RsRERlbnpsCi81M1pOUGhjQyt2bkZ3RTJjcXJmeko4RzIrWlNMWUZLUFB6WkhaZVh3c2V0YmVpMm5nUlVyVWk1ZDlBcGdkU3EKV2syQWdFOHNoQ2JBSWJJcEdrUmxCQXd0ZG9DSjVSOGJlcnhPYkplYkNDdW1TVnBBTS8xWVNyY0FjOFZYaisrWgp5TW1kTFFkeElvRisrdEs0clM3Qm1ONlJKejZ3Z0tvYnpFRzE4aXpQekxWTGM2dlNLVzlBTXJKS2tGWTBuUGtRCmJpOVJHOUdCZjZpQXZuZkJTZ2xiRjJKUmFSUnhpcmwwdEd1cgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.128.129:6443
  name: cluster.local
contexts:
- context:
    cluster: cluster.local
    user: kubernetes-admin
  name: kubernetes-admin@cluster.local
current-context: kubernetes-admin@cluster.local
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJSnlzNXU0cjcvV0l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TWpBMU1qRXdOVEEyTURSYUZ3MHlNekExTWpFd05UQTJNRFZhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXllSFNoUFBoZ0IvQmJKMTgKdXJ2cEdud3U4TTAyeHZpcS9MTlZ3MHpDNmVubld2NGY1QlIrR2tzL1JZalhWY3dXY0dlemZhTGVNM1E4Rk53Wgp2SUxRanVtRlVuWTZZcUEzaGJuSWJzeVZYSjY0azE2MFM4dUU0L0VTSThadXpFUTJGNjNlYjJmUWR5bVVpQkxHCm5zY1J0S0pFUzRYdFdrSUR5OEtTUERpM1pSWGh2a0pGTnBaWnExaVlvK2xQTlZPOXg0SVhSUElXZHJBeHc0L3gKQ1haemlCT3doQnNzVU5rajFJd2pmZDF6Y0drVVV2MGZIcDVpMmI1L1ZGeEJLL0lWMEJQMFhKeGFPRVBMU1dybwovTUtZQ3dzRnNSTldMSmtxbWhQeTFvSytveGQvYzRYdVJqajg3Tm1MMXdXajNaMk9mQmEzRjVmU2daWHhmN3pHCjh2RURRUUlEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JRWXZCWHBGZWxucHV6S29yYmwxc0dxSmpKbwp6VEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBSVRUdUUrQ1RHWVRJejFWaGcxQnlINXBzV3czMFNmcmFQZ2psCmpoeC9RWExzU0ZSQzhMYXIyZlJGd3QzZnh5QkMwbFpJSXI1WUt2SWZ0SlZQd1B4OHk0SnJORjQ1VzkxamFaOWMKQ1p6Q3Z6QS9UUzc0bGhRNTQ5MVJxSTNadUo4VmVIQXVmVCtlRUJpYm16QmxjYWtESkhuMjN2MlptYWV1TmNZZwpRQXdCOFVGdnlhZmZEOUR3cnhZR1Z4dTRFTzI5L1c1QWErUy9lS1A0ZEdSVHBjNVM0YnNEdlAzbjlTUUp3Uk5LCnRHM3hieEdMY0hPZnpYSndBSXJRT3lXV0llN1VuL1ZZbzFaNXM4RmdlVXhFWUIxNFNRTURoUFlSZnJ2ODNkaTIKRHgrVHdvclYrQzI0UUZEV0c1UjY1SUhvekxCQ3V1L242aG93ODd0SUFKSGFEYTAwdnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBeWVIU2hQUGhnQi9CYkoxOHVydnBHbnd1OE0wMnh2aXEvTE5WdzB6QzZlbm5XdjRmCjVCUitHa3MvUllqWFZjd1djR2V6ZmFMZU0zUThGTndadklMUWp1bUZVblk2WXFBM2hibklic3lWWEo2NGsxNjAKUzh1RTQvRVNJOFp1ekVRMkY2M2ViMmZRZHltVWlCTEduc2NSdEtKRVM0WHRXa0lEeThLU1BEaTNaUlhodmtKRgpOcFpacTFpWW8rbFBOVk85eDRJWFJQSVdkckF4dzQveENYWnppQk93aEJzc1VOa2oxSXdqZmQxemNHa1VVdjBmCkhwNWkyYjUvVkZ4QksvSVYwQlAwWEp4YU9FUExTV3JvL01LWUN3c0ZzUk5XTEprcW1oUHkxb0srb3hkL2M0WHUKUmpqODdObUwxd1dqM1oyT2ZCYTNGNWZTZ1pYeGY3ekc4dkVEUVFJREFRQUJBb0lCQUZ5N3RwQUwxdEdieEtXMwowY3VVOVlhTTlLTDRJT2xVNEhZamlvbWpnUVVoeEh3dnIwWjlnMDlnc1Rlbm5BSjFOUGw5S1IzVTZteUlQL0QxCkNYMW1PWmJyL2FuYlZRWm93aGhUTnBadXMwMVFPMGkyZitzeEdXSDdJbkg4Zkhpbi9KRHo5UEVIcHVLVjN2eUMKWTJvYjF5NDZPMVRWdUNsMW1YakhiNVRxR0pQOW9DNW1uOGZzakt2ZThGN2pPWnJtQnhWVGpzb0dDaFlJdU9VNQpqVCtUbmhBd21GekRzN1R6YXd2S2Jld1Q2Q0dvbHVvZFA0TU5uOUo2WkNoLzBrUnJ0bkt2RHhmcWoxenlCc0d4Ck5nRVd2c3IvdTdKMURKRlZkSlpEeTMyR3NRQWNneG9DMWNpNEN2Z29xazl1ZDJxR1p5dWdLaDduRGFFazVUeSsKNDExdUNnRUNnWUVBNjc5c1VIYmN2YjVOaVFvWHNuWVhtTHZoWkkzN3BlOG1ObzJXelZCWDVuVHpxUzF0WStvMgpSRzN1cW9VU0RsRDhsSm10eVVrR21JSm1IeDRCMkNUWWRjZ2FOS0NuVXNsNXE3NmNyaE1HVFJRN0c4L0NQd09QClZ0MStFYjNSb2JkRXFmSGIweGtiTmdOZ2FuZVVoaTNteGM3ajJ3TXVDTExVNGdPMmVEcHRBNWtDZ1lFQTJ6bWYKNHhMQS9FRUgwOUg3VDUyeTZPQ3RoVnZVREk2NTg3Nnh3UkdldmNDZGVRcGh1R2g3QWJIeVhFYUp4d294SzlHaApLWnliZ2ZTZEdUdEpHMTVWTWh0aXRKWDdYSzM2ZGk2T1dnMDFERzNQaERrMHpFV3BnMXhSajdobzRIT3p5TjJHCkRUTWZHek5TNEVRNUVZQWNhRlBoUGVwL0N4MlVsUVBZM0tvVXhla0NnWUVBNDkrZ1h4YkZ3RkxXdDRRZDY4N2kKZUN3RGJpTWdBQUR1T3dVWm8xUHA0MFZnMFVLcjNreGlNRHJpMjhqTTd6R3hOQ0pvTFl4ODU2WUQrRWdWR0V4bApQMVF3b0hZNXhuZ2hON1dEMVc5bVE5TXVYMit2SHlIZHgrVkpHdlVVVVBESldrd0NaRVo4V3ZWZ21Ra0ZjNzJpCnQ4bUh6Z2VBMDcrb3J0OVAzVjc4U09FQ2dZRUFzQUhHM1orcjg1c2VkckVLN1RQMmRVUVY3SkQ2WVk2aHV4RnEKVTFFYk9zdVBZcU8wSzBNdkp3QkFUbGVQdkk3eFJYWUx4NFhsMEdPZFVhbW9tMkdVVXlOcmp3TXZpWXhoSDB0bgpuT01ucVMvc3dRTFE0Z1E0QWJBNEI0U09KMDZkbEhKT2N3Q05RK0JqOUl5eHFOeExjbk9OenBFYnFNZjZCOTNMCjJmWnZzU2tDZ1lFQXVJNEZ2UG02cUxJcGdhY2VKbktrZjF3QnFwRG8zNXF5amZjZTl2bW13UVlGU1NaSDEwSS8KTU1hRHIycG56WktmclF2QVpmRTNCSGFCTDNSV0tvcGIvSUdySkRGaWtTYWNuY3lnUlByeVNqZktNWm11VDE4aApxREpuUjhXelJlbEpCY1VxNnJrNG04QzFTSFVmS0N2NlN1akF5WVA3WjBvcTYzRVJlQWMxUkQ0PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
```

### A clear and concise description of what happend.

when i try to install kubernetes with muti-node in my Vmware. after install the calico-controller pod is  CrashLoopBackOff and etcd pod is gone.
I resolved the `check that the calico/node container is running and has mounted /var/lib/calico/` problem in calico community.
I just create a nodename file in node filesystem.
but when i see problem with "status.json", i find the etcd pod lost!

the Virtual Machine configuration is 4 core CPU and 4 Gib Memory. IPAddr: 192.168.128.129,192.168.128.130

### Relevant log output

```shell
kube-controllers-75ddb95444-h6gts
Name:                 calico-kube-controllers-75ddb95444-h6gts
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 worker/
Start Time:           Sat, 21 May 2022 06:06:09 +0000
Labels:               k8s-app=calico-kube-controllers
                      pod-template-hash=75ddb95444
Annotations:          cni.projectcalico.org/containerID: 0fe32d6c72a92a0ad336872661cbbc95262dc60f48900d08cad89364b267c7b2
                      cni.projectcalico.org/podIP: 10.233.94.3/32
                      cni.projectcalico.org/podIPs: 10.233.94.3/32
Status:               Running
IP:                   10.233.94.3
IPs:
  IP:           10.233.94.3
Controlled By:  ReplicaSet/calico-kube-controllers-75ddb95444
Containers:
  calico-kube-controllers:
    Container ID:   docker://361ebff5cf54c8d3b3723d3aae60665a665a4e3fe4075695be771d825d3ae5bd
    Image:          registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controllers:v3.20.0
    Image ID:       docker-pullable://registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controllers@sha256:a850ce8daa84433a5641900693b0f8bc8e5177a4aa4cac8cf4b6cd8c24fd9886
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 21 May 2022 06:23:34 +0000
      Finished:     Sat, 21 May 2022 06:23:44 +0000
    Ready:          False
    Restart Count:  8
    Liveness:       exec [/usr/bin/check-status -l] delay=10s timeout=10s period=10s #success=1 #failure=6
    Readiness:      exec [/usr/bin/check-status -r] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      ENABLED_CONTROLLERS:  node
      DATASTORE_TYPE:       kubernetes
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-rc5jj (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-rc5jj:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 CriticalAddonsOnly op=Exists
                             node-role.kubernetes.io/master:NoSchedule
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  19m                   default-scheduler  Successfully assigned kube-system/calico-kube-controllers-75ddb95444-h6gts to worker
  Normal   Pulled     18m (x4 over 19m)     kubelet            Container image "registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controllers:v3.20.0" already present on machine
  Normal   Created    18m (x4 over 19m)     kubelet            Created container calico-kube-controllers
  Normal   Started    18m (x4 over 19m)     kubelet            Started container calico-kube-controllers
  Warning  Unhealthy  18m (x8 over 19m)     kubelet            Readiness probe failed: Failed to read status file /status/status.json: unexpected end of JSON input
  Warning  BackOff    4m40s (x68 over 19m)  kubelet            Back-off restarting failed container
```

### Additional information

kube-system   calico-kube-controllers-75ddb95444-h6gts   0/1     CrashLoopBackOff             8          20m
kube-system   calico-node-7m7v8                          1/1     Running                      0          80m
kube-system   calico-node-rxw5t                          0/1     CreateContainerConfigError   0          80m
kube-system   coredns-5495dd7c88-48v44                   0/1     Running                      0          80m
kube-system   coredns-5495dd7c88-cgdxp                   0/1     Running                      0          80m
kube-system   kube-apiserver-master                      1/1     Running                      0          80m
kube-system   kube-controller-manager-master             1/1     Running                      0          80m
kube-system   kube-proxy-58b62                           1/1     Running                      0          80m
kube-system   kube-proxy-l49mk                           1/1     Running                      0          80m
kube-system   kube-scheduler-master                      1/1     Running                      0          80m
kube-system   nodelocaldns-4bftg                         1/1     Running                      0          80m
kube-system   nodelocaldns-hw444                         1/1     Running                      0          80m
