### ISSUE TITLE
timeout failed

### ISSUE THREAD

**Issue by Nello-Angelo** [kubesphere/kubekey#1288]
### What is version of KubeKey has the issue?

A versions with  a "timeout" option for the host TCP connection to establish

### What is your os environment?

centos 7

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master1, address: 192.168.101.128, internalAddress: 192.168.101.128, user: root, password: "123"}
  - {name: worker, address: 192.168.101.131, internalAddress: 192.168.101.131, user: root, password: "123"}
  - {name: worker2, address: 192.168.101.134, internalAddress: 192.168.101.134, user: root, password: "123"}
  roleGroups:
    etcd:
    - master1
    control-plane: 
    - master1
    worker:
    - worker
    - worker2
  controlPlaneEndpoint: 
    internalLoadbalancer: haproxy
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.23.6
    clusterName: cluster.local
    masqueradeAll: false 
    maxPods: 110 
    nodeCidrMaskSize: 24  
    proxyMode: ipvs
  etcd:
    type: kubeadm
  network:
    plugin: calico
    calico:
      ipipMode: Never
      vxlanMode: Never  
      vethMTU: 1440
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    multusCNI:
      enabled: false
  registry:
    plainHTTP: false
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

failed after a time when kubekey checked hosts

### Relevant log output

```shell
14:07:49 MSK [GreetingsModule] Greetings
14:07:49 MSK message: [worker2]
Greetings, KubeKey!
14:08:19 MSK success: [worker2]
14:08:19 MSK failed: [master1]
14:08:19 MSK failed: [worker]
error: Pipeline[CreateClusterPipeline] execute failed: Module[GreetingsModule] exec failed:
failed: [master1] execute task timeout, Timeout=30000000000
failed: [worker] execute task timeout, Timeout=30000000000
```

### Additional information

this happen every time after you added a "timeout" option for the host TCP connection 

you need to add a key to set custome timeout or increase timeout maybe 10 minutes
