### ISSUE TITLE
When the offline installation pushes the private registry, it will push any image to the private registry kubesphereio namespace

### ISSUE THREAD

**Issue by e421083458** [kubesphere/kubekey#1311]
### What is version of KubeKey has the issue?

2.0.0

### What is your os environment?

centos7.2

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: new-web01.gz01, address: 100.74.181.59, internalAddress: 100.74.181.59, user: kubesphere, password: "123456"}
  roleGroups:
    etcd:
    - new-web01.gz01
    control-plane:
    - new-web01.gz01
    worker:
    - new-web01.gz01
    registry:
    - new-web01.gz01
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.21.5
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    type: harbor
    auths:
      "dockerhub.kubekey.local":
        username: admin
        password: Harbor12345
    plainHTTP: false
    privateRegistry: "dockerhub.kubekey.local"
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
  addons: []



---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.2.1
spec:
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  local_registry: ""
  namespace_override: ""
  # dev_tag: ""
  etcd:
    monitoring: false
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    # apiserver:
    #  resources: {}
    # controllerManager:
    #  resources: {}
    redis:
      enabled: false
      volumeSize: 2Gi
    openldap:
      enabled: false
      volumeSize: 2Gi
    minio:
      volumeSize: 20Gi
    monitoring:
      # type: external
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      GPUMonitoring:
        enabled: false
    gpu:
      kinds:
      - resourceName: "nvidia.com/gpu"
        resourceType: "GPU"
        default: true
    es:
      # master:
      #   volumeSize: 4Gi
      #   replicas: 1
      #   resources: {}
      # data:
      #   volumeSize: 20Gi
      #   replicas: 1
      #   resources: {}
      logMaxAge: 7
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchHost: ""
      externalElasticsearchPort: ""
  alerting:
    enabled: false
    # thanosruler:
    #   replicas: 1
    #   resources: {}
  auditing:
    enabled: false
    # operator:
    #   resources: {}
    # webhook:
    #   resources: {}
  devops:
    enabled: false
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 512m
    jenkinsJavaOpts_Xmx: 512m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: false
    # operator:
    #   resources: {}
    # exporter:
    #   resources: {}
    # ruler:
    #   enabled: true
    #   replicas: 2
    #   resources: {}
  logging:
    enabled: false
    containerruntime: docker
    logsidecar:
      enabled: true
      replicas: 2
      # resources: {}
  metrics_server:
    enabled: false
  monitoring:
    storageClass: ""
    # kube_rbac_proxy:
    #   resources: {}
    # kube_state_metrics:
    #   resources: {}
    # prometheus:
    #   replicas: 1
    #   volumeSize: 20Gi
    #   resources: {}
    #   operator:
    #     resources: {}
    #   adapter:
    #     resources: {}
    # node_exporter:
    #   resources: {}
    # alertmanager:
    #   replicas: 1
    #   resources: {}
    # notification_manager:
    #   resources: {}
    #   operator:
    #     resources: {}
    #   proxy:
    #     resources: {}
    gpu:
      nvidia_dcgm_exporter:
        enabled: false
        # resources: {}
  multicluster:
    clusterRole: none
  network:
    networkpolicy:
      enabled: false
    ippool:
      type: none
    topology:
      type: none
  openpitrix:
    store:
      enabled: false
  servicemesh:
    enabled: false
  kubeedge:
    enabled: false
    cloudCore:
      nodeSelector: {"node-role.kubernetes.io/worker": ""}
      tolerations: []
      cloudhubPort: "10000"
      cloudhubQuicPort: "10001"
      cloudhubHttpsPort: "10002"
      cloudstreamPort: "10003"
      tunnelPort: "10004"
      cloudHub:
        advertiseAddress:
          - ""
        nodeLimit: "100"
      service:
        cloudhubNodePort: "30000"
        cloudhubQuicNodePort: "30001"
        cloudhubHttpsNodePort: "30002"
        cloudstreamNodePort: "30003"
        tunnelNodePort: "30004"
    edgeWatcher:
      nodeSelector: {"node-role.kubernetes.io/worker": ""}
      tolerations: []
      edgeWatcherAgent:
        nodeSelector: {"node-role.kubernetes.io/worker": ""}
        tolerations: []
```

### A clear and concise description of what happend.

I conducted offline deployment and installation by referring to the latest documents，https://kubesphere.com.cn/docs/installing-on-linux/introduction/air-gapped-installation/
The pre operation is as follows:
`
curl -sfL https://get-kk.kubesphere.io | VERSION=v2.0.0 sh -
./kk create manifest
./kk artifact export -m manifest-sample.yaml -o kubesphere.tar.gz
./kk init registry -f config-sample.yaml -a kubesphere.tar.gz
`

When I execute
`
./kk create cluster -f config-sample.yaml -a kubesphere.tar.gz --with-packages
`
When an execution error occurs, it will be pushed to the private registry kubesphereio, regardless of any image.

### Relevant log output

```shell
root@new-server01.gz01:~/kubesphere$ ./kk create cluster -f config-sample.yaml -a kubesphere.tar.gz --with-packages


 _   __      _          _   __
| | / /     | |        | | / /
| |/ / _   _| |__   ___| |/ /  ___ _   _
|    \| | | | '_ \ / _ \    \ / _ \ | | |
| |\  \ |_| | |_) |  __/ |\  \  __/ |_| |
\_| \_/\__,_|_.__/ \___\_| \_/\___|\__, |
                                    __/ |
                                   |___/

22:19:39 CST [NodePreCheckModule] A pre-check on nodes
22:19:40 CST success: [ipd-new-web01.gz01]
22:19:40 CST [ConfirmModule] Display confirmation form
+--------------------+------+------+---------+----------+-------+-------+-----------+--------+----------+------------+-------------+------------------+--------------+
| name               | sudo | curl | openssl | ebtables | socat | ipset | conntrack | chrony | docker   | nfs client | ceph client | glusterfs client | time         |
+--------------------+------+------+---------+----------+-------+-------+-----------+--------+----------+------------+-------------+------------------+--------------+
| ipd-new-web01.gz01 | y    | y    | y       | y        | y     | y     | y         | y      | 20.10.16 | y          |             |                  | CST 22:19:40 |
+--------------------+------+------+---------+----------+-------+-------+-----------+--------+----------+------------+-------------+------------------+--------------+

This is a simple check of your environment.
Before installation, you should ensure that your machines meet all requirements specified at
https://github.com/kubesphere/kubekey#requirements-and-recommendations

Continue this installation? [yes/no]: yes
22:19:47 CST success: [LocalHost]
22:19:47 CST [UnArchiveArtifactModule] Check the KubeKey artifact md5 value
22:20:25 CST success: [LocalHost]
22:20:25 CST [UnArchiveArtifactModule] UnArchive the KubeKey artifact
/root/kubesphere/kubekey/cni/v0.9.1/amd64/cni-plugins-linux-amd64-v0.9.1.tgz
/root/kubesphere/kubekey/crictl/v1.22.0/amd64/crictl-v1.22.0-linux-amd64.tar.gz
/root/kubesphere/kubekey/docker/20.10.14/amd64/docker-20.10.14.tgz
/root/kubesphere/kubekey/docker/20.10.8/amd64/docker-20.10.8.tgz
/root/kubesphere/kubekey/etcd/v3.4.13/amd64/etcd-v3.4.13-linux-amd64.tar.gz
/root/kubesphere/kubekey/helm/v3.6.3/amd64/helm
/root/kubesphere/kubekey/images/docker.io#openpolicyagent#gatekeeper:v3.5.2.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#calico#cni:v3.20.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#calico#kube-controllers:v3.20.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#calico#node:v3.20.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#calico#pod2daemon-flexvol:v3.20.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#calico#typha:v3.20.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#coredns#coredns:1.8.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#csiplugin#snapshot-controller:v4.0.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#elastic#filebeat:6.7.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#fluent#fluentd:v1.4.2-2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#grafana#grafana:7.4.3.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#istio#pilot:1.11.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#istio#proxyv2:1.11.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#jaegertracing#jaeger-agent:1.27.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#jaegertracing#jaeger-collector:1.27.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#jaegertracing#jaeger-es-index-cleaner:1.27.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#jaegertracing#jaeger-operator:1.27.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#jaegertracing#jaeger-query:1.27.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#jenkins#jnlp-slave:3.27-1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#jimmidyson#configmap-reload:v0.3.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#joosthofman#wget:1.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubeedge#cloudcore:v1.7.2.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#builder-base:v3.2.0-podman.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#builder-base:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#builder-go:v3.2.0-podman.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#builder-go:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#builder-maven:v3.2.0-podman.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#builder-maven:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#builder-nodejs:v3.2.0-podman.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#builder-nodejs:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#builder-python:v3.2.0-podman.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#builder-python:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#devops-apiserver:v3.2.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#devops-controller:v3.2.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#devops-tools:v3.2.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#edge-watcher-agent:v0.1.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#edge-watcher:v0.1.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#elasticsearch-curator:v5.7.6.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#elasticsearch-oss:6.7.0-1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#examples-bookinfo-details-v1:1.16.2.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#examples-bookinfo-productpage-v1:1.16.2.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#examples-bookinfo-ratings-v1:1.16.3.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#examples-bookinfo-reviews-v1:1.16.2.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#examples-bookinfo-reviews-v2:1.16.2.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#flannel:v0.12.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#fluent-bit:v1.8.3.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#fluentbit-operator:v0.11.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#java-11-centos7:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#java-11-runtime:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#java-8-centos7:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#java-8-runtime:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#k8s-dns-node-cache:1.15.12.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#k8s-prometheus-adapter-amd64:v0.6.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kiali-operator:v1.38.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kiali:v1.38.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#ks-apiserver:v3.2.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#ks-console:v3.2.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#ks-controller-manager:v3.2.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#ks-installer:v3.2.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#ks-jenkins:v3.2.0-2.249.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-apiserver:v1.19.9.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-apiserver:v1.20.10.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-apiserver:v1.21.5.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-apiserver:v1.22.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-auditing-operator:v0.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-auditing-webhook:v0.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-controller-manager:v1.19.9.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-controller-manager:v1.20.10.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-controller-manager:v1.21.5.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-controller-manager:v1.22.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-events-exporter:v0.3.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-events-operator:v0.3.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-events-ruler:v0.3.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-proxy:v1.19.9.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-proxy:v1.20.10.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-proxy:v1.21.5.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-proxy:v1.22.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-rbac-proxy:v0.8.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-scheduler:v1.19.9.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-scheduler:v1.20.10.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-scheduler:v1.21.5.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-scheduler:v1.22.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kube-state-metrics:v1.9.7.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kubectl:v1.20.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#kubefed:v0.8.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#log-sidecar-injector:1.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#metrics-server:v0.4.2.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#netshoot:v1.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#nginx-ingress-controller:v0.48.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#nodejs-4-centos7:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#nodejs-6-centos7:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#nodejs-8-centos7:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#notification-manager-operator:v1.4.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#notification-manager:v1.4.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#notification-tenant-sidecar:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#openpitrix-jobs:v3.2.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#pause:3.4.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#pause:3.5.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#prometheus-config-reloader:v0.43.2.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#prometheus-operator:v0.43.2.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#python-27-centos7:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#python-34-centos7:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#python-35-centos7:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#python-36-centos7:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#s2i-binary:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#s2ioperator:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#s2irun:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#tomcat85-java11-centos7:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#tomcat85-java11-runtime:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#tomcat85-java8-centos7:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#tomcat85-java8-runtime:v3.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#kubesphere#tower:v0.2.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#library#alpine:3.14.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#library#busybox:1.31.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#library#docker:19.03.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#library#haproxy:2.0.25-alpine.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#library#java:openjdk-8-jre-alpine.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#library#nginx:1.14-alpine.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#library#perl:latest.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#library#redis:5.0.14-alpine.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#library#wordpress:4.8-apache.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#minio#mc:RELEASE.2019-08-07T23-14-43Z.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#minio#minio:RELEASE.2019-08-07T01-59-21Z.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#mirrorgooglecontainers#defaultbackend-amd64:1.4.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#mirrorgooglecontainers#hpa-example:latest.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#nginxdemos#hello:plain-text.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#openebs#linux-utils:2.10.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#openebs#provisioner-localpv:2.10.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#osixia#openldap:1.3.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#prom#alertmanager:v0.21.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#prom#node-exporter:v0.18.1.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#prom#prometheus:v2.26.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#thanosio#thanos:v0.18.0.tar
/root/kubesphere/kubekey/images/dockerhub.kubekey.local#weaveworks#scope:1.13.0.tar
/root/kubesphere/kubekey/kube/v1.21.5/amd64/kubeadm
/root/kubesphere/kubekey/kube/v1.21.5/amd64/kubectl
/root/kubesphere/kubekey/kube/v1.21.5/amd64/kubelet
/root/kubesphere/kubekey/registry/compose/v2.2.2/amd64/docker-compose-linux-x86_64
/root/kubesphere/kubekey/registry/harbor/v2.4.1/amd64/harbor-offline-installer-v2.4.1.tgz
/root/kubesphere/kubekey/repository/amd64/centos/7/centos-7-amd64.iso
22:22:19 CST success: [LocalHost]
22:22:19 CST [UnArchiveArtifactModule] Create the KubeKey artifact Md5 file
22:22:58 CST success: [LocalHost]
22:22:58 CST [RepositoryModule] Get OS release
22:22:58 CST success: [ipd-new-web01.gz01]
22:22:58 CST [RepositoryModule] Sync repository iso file to all nodes
22:23:01 CST success: [ipd-new-web01.gz01]
22:23:01 CST [RepositoryModule] Mount iso file
22:23:01 CST success: [ipd-new-web01.gz01]
22:23:01 CST [RepositoryModule] Backup original repository
22:23:01 CST success: [ipd-new-web01.gz01]
22:23:01 CST [RepositoryModule] Add local repository
22:23:02 CST stdout: [ipd-new-web01.gz01]
Loaded plugins: aliases, fastestmirror,
              : protectbase
Cleaning repos: base-local
Cleaning up list of fastest mirrors
Other repos take up 197 M of disk space (use --verbose for details)
Loaded plugins: aliases, fastestmirror,
              : protectbase
Determining fastest mirrors
base-local                 | 2.9 kB     00:00
(1/3): base-local/filelists_ | 100 kB   00:00
(2/3): base-local/primary_db | 188 kB   00:00
(3/3): base-local/other_db   |  87 kB   00:00
Metadata Cache Created
22:23:02 CST success: [ipd-new-web01.gz01]
22:23:02 CST [RepositoryModule] Install packages
22:23:03 CST stdout: [ipd-new-web01.gz01]
Loaded plugins: aliases, fastestmirror,
              : protectbase
Loading mirror speeds from cached hostfile
0 packages excluded due to repository protections
Package matching 1:openssl-1.0.2k-22.el7_9.x86_64 already installed. Checking for update.
Package socat-1.7.3.2-2.el7.x86_64 already installed and latest version
Package conntrack-tools-1.4.4-7.el7.x86_64 already installed and latest version
Package ipset-7.1-1.el7.x86_64 already installed and latest version
Package ebtables-2.0.10-16.el7.x86_64 already installed and latest version
Package chrony-3.4-1.el7.x86_64 already installed and latest version
Nothing to do
22:23:03 CST success: [ipd-new-web01.gz01]
22:23:03 CST [RepositoryModule] Reset repository to the original repository
22:23:03 CST success: [ipd-new-web01.gz01]
22:23:03 CST [RepositoryModule] Umount ISO file
22:23:03 CST success: [ipd-new-web01.gz01]
22:23:03 CST [NodeBinariesModule] Download installation binaries
22:23:03 CST message: [localhost]
downloading amd64 kubeadm v1.21.5 ...
22:23:03 CST message: [localhost]
kubeadm is existed
22:23:03 CST message: [localhost]
downloading amd64 kubelet v1.21.5 ...
22:23:04 CST message: [localhost]
kubelet is existed
22:23:04 CST message: [localhost]
downloading amd64 kubectl v1.21.5 ...
22:23:04 CST message: [localhost]
kubectl is existed
22:23:04 CST message: [localhost]
downloading amd64 helm v3.6.3 ...
22:23:05 CST message: [localhost]
helm is existed
22:23:05 CST message: [localhost]
downloading amd64 kubecni v0.9.1 ...
22:23:05 CST message: [localhost]
kubecni is existed
22:23:05 CST message: [localhost]
downloading amd64 docker 20.10.8 ...
22:23:05 CST message: [localhost]
docker is existed
22:23:05 CST message: [localhost]
downloading amd64 crictl v1.22.0 ...
22:23:05 CST message: [localhost]
crictl is existed
22:23:05 CST message: [localhost]
downloading amd64 etcd v3.4.13 ...
22:23:06 CST message: [localhost]
etcd is existed
22:23:06 CST success: [LocalHost]
22:23:06 CST [ConfigureOSModule] Prepare to init OS
22:23:08 CST success: [ipd-new-web01.gz01]
22:23:08 CST [ConfigureOSModule] Generate init os script
22:23:09 CST success: [ipd-new-web01.gz01]
22:23:09 CST [ConfigureOSModule] Exec init os script
22:23:10 CST stdout: [ipd-new-web01.gz01]
setenforce: SELinux is disabled
Disabled
net.ipv4.ip_forward = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
kernel.sysrq = 0
kernel.core_uses_pid = 1
net.ipv4.tcp_syncookies = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-arptables = 1
kernel.msgmnb = 65536
kernel.msgmax = 65536
kernel.shmmax = 68719476736
kernel.shmall = 4294967296
kernel.panic = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.default.arp_ignore = 1
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.all.arp_announce = 2
net.ipv4.ip_no_pmtu_disc = 1
kernel.printk = 3 4 1 7
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.ip_local_port_range = 10000 65535
net.ipv4.tcp_max_tw_buckets = 180000
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_tw_recycle = 0
kernel.core_pattern = |/usr/local/bin/core_filter -P %P -p %p -e %e -t %t -s 102400
net.core.somaxconn = 4096
net.ipv4.tcp_max_syn_backlog = 4096
net.core.netdev_max_backlog = 4096
vm.vfs_cache_pressure = 200
vm.min_free_kbytes = 409600
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
vm.swappiness = 1
fs.inotify.max_user_instances = 524288
kernel.pid_max = 65535
22:23:10 CST success: [ipd-new-web01.gz01]
22:23:10 CST [ConfigureOSModule] configure the ntp server for each node
22:23:10 CST skipped: [ipd-new-web01.gz01]
22:23:10 CST [KubernetesStatusModule] Get kubernetes cluster status
22:23:11 CST success: [ipd-new-web01.gz01]
22:23:11 CST [InstallContainerModule] Sync docker binaries
22:23:11 CST skipped: [ipd-new-web01.gz01]
22:23:11 CST [InstallContainerModule] Generate containerd service
22:23:11 CST skipped: [ipd-new-web01.gz01]
22:23:11 CST [InstallContainerModule] Enable containerd
22:23:11 CST skipped: [ipd-new-web01.gz01]
22:23:11 CST [InstallContainerModule] Generate docker service
22:23:11 CST skipped: [ipd-new-web01.gz01]
22:23:11 CST [InstallContainerModule] Generate docker config
22:23:11 CST skipped: [ipd-new-web01.gz01]
22:23:11 CST [InstallContainerModule] Enable docker
22:23:11 CST skipped: [ipd-new-web01.gz01]
22:23:11 CST [InstallContainerModule] Add auths to container runtime
22:23:12 CST success: [ipd-new-web01.gz01]
22:23:12 CST [PushModule] Push images to private registry
push dockerhub.kubekey.local/kubesphereio/gatekeeper:v3.5.2 success
push dockerhub.kubekey.local/kubesphereio/cni:v3.20.0 success
push dockerhub.kubekey.local/kubesphereio/kube-controllers:v3.20.0 success
push dockerhub.kubekey.local/kubesphereio/node:v3.20.0 success
push dockerhub.kubekey.local/kubesphereio/pod2daemon-flexvol:v3.20.0 success
push dockerhub.kubekey.local/kubesphereio/typha:v3.20.0 success
push dockerhub.kubekey.local/kubesphereio/coredns:1.8.0 success
push dockerhub.kubekey.local/kubesphereio/snapshot-controller:v4.0.0 success
push dockerhub.kubekey.local/kubesphereio/filebeat:6.7.0 success
push dockerhub.kubekey.local/kubesphereio/fluentd:v1.4.2-2.0 success
push dockerhub.kubekey.local/kubesphereio/grafana:7.4.3 success
push dockerhub.kubekey.local/kubesphereio/pilot:1.11.1 success
push dockerhub.kubekey.local/kubesphereio/proxyv2:1.11.1 success
push dockerhub.kubekey.local/kubesphereio/jaeger-agent:1.27 success
push dockerhub.kubekey.local/kubesphereio/jaeger-collector:1.27 success
push dockerhub.kubekey.local/kubesphereio/jaeger-es-index-cleaner:1.27 success
push dockerhub.kubekey.local/kubesphereio/jaeger-operator:1.27 success
push dockerhub.kubekey.local/kubesphereio/jaeger-query:1.27 success
push dockerhub.kubekey.local/kubesphereio/jnlp-slave:3.27-1 succ
```
