### ISSUE TITLE
2.2.1离线安装推送私服报错

### ISSUE THREAD

**Issue by luminus-xt** [kubesphere/kubekey#1376]
### What is version of KubeKey has the issue?

2.2.1

### What is your os environment?

kylin v10

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: k8s-node1, address: 10.81.193.109, internalAddress: 10.81.193.109, user: root, password: "Admin@123"}
  - {name: k8s-node2, address: 10.81.193.110, internalAddress: 10.81.193.110, user: root, password: "111111"}
  - {name: k8s-node3, address: 10.81.193.111, internalAddress: 10.81.193.111, user: root, password: "111111"}
  roleGroups:
    etcd:
    - k8s-node1
    control-plane:
    - k8s-node1
    worker:
    - k8s-node1
    - k8s-node2
    - k8s-node3
    registry:
    - k8s-node1
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.22.10
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: docker
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    type: harbor
    auth:
      "dockerhub.kubekey.local":
        username: "admin"
        password: "Harbor12345"
        skipTLSVerify: true
#        certsPath: "/etc/docker/certs.d/dockerhub.kubekey.local/"
    privateRegistry: "dockerhub.kubekey.local"
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

docker可以正常登录私服
![image](https://user-images.githubusercontent.com/106000358/178936979-2df3a8c0-ccd4-4c6d-9688-97d6a520e43e.png)
但是通过kubekey安装集群时候会报错
![image](https://user-images.githubusercontent.com/106000358/178937140-1a180e51-9562-489a-b285-14abd7a246c8.png)

**Comment by 24sama** [comment]
Hi @luminus-xt 
I see your config is:
```
registry:
    type: harbor
    auth:
      "dockerhub.kubekey.local":
        username: "admin"
        password: "Harbor12345"
        skipTLSVerify: true
#        certsPath: "/etc/docker/certs.d/dockerhub.kubekey.local/"
    privateRegistry: "dockerhub.kubekey.local"
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
```
And you use the command `docker login https://10.81.193.109`.
So I guess your `privateRegistry` is `https://10.81.193.109`. You have the wrong configuration in the kk config file. Maybe it should be:
```
registry:
    type: harbor
    auth:
      "10.81.193.109":
        skipTLSVerify: true
#        certsPath: "/etc/docker/certs.d/dockerhub.kubekey.local/"
    privateRegistry: "10.81.193.109"
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
```
