### ISSUE TITLE
offline install failed: "reading manifest 3.14 in docker.io/docker.io/alpine: unauthorized"

### ISSUE THREAD

**Issue by panbasten** [kubesphere/kubekey#1383]
### What is version of KubeKey has the issue?

v2.2.1

### What is your os environment?

centos 7

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master, address: 172.16.30.61, internalAddress: 172.16.30.61, user: root, password: ""}
  - {name: node4, address: 172.16.30.121, internalAddress: 172.16.30.121, user: root, password: ""}
  - {name: node5, address: 172.16.30.122, internalAddress: 172.16.30.122, user: root, password: ""}
  - {name: node6, address: 172.16.30.123, internalAddress: 172.16.30.123, user: root, password: ""}
  - {name: node7, address: 172.16.30.124, internalAddress: 172.16.30.124, user: root, password: ""}
  - {name: node8, address: 172.16.30.125, internalAddress: 172.16.30.125, user: root, password: ""}
  - {name: node9, address: 172.16.30.126, internalAddress: 172.16.30.126, user: root, password: ""}
  roleGroups:
    etcd:
    - master
    - node4
    - node7
    control-plane:
    - master
    - node4
    - node7
    worker:
    - node4
    - node5
    - node6
    - node7
    - node8
    - node9
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.22.10
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: docker
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []



---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.3.0
spec:
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  zone: ""
  local_registry: ""
  namespace_override: ""
  # dev_tag: ""
  etcd:
    monitoring: false
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    # apiserver:
    #  resources: {}
    # controllerManager:
    #  resources: {}
    redis:
      enabled: true
      volumeSize: 2Gi
    openldap:
      enabled: false
      volumeSize: 2Gi
    minio:
      volumeSize: 20Gi
    monitoring:
      # type: external
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      GPUMonitoring:
        enabled: false
    gpu:
      kinds:
      - resourceName: "nvidia.com/gpu"
        resourceType: "GPU"
        default: true
    es:
      master:
        volumeSize: 4Gi
        replicas: 1
        resources: {}
      data:
        volumeSize: 20Gi
        replicas: 1
        resources: {}
      logMaxAge: 7
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchHost: ""
      externalElasticsearchPort: ""
  alerting:
    enabled: true
    # thanosruler:
    #   replicas: 1
    #   resources: {}
  auditing:
    enabled: true
    # operator:
    #   resources: {}
    # webhook:
    #   resources: {}
  devops:
    enabled: false
    # resources: {}
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 1200m
    jenkinsJavaOpts_Xmx: 1600m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: true
    # operator:
    #   resources: {}
    # exporter:
    #   resources: {}
    # ruler:
    #   enabled: true
    #   replicas: 2
    #   resources: {}
  logging:
    enabled: true
    logsidecar:
      enabled: true
      replicas: 2
      # resources: {}
  metrics_server:
    enabled: false
  monitoring:
    storageClass: ""
    node_exporter:
      port: 9100
      # resources: {}
    # kube_rbac_proxy:
    #   resources: {}
    # kube_state_metrics:
    #   resources: {}
    # prometheus:
    #   replicas: 1
    #   volumeSize: 20Gi
    #   resources: {}
    #   operator:
    #     resources: {}
    # alertmanager:
    #   replicas: 1
    #   resources: {}
    # notification_manager:
    #   resources: {}
    #   operator:
    #     resources: {}
    #   proxy:
    #     resources: {}
    gpu:
      nvidia_dcgm_exporter:
        enabled: false
        # resources: {}
  multicluster:
    clusterRole: none
  network:
    networkpolicy:
      enabled: true
    ippool:
      type: calico
    topology:
      type: weave-scope
  openpitrix:
    store:
      enabled: false
  servicemesh:
    enabled: true
    istio:
      components:
        ingressGateways:
        - name: istio-ingressgateway
          enabled: false
        cni:
          enabled: false
  edgeruntime:
    enabled: false
    kubeedge:
      enabled: false
      cloudCore:
        cloudHub:
          advertiseAddress:
            - ""
        service:
          cloudhubNodePort: "30000"
          cloudhubQuicNodePort: "30001"
          cloudhubHttpsNodePort: "30002"
          cloudstreamNodePort: "30003"
          tunnelNodePort: "30004"
        # resources: {}
        # hostNetWork: false
      iptables-manager:
        enabled: true
        mode: "external"
        # resources: {}
      # edgeService:
      #   resources: {}
  terminal:
    timeout: 600
```

### A clear and concise description of what happend.

./kk create manifest
./kk artifact export -m manifest-sample.yaml -o kubesphere.tar.gz

manifest-sample.yaml

```

apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Manifest
metadata:
  name: sample
spec:
  arches:
  - amd64
  operatingSystems:
  - arch: amd64
    type: linux
    id: centos
    version: "7"
    osImage: CentOS Linux 7 (Core)
    repository:
      iso:
        localPath:
        url:
  kubernetesDistributions:
  - type: kubernetes
    version: v1.22.10
  components:
    helm:
      version: v3.6.3
    cni:
      version: v0.9.1
    etcd:
      version: v3.4.13
    containerRuntimes:
    - type: docker
      version: 1.13.1
    crictl:
      version: v1.24.0
    ##
    # docker-registry:
    #   version: "2"
    # harbor:
    #   version: v2.4.1
    # docker-compose:
    #   version: v2.2.2
  images:
  - docker.io/calico/cni:v3.20.0
  - docker.io/calico/kube-controllers:v3.20.0
  - docker.io/calico/node:v3.20.0
  - docker.io/calico/pod2daemon-flexvol:v3.20.0
  - docker.io/coredns/coredns:1.8.0
  - docker.io/csiplugin/snapshot-controller:v4.0.0
  - docker.io/docker.io/alpine:3.14
  - docker.io/docker.io/docker:19.03
  - docker.io/docker.io/haproxy:2.3
  - docker.io/docker.io/redis:5.0.14-alpine
  - docker.io/docker.io/registry:2.6
  - docker.io/istio/pilot:1.11.1
  - docker.io/jaegertracing/jaeger-agent:1.27
  - docker.io/jaegertracing/jaeger-collector:1.27
  - docker.io/jaegertracing/jaeger-operator:1.27
  - docker.io/jaegertracing/jaeger-query:1.27
  - docker.io/jimmidyson/configmap-reload:v0.5.0
  - docker.io/kubesphere/elasticsearch-oss:6.8.22
  - docker.io/kubesphere/fluent-bit:v1.8.11
  - docker.io/kubesphere/fluentbit-operator:v0.13.0
  - docker.io/kubesphere/k8s-dns-node-cache:1.15.12
  - docker.io/kubesphere/kiali-operator:v1.38.1
  - docker.io/kubesphere/kiali:v1.38
  - docker.io/kubesphere/ks-apiserver:v3.3.0
  - docker.io/kubesphere/ks-console:v3.3.0
  - docker.io/kubesphere/ks-controller-manager:v3.3.0
  - docker.io/kubesphere/ks-installer:v3.3.0
  - docker.io/kubesphere/kube-apiserver:v1.22.10
  - docker.io/kubesphere/kube-auditing-operator:v0.2.0
  - docker.io/kubesphere/kube-auditing-webhook:v0.2.0
  - docker.io/kubesphere/kube-controller-manager:v1.22.10
  - docker.io/kubesphere/kube-events-exporter:v0.4.0
  - docker.io/kubesphere/kube-events-operator:v0.4.0
  - docker.io/kubesphere/kube-events-ruler:v0.4.0
  - docker.io/kubesphere/kube-proxy:v1.22.10
  - docker.io/kubesphere/kube-rbac-proxy:v0.11.0
  - docker.io/kubesphere/kube-rbac-proxy:v0.8.0
  - docker.io/kubesphere/kube-scheduler:v1.22.10
  - docker.io/kubesphere/kube-state-metrics:v2.3.0
  - docker.io/kubesphere/kubectl:v1.22.0
  - docker.io/kubesphere/log-sidecar-injector:1.1
  - docker.io/kubesphere/notification-manager-operator:v1.4.0
  - docker.io/kubesphere/notification-manager:v1.4.0
  - docker.io/kubesphere/notification-tenant-sidecar:v3.2.0
  - docker.io/kubesphere/pause:3.5
  - docker.io/kubesphere/prometheus-config-reloader:v0.55.1
  - docker.io/kubesphere/prometheus-operator:v0.55.1
  - docker.io/mirrorgooglecontainers/defaultbackend-amd64:1.4
  - docker.io/openebs/linux-utils:2.10.0
  - docker.io/openebs/provisioner-localpv:2.10.1
  - docker.io/prom/alertmanager:v0.23.0
  - docker.io/prom/node-exporter:v1.3.1
  - docker.io/prom/prometheus:v2.34.0
  - docker.io/thanosio/thanos:v0.25.2
  - docker.io/weaveworks/scope:1.13.0
  registry:
    auths:
      "dockerhub.kubekey.local":
        username: "panbasten"
        password: "panda26"
        skipTLSVerify: false # Allow contacting registries over HTTPS with failed TLS verification.
        plainHTTP: false # Allow contacting registries over HTTP.
        certsPath: "/etc/docker/certs.d/dockerhub.kubekey.local" # Use certificates at path (*.crt, *.cert, *.key) to connect to the registry.


```

### Relevant log output

```shell
20:34:59 EDT Source: docker://docker.io/calico/pod2daemon-flexvol:v3.20.0
20:34:59 EDT Destination: oci:/data/_bak/master_kk/kubekey/artifact/images:calico:pod2daemon-flexvol:v3.20.0-amd64
Getting image source signatures
Copying blob 3352f112e445 skipped: already exists  
Copying blob c2fe5564d909 skipped: already exists  
Copying blob 4bb92edc9dbf skipped: already exists  
Copying blob eac675be51f6 skipped: already exists  
Copying blob 966bd0f3e149 skipped: already exists  
Copying blob 4aaab3250002 skipped: already exists  
Copying blob c948de259b51 skipped: already exists  
Copying config b98200c9a6 done  
Writing manifest to image destination
Storing signatures
20:35:04 EDT Source: docker://docker.io/coredns/coredns:1.8.0
20:35:04 EDT Destination: oci:/data/_bak/master_kk/kubekey/artifact/images:coredns:coredns:1.8.0-amd64
Getting image source signatures
Copying blob 5984b6d55edf skipped: already exists  
Copying blob c6568d217a00 skipped: already exists  
Copying config b87146fdf5 done  
Writing manifest to image destination
Storing signatures
20:35:09 EDT Source: docker://docker.io/csiplugin/snapshot-controller:v4.0.0
20:35:09 EDT Destination: oci:/data/_bak/master_kk/kubekey/artifact/images:csiplugin:snapshot-controller:v4.0.0-amd64
Getting image source signatures
Copying blob 0810b1707876 skipped: already exists  
Copying blob e59bd8947ac7 skipped: already exists  
Copying config 9f8a5ab207 done  
Writing manifest to image destination
Storing signatures
20:35:14 EDT Source: docker://docker.io/docker.io/alpine:3.14
20:35:14 EDT Destination: oci:/data/_bak/master_kk/kubekey/artifact/images:docker.io:alpine:3.14-amd64
20:35:17 EDT message: [LocalHost]
initializing source docker://docker.io/alpine:3.14: reading manifest 3.14 in docker.io/docker.io/alpine: unauthorized
20:35:17 EDT failed: [LocalHost]
error: Pipeline[ArtifactExportPipeline] execute failed: Module[CopyImagesToLocalModule] exec failed: 
failed: [LocalHost] [SaveImages] exec failed after 1 retires: initializing source docker://docker.io/alpine:3.14: reading manifest 3.14 in docker.io/docker.io/alpine: unauthorized
```

### Additional information

"docker.io/docker.io/alpine:3.14" modify to "docker.io/alpine:3.14" also failed

log

```
Storing signatures
20:33:20 EDT Source: docker://docker.io/csiplugin/snapshot-controller:v4.0.0
20:33:20 EDT Destination: oci:/data/_bak/master_kk/kubekey/artifact/images:csiplugin:snapshot-controller:v4.0.0-amd64
Getting image source signatures
Copying blob 0810b1707876 skipped: already exists  
Copying blob e59bd8947ac7 skipped: already exists  
Copying config 9f8a5ab207 done  
Writing manifest to image destination
Storing signatures
panic: runtime error: index out of range [2] with length 2

goroutine 94 [running]:
github.com/kubesphere/kubekey/pkg/images.(*SaveImages).Execute(0xc000464e70, {0x2637cc0, 0xc00015b340})
        /home/runner/work/kubekey/kubekey/pkg/images/tasks.go:169 +0x8f2
github.com/kubesphere/kubekey/pkg/core/task.(*LocalTask).ExecuteWithRetry(0xc00015b290, {0x2637cc0, 0xc00015b340}, {0x2642580, 0xc0009340c0})
        /home/runner/work/kubekey/kubekey/pkg/core/task/local_task.go:203 +0x137
github.com/kubesphere/kubekey/pkg/core/task.(*LocalTask).Run(0xc00015b290, {0x2637cc0, 0xc00015b340}, {0x2642580, 0xc0009340c0}, 0xc000246480)
        /home/runner/work/kubekey/kubekey/pkg/core/task/local_task.go:157 +0x225
created by github.com/kubesphere/kubekey/pkg/core/task.(*LocalTask).RunWithTimeout
        /home/runner/work/kubekey/kubekey/pkg/core/task/local_task.go:119 +0x16f
```
