### ISSUE TITLE
normal user with sudo permissions have some promble

### ISSUE THREAD

**Issue by tanmx** [kubesphere/kubekey#1395]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"v2.2.1", GitCommit:"c056977c68b5d2056a77bd5410df65548a9c2c36", GitTreeState:"dirty", GoVersion:"go1.17.12"}

### What is your os environment?

Kylin Linux Advanced Server V10 (SP1)

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: 1-c86-uos
spec:
  hosts:
  - {name: xxxx, address: xxxxxx, internalAddress: xxxx, user: test, password: "xxxxx@test2020"}
  roleGroups:
    etcd:
    - xxxxx
    control-plane:
    - xxxxx
    worker:
    - xxxxx
    registry:
    - xxx
```

### A clear and concise description of what happend.

the user test hava the root permissions with sudo command

### Relevant log output

```shell
09:58:32 CST [ConfigureOSModule] Generate init os script
09:58:33 CST message: [xxxx]
scp file /mnt/kubekey/kubekey/xxxx/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
```
