### ISSUE TITLE
service 暴露 NodePort，端口 31005 以上 并且服务可用，为啥 netstat 查看不到 31005端口

### ISSUE THREAD

**Issue by Heyz6** [kubesphere/kubekey#1468]
### What is version of KubeKey has the issue?

2.2.0

### What is your os environment?

ceontos7.9

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: "192.168.66.66", internalAddress: "192.168.66.66", port: 22, user: "root", password: "password"}
  roleGroups:
    etcd:
    - node1
    control-plane:
    - node1
    worker:
    - node1
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.12.13
    clusterName: cluster.local
    autoRenewCerts: true
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

同样的安装 v1.0.1 能够正常暴露 ,咨询下 是 k8s 版本 升级导致的吗 目前 k8s 版本 v1.21.13
