### ISSUE TITLE
insecureRegistries not effect

### ISSUE THREAD

**Issue by willzhang** [kubesphere/kubekey#1495]
### What is version of KubeKey has the issue?

2.2.2

### What is your os environment?

centos7.6

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master1, address: 1xxxxx, internalAddress: 1xxxxx, user: root, password: "xxxxx"}
  - {name: master2, address: 1xxxxx, internalAddress: 1xxxxx, user: root, password: "xxxxx"}
  - {name: master3, address: 1xxxxx, internalAddress: 1xxxxx, user: root, password: "xxxxx"}
  - {name: worker1, address: 1xxxxx, internalAddress: 1xxxxx, user: root, password: "xxxxx"}
  - {name: worker2, address: 1xxxxx, internalAddress: 1xxxxx, user: root, password: "xxxxx"}
  - {name: worker3, address: 1xxxxx, internalAddress: 1xxxxx, user: root, password: "xxxxx"}
  roleGroups:
    etcd:
    - master1
    - master2
    - master3
    control-plane: 
    - master1
    - master2
    - master3
    worker:
    - worker1
    - worker2
    - worker3
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.24.1
    clusterName: kubesphere.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    type: "harbor"
    auths:
      "http://169.169.128.41":
         username: admin
         password: Harbor12345
         skipTLSVerify: true
    plainHTTP: false
    privateRegistry: "169.169.128.41"
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: ["169.169.128.41"]
  addons: []

---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.3.0
spec:
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  zone: ""
  local_registry: ""
  namespace_override: ""
  # dev_tag: ""
  etcd:
    monitoring: false
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    # apiserver:
    #  resources: {}
    # controllerManager:
    #  resources: {}
    redis:
      enabled: false
      volumeSize: 2Gi
    openldap:
      enabled: false
      volumeSize: 2Gi
    minio:
      volumeSize: 20Gi
    monitoring:
      # type: external
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      GPUMonitoring:
        enabled: false
    gpu:
      kinds:
      - resourceName: "nvidia.com/gpu"
        resourceType: "GPU"
        default: true
    es:
      # master:
      #   volumeSize: 4Gi
      #   replicas: 1
      #   resources: {}
      # data:
      #   volumeSize: 20Gi
      #   replicas: 1
      #   resources: {}
      logMaxAge: 7
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchHost: ""
      externalElasticsearchPort: ""
  alerting:
    enabled: false
    # thanosruler:
    #   replicas: 1
    #   resources: {}
  auditing:
    enabled: false
    # operator:
    #   resources: {}
    # webhook:
    #   resources: {}
  devops:
    enabled: true
    # resources: {}
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 1200m
    jenkinsJavaOpts_Xmx: 1600m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: false
    # operator:
    #   resources: {}
    # exporter:
    #   resources: {}
    # ruler:
    #   enabled: true
    #   replicas: 2
    #   resources: {}
  logging:
    enabled: true
    logsidecar:
      enabled: true
      replicas: 2
      # resources: {}
  metrics_server:
    enabled: true
  monitoring:
    storageClass: ""
    node_exporter:
      port: 9100
      # resources: {}
    # kube_rbac_proxy:
    #   resources: {}
    # kube_state_metrics:
    #   resources: {}
    # prometheus:
    #   replicas: 1
    #   volumeSize: 20Gi
    #   resources: {}
    #   operator:
    #     resources: {}
    # alertmanager:
    #   replicas: 1
    #   resources: {}
    # notification_manager:
    #   resources: {}
    #   operator:
    #     resources: {}
    #   proxy:
    #     resources: {}
    gpu:
      nvidia_dcgm_exporter:
        enabled: false
        # resources: {}
  multicluster:
    clusterRole: none
  network:
    networkpolicy:
      enabled: false
    ippool:
      type: none
    topology:
      type: none
  openpitrix:
    store:
      enabled: true
  servicemesh:
    enabled: false
    istio:
      components:
        ingressGateways:
        - name: istio-ingressgateway
          enabled: false
        cni:
          enabled: false
  edgeruntime:
    enabled: false
    kubeedge:
      enabled: false
      cloudCore:
        cloudHub:
          advertiseAddress:
            - ""
        service:
          cloudhubNodePort: "30000"
          cloudhubQuicNodePort: "30001"
          cloudhubHttpsNodePort: "30002"
          cloudstreamNodePort: "30003"
          tunnelNodePort: "30004"
        # resources: {}
        # hostNetWork: false
      iptables-manager:
        enabled: true
        mode: "external"
        # resources: {}
      # edgeService:
      #   resources: {}
  terminal:
    timeout: 600
```

### A clear and concise description of what happend.

 kk artifact export -m ks-v3.3.0-manifest.yaml -o kubesphere-v3.3.0-artifact.tar.gz |tee export.log
```
Getting image source signatures
Copying blob sha256:5f68dfd9f8d78f3535856ecc443b69b110c4003bd402e0e45996ef85b93cce79
Copying config sha256:75235052b8de33c182ea2df1a4df9eb4d36166dbae93eac2fc76a7ab4a33ef97
Writing manifest to image destination
Storing signatures
17:28:29 CST Source: docker://registry.cn-beijing.aliyuncs.com/kubesphereio/metrics-server:v0.4.2
17:28:29 CST Destination: oci:/data/kubekey/kubekey/artifact/images:kubesphereio:metrics-server:v0.4.2-amd64
Getting image source signatures
Copying blob sha256:125b87d77e36b5ef13edd14f8bb3f38ae061cfb3e951ad0a7293f5fb13929880
Copying blob sha256:9e4425256ce4503b2a009683be02372ee51d411e9cc3547919e064fee4970eab
17:31:00 CST message: [LocalHost]
writing blob: happened during read: read tcp 192.168.0.45:40920->39.107.19.13:80: read: connection reset by peer
17:31:00 CST failed: [LocalHost]
error: Pipeline[ArtifactExportPipeline] execute failed: Module[CopyImagesToLocalModule] exec failed: 
failed: [LocalHost] [SaveImages] exec failed after 1 retires: writing blob: happened during read: read tcp 192.168.0.45:40920->39.107.19.13:80: read: connection reset by peer
```

### Relevant log output

```shell
[root@harbor01 kubesphere]# docker push 169.169.128.41/library/nginx
Using default tag: latest
The push refers to repository [169.169.128.41/library/nginx]
d874fd2bc83b: Layer already exists 
32ce5f6a5106: Layer already exists 
f1db227348d0: Layer already exists 
b8d6e692a25e: Layer already exists 
e379e8aedd4d: Layer already exists 
2edcec3590a4: Layer already exists 
latest: digest: sha256:ee89b00528ff4f02f2405e4ee221743ebc3f8e8dd0bfd5c4c20a2fa2aaa7ede3 size: 1570
[root@harbor01 kubesphere]# cat /etc/docker/daemon.json 
{
  "registry-mirrors": ["https://uyah70su.mirror.aliyuncs.com"],
  "insecure-registries": ["169.169.128.41"],  
  "data-root": "/data/docker"
}
````
```


### Additional information

_No response_

**Comment by 24sama** [comment]
The kk artifact export doesn't use containerd or docker. So `insecureRegistries` doesn't work for it. Others, Your configuration file has some field indentation issues.
See:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/43993589/189255184-5b015303-b778-4756-a127-c65bd16bf6fa.png">
The `plainHTTP` have a indentation issue.
```
auths:
      "http://169.169.128.41":
         username: admin
         password: Harbor12345
         skipTLSVerify: true
         plainHTTP: true
    privateRegistry: "169.169.128.41"
```
