### ISSUE TITLE
FEAT: allow to configure ipvs scheduler method

### ISSUE THREAD

**Issue by vanloswang** [kubesphere/kubekey#1509]
### Your current KubeKey version

v2.2.2

### Describe this feature

There is no option to configure kube-proxy ipvs scheduler method.

### Describe the solution you'd like

Add an option to configure kube-proxy ipvs scheduler method as bellow.
```
    proxyMode: ipvs
    ipvsScheduler: rr
```

**Comment by 24sama** [comment]
Hi @vanloswang!
Try to configure it like this:
```
kuberneters:
  kubeProxyConfiguration:
    mode: ipvs
    ipvs:
      scheduler: rr
```
More configuration, please see: https://kubernetes.io/docs/reference/config-api/kube-proxy-config.v1alpha1/
