### ISSUE TITLE
节点不能被删除 node can not be deleted

### ISSUE THREAD

**Issue by lgzhaha** [kubesphere/kubekey#1533]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"1.1.1", GitCommit:"7f4b70f", GitTreeState:"", GoVersion:"go1.14.15"}

### What is your os environment?

CentOS Linux release 7.9.2009 (Core)

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts: 
  # You should complete the ssh information of the hosts
  - {name: kk-kubesphere-master, address: 10.180.4.25, internalAddress: 10.180.4.25}
  - {name: kk-kubesphere-node1, address: 10.180.4.43, internalAddress: 10.180.4.43}
  - {name: kk-kubesphere-node2, address: 10.180.4.23, internalAddress: 10.180.4.23}
  - {name: dev-qa-pre-k8s-node4, address: 10.180.4.23, internalAddress: 10.180.4.23}
  roleGroups:
    etcd:
    - kk-kubesphere-master
    - kk-kubesphere-node1
    - kk-kubesphere-node2
    master:
    - kk-kubesphere-master
    - kk-kubesphere-node1
    - kk-kubesphere-node2
    worker:
    - kk-kubesphere-master
    - kk-kubesphere-node1
    - kk-kubesphere-node2
    - dev-qa-pre-k8s-node4
  controlPlaneEndpoint:
    # If loadbalancer was used, 'address' should be set to loadbalancer's ip.
    domain: lb.kubesphere.local
    address: "10.180.4.25"
    port: 6443
  kubernetes:
    version: v1.19.8
    clusterName: cluster.local
    proxyMode: ipvs
    masqueradeAll: false
    maxPods: 110
    nodeCidrMaskSize: 24
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    privateRegistry: ""
```

### A clear and concise description of what happend.

按照配置文件所示，当删除节点名称为 dev-qa-pre-k8s-node4 时，按照官网提示https://kubesphere.com.cn/docs/v3.3/installing-on-linux/cluster-operation/remove-nodes  删除节点，当执行完命令 ./kk delete node dev-qa-pre-k8s-node4 -f sample.yaml 后节点不能被删除，但sample.yaml文件内关于 dev-qa-pre-k8s-node4 的一切信息已被清理。kubectl get node 和 kubectl describe node dev-qa-pre-k8s-node4 显示待删节点状态为正常，且可被调度。
