### ISSUE TITLE
容器运行时为containerd，自签名证书无法拉取镜像

### ISSUE THREAD

**Issue by vinsonzou** [kubesphere/kubekey#1536]
### Your current KubeKey version

version.BuildInfo{Version:"2.3.0-rc.2", GitCommit:"b731d2f4", GitTreeState:"", GoVersion:"go1.18.5"}

### Describe this feature

容器运行时：containerd
当前Harbor为默认证书，不受信任，导致新增节点或者部署时失败。

现在是临时修改/etc/containerd/config.toml解决
insecure_skip_verify = true

### Describe the solution you'd like

希望添加个开关调整配置文件

**Comment by 24sama** [comment]
Please see:
```
registry:
    registryMirrors: []
    insecureRegistries: []
    privateRegistry: ""
    namespaceOverride: ""
    auths: # if docker add by `docker login`, if containerd append to `/etc/containerd/config.toml`
      "dockerhub.kubekey.local":
        username: "xxx"
        password: "***"
        skipTLSVerify: false # Allow contacting registries over HTTPS with failed TLS verification.
        plainHTTP: false # Allow contacting registries over HTTP.
        certsPath: "/etc/docker/certs.d/dockerhub.kubekey.local"
```
If you configure this and you don't have containerd installed on your node, then kk will automatically generate config.yaml using the above configuration.
