### ISSUE TITLE
skip `Join control-plane node` when node already worker

### ISSUE THREAD

**Issue by way-zer** [kubesphere/kubekey#1546]
### What is version of KubeKey has the issue?

2.3.0-rc.3

### What is your os environment?

Ubuntu 18

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: new
spec:
  hosts: [] #hidden
  roleGroups:
    etcd:
    - nine
    - eleven
    - root100
    control-plane: 
    - nine
    - eleven
    - root100
    worker:
    - eight
    - nine
    - ten
    - eleven
    - root100
    - root101
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    internalLoadbalancer: kube-vip
#    domain: lb.kubesphere.local
    address: "10.106.128.146"
    port: 6443
  kubernetes:
    version: v1.23.8
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: docker
  etcd:
    type: kubekey
  network:
    plugin: fhannel
    kubePodsCIDR: 192.168.64.0/18
    kubeServiceCIDR: 192.168.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: [
      "https://mirror.baidubce.com",
      "https://hub-mirror.c.163.com",
      "https://i6mwaa6f.mirror.aliyuncs.com"
    ]
    insecureRegistries: ["192.168.16.231"]
  addons: []
```

### A clear and concise description of what happend.

I want to add worker as `control-plane`, but it skipped as it in cluster.

### Relevant log output

```shell
13:13:21 UTC [JoinNodesModule] Join control-plane node
13:13:21 UTC skipped: [root100]
13:13:21 UTC skipped: [nine]
13:13:21 UTC skipped: [eleven]
13:13:21 UTC [JoinNodesModule] Join worker node
13:13:21 UTC skipped: [root101]
13:13:21 UTC skipped: [eleven]
13:13:21 UTC skipped: [ten]
13:13:21 UTC skipped: [eight]
13:13:21 UTC skipped: [nine]
13:13:21 UTC skipped: [root100]
```
