### ISSUE TITLE
cilium 1.11.6 bug causes coredns to fail to start

### ISSUE THREAD

**Issue by vinsonzou** [kubesphere/kubekey#1551]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"2.3.0-rc.2", GitCommit:"b731d2f4", GitTreeState:"", GoVersion:"go1.18.5"}

### What is your os environment?

AlmaLinux 9.0

### KubeKey config file

```yaml
kubernetes:
    version: v1.24.3
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
    disableKubeProxy: true
  etcd:
    type: kubekey
  network:
    plugin: cilium
---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.3.1-rc.2
```

### A clear and concise description of what happend.

After using cilium, coredns cannot be started. cilium has reported bugs. cilium issues are as follows
- https://github.com/cilium/cilium/issues/20125#issuecomment-1199904785
- https://github.com/cilium/cilium/issues/20437#issuecomment-1199908416
