### ISSUE TITLE
[env: arm64] assigned an image with the wrong architecture(amd64)

### ISSUE THREAD

**Issue by niconical** [kubesphere/kubekey#1555]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"2.2.2", GitCommit:"2ef69c68", GitTreeState:"", GoVersion:"go1.17.12"}

### What is your os environment?

OS：openEuler release 20.03 (LTS)，CPU：KungPeng 920，Arch：arm64

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: 192.168.20.30, internalAddress: 192.168.20.30, user: xxxx, password: "xxxx", arch: arm64}
  roleGroups:
    etcd:
    - node1
    control-plane:
    - node1
    worker:
    - node1
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    # internalLoadbalancer: haproxy
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.22.10
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: docker
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

我在config文件里面指定了host架构为arm64，使用了默认的kubesphere版本，执行的安装命令为

```bash
kk create cluster -f ./config-sample.yaml --with-kubesphere
```

但是在安装kubeSphere组件时候，kubesphereio/defaultbackend安装了amd64版本的镜像：
```bash
[root@node1 logs]# kubectl get po -A
NAMESPACE                      NAME                                               READY   STATUS             RESTARTS       AGE
kube-system                    calico-kube-controllers-69cfcfdf6c-28bpz           1/1     Running            0              29m
kube-system                    calico-node-pdfhr                                  1/1     Running            0              29m
kube-system                    coredns-5495dd7c88-2f7px                           1/1     Running            0              29m
kube-system                    coredns-5495dd7c88-vvsf6                           1/1     Running            0              29m
kube-system                    kube-apiserver-node1                               1/1     Running            0              30m
kube-system                    kube-controller-manager-node1                      1/1     Running            0              30m
kube-system                    kube-proxy-jl5sp                                   1/1     Running            0              29m
kube-system                    kube-scheduler-node1                               1/1     Running            0              30m
kube-system                    nodelocaldns-bgbch                                 1/1     Running            0              29m
kube-system                    openebs-localpv-provisioner-6f8b56f75-b9576        1/1     Running            0              29m
kube-system                    snapshot-controller-0                              1/1     Running            0              28m
kubesphere-controls-system     default-http-backend-56d9d4fdf7-sbbmx              0/1     CrashLoopBackOff   10 (11s ago)   27m
kubesphere-controls-system     kubectl-admin-7685cdd85b-m5r64                     1/1     Running            0              24m
kubesphere-monitoring-system   alertmanager-main-0                                2/2     Running            0              25m
kubesphere-monitoring-system   kube-state-metrics-89f49579b-8wqbc                 3/3     Running            0              25m
kubesphere-monitoring-system   node-exporter-qks92                                2/2     Running            0              25m
kubesphere-monitoring-system   notification-manager-deployment-6ff7974fbd-44th5   2/2     Running            0              25m
kubesphere-monitoring-system   notification-manager-operator-58bc989b46-244dt     2/2     Running            0              25m
kubesphere-monitoring-system   prometheus-k8s-0                                   2/2     Running            0              25m
kubesphere-monitoring-system   prometheus-operator-fc9b55959-h4swr                2/2     Running            0              25m
kubesphere-system              ks-apiserver-5db774f4f-rgltn                       1/1     Running            0              27m
kubesphere-system              ks-console-64b56f967-99twq                         0/1     CrashLoopBackOff   10 (22s ago)   27m
kubesphere-system              ks-controller-manager-7b5f77b47f-nvps8             1/1     Running            0              27m
kubesphere-system              ks-installer-9b4c69688-djxx5                       1/1     Running            0              29m
```

```bash
[root@node1 ~]# kubectl describe po default-http-backend-56d9d4fdf7-sbbmx -n kubesphere-controls-system
Name:         default-http-backend-56d9d4fdf7-sbbmx
Namespace:    kubesphere-controls-system
Priority:     0
Node:         node1/192.168.20.30
Start Time:   Sun, 16 Oct 2022 23:21:45 +0800
Labels:       app=kubesphere
              component=kubesphere-router
              pod-template-hash=56d9d4fdf7
Annotations:  cni.projectcalico.org/containerID: 9ab0a46020abce1aee7ff352a9baec21dca12051de5558c6b09da1dc836a3c8f
              cni.projectcalico.org/podIP: 10.233.90.8/32
              cni.projectcalico.org/podIPs: 10.233.90.8/32
Status:       Running
IP:           10.233.90.8
IPs:
  IP:           10.233.90.8
Controlled By:  ReplicaSet/default-http-backend-56d9d4fdf7
Containers:
  default-http-backend:
    Container ID:   docker://9165eaf9b2135ca59f5f18b445800d9130b067b15f414f0c386bf6870c0f81de
    Image:          registry.cn-beijing.aliyuncs.com/kubesphereio/defaultbackend-amd64:1.4
    Image ID:       docker-pullable://registry.cn-beijing.aliyuncs.com/kubesphereio/defaultbackend-amd64@sha256:05cb942c5ff93ebb6c63d48737cd39d4fa1c6fa9dc7a4d53b2709f5b3c8333e8
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sun, 16 Oct 2022 23:43:38 +0800
      Finished:     Sun, 16 Oct 2022 23:43:38 +0800
    Ready:          False
    Restart Count:  9
    Limits:
      cpu:     10m
      memory:  20Mi
    Requests:
      cpu:        10m
      memory:     20Mi
    Liveness:     http-get http://:8080/healthz delay=30s timeout=5s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-cp7tp (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-cp7tp:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  22m                   default-scheduler  Successfully assigned kubesphere-controls-system/default-http-backend-56d9d4fdf7-sbbmx to node1
  Normal   Pulling    22m                   kubelet            Pulling image "registry.cn-beijing.aliyuncs.com/kubesphereio/defaultbackend-amd64:1.4"
  Normal   Pulled     22m                   kubelet            Successfully pulled image "registry.cn-beijing.aliyuncs.com/kubesphereio/defaultbackend-amd64:1.4" in 7.108640966s
  Normal   Started    21m (x4 over 22m)     kubelet            Started container default-http-backend
  Normal   Pulled     20m (x4 over 22m)     kubelet            Container image "registry.cn-beijing.aliyuncs.com/kubesphereio/defaultbackend-amd64:1.4" already present on machine
  Normal   Created    20m (x5 over 22m)     kubelet            Created container default-http-backend
  Warning  BackOff    2m49s (x95 over 22m)  kubelet            Back-off restarting failed container`
```

导致目前无法在arm64平台上使用KubeKey安装KubeSphere。目前是否有经过测试的arm64平台kubesphere版本？我可以协助进行arm64测试工作。
