### ISSUE TITLE
How to change the IP address of the master machine without resetting the machine and cluster.

### ISSUE THREAD

**Issue by Heyz6** [kubesphere/kubekey#1564]
### What is version of KubeKey has the issue?

2.1.0

### What is your os environment?

centos 7.9

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: "192.168.66.66", internalAddress: "192.168.66.66", port: 22, user: "root", password: "password"}
  roleGroups:
    etcd:
    - node1
    control-plane:
    - node1
    worker:
    - node1
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.12.13
    clusterName: cluster.local
    autoRenewCerts: true
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

How do I make k8s available (single master node) without resetting k8s and reinstalling the OS because the machine IP is changed?
