### ISSUE TITLE
`coredns` pod throw `ImagePullBackOff ` error when offline install kubesphere with k3s

### ISSUE THREAD

**Issue by mangoGoForward** [kubesphere/kubekey#1568]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"latest+unreleased", GitCommit:"455d8c4bdbe41dba9a71ec09526b75bd101e6719", GitTreeState:"dirty", GoVersion:"go1.17.13"}

### What is your os environment?

Centos 7.9

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: centos-174, address: ***, internalAddress: ***, user: ***, password: "***"}
  - {name: centos-176, address: ***, internalAddress: ***, user: ***, password: "***"}
  roleGroups:
    etcd:
    - centos-174
    control-plane:
    - centos-174
    worker:
    - centos-174
    - centos-176
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.21.4-k3s
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    plainHTTP: false
    privateRegistry: "***"
    namespaceOverride: "kubesphere"
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

When successful installed kubesphere on offline environment, but `coredns` deployment can not run because the pod's container can not pull image, and the image is `rancher/coredns-coredns:v1.8.3` which need pull from internet
