### ISSUE TITLE
add kubernetes v1.25.x image to dockerhub

### ISSUE THREAD

**Issue by willzhang** [kubesphere/kubekey#1581]
### Your current KubeKey version

2.3.0

### Describe this feature

kk artifact export
```
22:12:42 CST Destination: oci:/data/kubekey/kubekey/artifact/images:kubesphere:k8s-dns-node-cache:1.21.1-amd64
Getting image source signatures
Copying blob sha256:af833073aa9559031531fca731390d329e083cccc0b824c236e7efc5742ae666
Copying blob sha256:20b09fbd30377e1315a8bc9e15b5f8393a1090a7ec3f714ba5fce0c9b82a42f2
Copying config sha256:87fe60ddfca990f76d112aa3834ea22624fbcceef0116f19dc78b553c49355f8
Writing manifest to image destination
Storing signatures
22:12:55 CST Source: docker://docker.io/kubesphere/kube-apiserver:v1.25.3
22:12:55 CST Destination: oci:/data/kubekey/kubekey/artifact/images:kubesphere:kube-apiserver:v1.25.3-amd64
22:12:58 CST message: [LocalHost]
initializing source docker://kubesphere/kube-apiserver:v1.25.3: reading manifest v1.25.3 in docker.io/kubesphere/kube-apiserver: manifest unknown: manifest unknown
22:12:58 CST failed: [LocalHost]
error: Pipeline[ArtifactExportPipeline] execute failed: Module[CopyImagesToLocalModule] exec failed: 
failed: [LocalHost] [SaveImages] exec failed after 1 retires: initializing source docker://kubesphere/kube-apiserver:v1.25.3: reading manifest v1.25.3 in docker.io/kubesphere/kube-apiserver: manifest unknown: manifest unknown
```

### Describe the solution you'd like

add v1.25 images to dockerhub, or sync everyday with github action.

**Comment by willzhang** [comment]
i can not use this images in `manifests.yaml`
```
  - registry.k8s.io/dns/k8s-dns-node-cache:1.22.13
```
run kk artifact export
```

toring signatures
22:32:40 CST Source: docker://registry.k8s.io/dns/k8s-dns-node-cache:1.22.13
22:32:40 CST Destination: oci:/data/kubekey/kubekey/artifact/images:dns:k8s-dns-node-cache:1.22.13-amd64
Getting image source signatures
Copying blob sha256:6694ef4704cc2d48d77d400e108676f3bd706e9496c7c2b0b9ad86d2c4961422
Copying blob sha256:33905e809db95cdd940d3db7fc8f1486243bf738f5cd712b8f62b105be60dad6
Copying config sha256:1fe3f5a38246787fa48f5212b5c559a3be012f8cbb578130ace9c7251d672e41
Writing manifest to image destination
Storing signatures
panic: runtime error: index out of range [2] with length 2

goroutine 105 [running]:
github.com/kubesphere/kubekey/pkg/images.(*SaveImages).Execute(0xc0003fb050, {0x2711428, 0xc000666a50})
        /home/runner/work/kubekey/kubekey/pkg/images/tasks.go:172 +0x8ee
github.com/kubesphere/kubekey/pkg/core/task.(*LocalTask).ExecuteWithRetry(0xc0006669a0, {0x2711428, 0xc000666a50}, {0x27136c0, 0xc00016b140})
        /home/runner/work/kubekey/kubekey/pkg/core/task/local_task.go:205 +0x126
github.com/kubesphere/kubekey/pkg/core/task.(*LocalTask).Run(0xc0006669a0, {0x2711428, 0xc000666a50}, {0x27136c0?, 0xc00016b140}, 0xc000112ea0?)
        /home/runner/work/kubekey/kubekey/pkg/core/task/local_task.go:159 +0x225
created by github.com/kubesphere/kubekey/pkg/core/task.(*LocalTask).RunWithTimeout
        /home/runner/work/kubekey/kubekey/pkg/core/task/local_task.go:121 +0x172
root@ubuntu:/data/kubekey# ^C
```

**Comment by 24sama** [comment]
Thanks for the feedback, we are still syncing the k8s images...

**Comment by 24sama** [comment]
> i can not use this images in manifests.yaml
> - registry.k8s.io/dns/k8s-dns-node-cache:1.22.13

As for this error, it looks like one of the images behind this `registry.k8s.io/dns/k8s-dns-node-cache:1.22.13` has a formatting problem. `registry.k8s.io/dns/k8s-dns-node-cache:1.22.13` has been stored in the OCI path.

**Comment by 24sama** [comment]
> > but i can pull success.
> 
> ```
> root@ubuntu:~# docker pull registry.k8s.io/dns/k8s-dns-node-cache:1.22.13
> 1.22.13: Pulling from dns/k8s-dns-node-cache
> 33905e809db9: Pull complete 
> 6694ef4704cc: Pull complete 
> Digest: sha256:4746f27a85263d058d397deccbd4a07d5c98acf138bc35f98729c5c6b813a6b6
> Status: Downloaded newer image for registry.k8s.io/dns/k8s-dns-node-cache:1.22.13
> registry.k8s.io/dns/k8s-dns-node-cache:1.22.13
> root@ubuntu:~# 
> ```

I mean there is something wrong with the format of the other image names. Could you please paste your manifest file here?

**Comment by willzhang** [comment]
```
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Manifest
metadata:
  name: sample
spec:
  arches: 
  - amd64
  operatingSystems: 
  - arch: amd64
    type: linux
    id: ubuntu
    version: "22.04"
    osImage: Ubuntu 22.04 LTS
    repository: 
      iso:
        localPath: 
        url: https://github.com/kubesphere/kubekey/releases/download/v2.3.0/ubuntu-22.04-debs-amd64.iso
  kubernetesDistributions: 
  - type: kubernetes
    version: v1.25.3
  components: 
    helm:
      version: v3.6.3
    cni:
      version: v1.1.2
    etcd:
      version: v3.5.4
    containerRuntimes:
    - type: containerd
      version: 1.6.9
    crictl:
      version: v1.25.0
  images:
  - docker.io/calico/cni:v3.24.4
  - docker.io/calico/kube-controllers:v3.24.4
  - docker.io/calico/node:v3.24.4
  - docker.io/calico/pod2daemon-flexvol:v3.24.4
  - docker.io/coredns/coredns:1.9.3
  - registry.k8s.io/dns/k8s-dns-node-cache:1.22.13
  - registry.k8s.io/kube-apiserver:v1.25.3
  - registry.k8s.io/kube-controller-manager:v1.25.3
  - registry.k8s.io/kube-proxy:v1.25.3
  - registry.k8s.io/kube-scheduler:v1.25.3
  - registry.k8s.io/pause:3.8
```

**Comment by willzhang** [comment]
```
kind: Manifest
metadata:
  name: sample
spec:
  arches: 
  - amd64
  operatingSystems: 
  - arch: amd64
    type: linux
    id: ubuntu
    version: "22.04"
    osImage: Ubuntu 22.04 LTS
    repository: 
      iso:
        localPath: 
        url: https://github.com/kubesphere/kubekey/releases/download/v2.3.0/ubuntu-22.04-debs-amd64.iso
  kubernetesDistributions: 
  - type: kubernetes
    version: v1.25.3
  components: 
    helm:
      version: v3.6.3
    cni:
      version: v1.1.2
    etcd:
      version: v3.5.4
    containerRuntimes:
    - type: containerd
      version: 1.6.9
    crictl:
      version: v1.25.0
  images:
  - docker.io/calico/cni:v3.24.4
  - docker.io/calico/kube-controllers:v3.24.4
  - docker.io/calico/node:v3.24.4
  - docker.io/calico/pod2daemon-flexvol:v3.24.4
  - registry.k8s.io/coredns/coredns:v1.9.3
  - registry.k8s.io/dns/k8s-dns-node-cache:1.22.13
  - registry.k8s.io/kube-apiserver:v1.25.3
  - registry.k8s.io/kube-controller-manager:v1.25.3
  - registry.k8s.io/kube-proxy:v1.25.3
  - registry.k8s.io/kube-scheduler:v1.25.3
  - registry.k8s.io/pause:3.8
```

**Comment by 24sama** [comment]
Thanks @willzhang 
Then following images are missing the namespace. Image name must be formated as `registry/namespace/name:tag`.
```
  - registry.k8s.io/kube-apiserver:v1.25.3
  - registry.k8s.io/kube-controller-manager:v1.25.3
  - registry.k8s.io/kube-proxy:v1.25.3
  - registry.k8s.io/kube-scheduler:v1.25.3
  - registry.k8s.io/pause:3.8
```

**Comment by willzhang** [comment]
## some images lost
```
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Manifest
metadata:
  name: sample
spec:
  arches:
  - amd64
  operatingSystems:
  - arch: amd64
    type: linux
    id: ubuntu
    version: "22.04"
    osImage: Ubuntu 22.04 LTS
    repository:
      iso:
        localPath:
        url: https://github.com/kubesphere/kubekey/releases/download/v2.3.0/ubuntu-22.04-debs-amd64.iso
  kubernetesDistributions:
  - type: kubernetes
    version: v1.25.3
  components:
    helm:
      version: v3.6.3
    cni:
      version: v1.1.2
    etcd:
      version: v3.5.4
    containerRuntimes:
    - type: containerd
      version: 1.6.9
    crictl:
      version: v1.25.0
  images:
  - docker.io/calico/cni:v3.24.4
  - docker.io/calico/kube-controllers:v3.24.4
  - docker.io/calico/node:v3.24.4
  - docker.io/calico/pod2daemon-flexvol:v3.24.4
  - registry.k8s.io/coredns/coredns:v1.9.3
  - registry.k8s.io/dns/k8s-dns-node-cache:1.22.13
  - docker.io/kubesphere/kube-apiserver:v1.25.3
  - docker.io/kubesphere/kube-controller-manager:v1.25.3
  - docker.io/kubesphere/kube-proxy:v1.25.3
  - docker.io/kubesphere/kube-scheduler:v1.25.3
  - docker.io/kubesphere/pause:3.8
```
need pause and k8s-dns-node-cache
```
13:53:56 CST Source: docker://docker.io/kubesphere/kube-scheduler:v1.25.3
13:53:56 CST Destination: oci:/data/kubekey/kubekey/artifact/images:kubesphere:kube-scheduler:v1.25.3-amd64
Getting image source signatures
Copying blob sha256:79e0d8860fadaab56c716928c84875d99ff5e13787ca3fcced10b70af29bf320
Copying blob sha256:640696bfc7d7d234958dba52a2ea4694dc28a0f553c84ffd4aab41abaae2c690
Copying blob sha256:78ef12c4eeb634aec1f4d65185c8a5b2e56af3467f1ca90e2b00053853ada41f
Copying config sha256:890912e6edc6cdebc14e720a2189fbb1b64064c876abd6f15e49ceb4577b5a2c
Writing manifest to image destination
Storing signatures
13:54:04 CST Source: docker://docker.io/kubesphere/pause:3.8
13:54:04 CST Destination: oci:/data/kubekey/kubekey/artifact/images:kubesphere:pause:3.8-amd64
13:54:07 CST message: [LocalHost]
initializing source docker://kubesphere/pause:3.8: reading manifest 3.8 in docker.io/kubesphere/pause: manifest unknown: manifest unknown
13:54:07 CST failed: [LocalHost]
error: Pipeline[ArtifactExportPipeline] execute failed: Module[CopyImagesToLocalModule] exec failed: 
failed: [LocalHost] [SaveImages] exec failed after 1 retires: initializing source docker://kubesphere/pause:3.8: reading manifest 3.8 in docker.io/kubesphere/pause: manifest unknown: manifest unknown
```
## suggest
```
root@ubuntu:/data/kubekey# kubeadm config images list
registry.k8s.io/kube-apiserver:v1.25.3
registry.k8s.io/kube-controller-manager:v1.25.3
registry.k8s.io/kube-scheduler:v1.25.3
registry.k8s.io/kube-proxy:v1.25.3
registry.k8s.io/pause:3.8
registry.k8s.io/etcd:3.5.4-0
registry.k8s.io/coredns/coredns:v1.9.3
```

### part1:  kube images

```
wget kubeadm --version 1.25.3
kubeadm config images list | xargs -I {} skopeo sync --src docker --dest docker {} kubesphere/${image##}
```
### part2: k8s-dns-node-cache
```
skopeo sync registry.k8s.io/dns/k8s-dns-node-cache kubesphere/k8s-dns-node-cache
```

### part3: calico images just use docker.io

### suggest use github action workflow sync all version tags 

sync.yaml
```
registry.k8s.io:
    images-by-tag-regex:
        dns/k8s-dns-node-cache: ^v([0-9]+\.){0,2}(\*|[0-9]+)$
        kube-apiserver: ^v([0-9]+\.){0,2}(\*|[0-9]+)$
        kube-controller-manager: ^v([0-9]+\.){0,2}(\*|[0-9]+)$
        kube-scheduler: ^v([0-9]+\.){0,2}(\*|[0-9]+)$
        kube-proxy: ^v([0-9]+\.){0,2}(\*|[0-9]+)$
        pause: ^v([0-9]+\.){0,2}(\*|[0-9]+)$
        etcd: ^v([0-9]+\.){0,2}(\*|[0-9]+)$
        coredns/coredns: ^v([0-9]+\.){0,2}(\*|[0-9]+)$
```


```
name: image-sync
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 14 * * 1'

env:
  USERNAME: ${{ secrets.DOCKER_USERNAME }}
  PASSWORD: ${{ secretsDOCKER_PASSWORD }}

jobs:
  image-sync:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: check podman
      run: |
        sudo podman version
    - name: sync images
      run: |
        sudo podman run -it --rm -v ${PWD}:/workspace -w /workspace quay.io/skopeo/stable:latest \
        sync --src yaml --dest docker sync.yaml registry.cn-shenzhen.aliyuncs.com/cnmirror \
        --dest-username $USERNAME --dest-password $PASSWORD \
        --keep-going --retry-times 2
