### ISSUE TITLE
can kk  add new domain to kubeadm-config 

### ISSUE THREAD

**Issue by zj452008181** [kubesphere/kubekey#1591]
### Your current KubeKey version

2.2.0

### Describe this feature

i want to use a new domain to proxy my apiserver in a existing cluster，can i use kk to update this？

### Describe the solution you'd like

maybe we can use multi domain in kk config like this
`  controlPlaneEndpoint:
    ##Internal loadbalancer for apiservers
    internalLoadbalancer: haproxy
    domain: lb.kubesphere.local, api.jus.int
    address: ""      # The IP address of your load balancer.
    port: 6443
`

**Comment by 24sama** [comment]
kk can't support that. You need to do it manually.

**Comment by redscholar** [comment]
support in kubekey 4.x. https://github.com/kubesphere/kubekey/blob/ccca0edd811c689d8ee9f43e61e2a79b639d9684/builtin/core/roles/install/kubernetes/templates/kubeadm/kubeadm-init.v1beta2#L88-L90
set the value in config.yaml this:
```yaml
apiVersion: kubekey.kubesphere.io/v1
kind: Config
spec:
  kubernetes:
    apiserver:
      certSANs: []
```
