### ISSUE TITLE
How to used flannel CNI

### ISSUE THREAD

**Issue by hawking-lab** [kubesphere/kubekey#161]
![image](https://user-images.githubusercontent.com/47567011/88037646-c717e480-cb77-11ea-8c33-12c67c98a5c3.png)

Use the specified configuration file before installation and modify it to "flannel" network plug-in, but after installation, check that the network plug-in is calico

**Comment by hawking-lab** [comment]
I re-tested it. When using `./kk create config` get generated configuration file does not take effect, and the sample file in docs can be installed as flannel. 

Docs Sample config 
```docs
  network:
    plugin: calico
    podNetworkCidr: 10.233.64.0/18
    serviceNetworkCidr: 10.233.0.0/18
```
 generated configuration
```
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
```
