### ISSUE TITLE
custom script install crio Bash is empty

### ISSUE THREAD

**Issue by willzhang** [kubesphere/kubekey#1614]
### What is version of KubeKey has the issue?

v3.0.1

### What is your os environment?

ubuntu 22.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: 192.168.72.51, internalAddress: 192.168.72.51, user: root, password: "123456"}
  roleGroups:
    etcd:
    - node1
    control-plane: 
    - node1
    worker:
    - node1
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.25.3
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  system:
    preInstall:
      - name: install crio
        bash: /bin/bash -x init-crio.sh
        materials:
          - ./init-crio.sh
          - crio.tar.gz
  registry:
    privateRegistry: "192.168.72.15"
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
    auths:
      "192.168.72.15":
        username: "admin"
        password: "Harbor12345"
        skipTLSVerify: true
        plainHTTP: true
  addons: []
```

### A clear and concise description of what happend.

i want install crio use preInstall 
```
kk create cluster -f config-sample.yaml -a kubekey-artifact.tar.gz --with-packages -y
```

and i put files at current dir
```
root@ubuntu:~/k8s_v1.25.3# ll
total 915028
drwxr-xr-x 1 root root       158 Nov 18 00:34 ./
drwx------ 1 root root       196 Nov 18 00:42 ../
-rw-r--r-- 1 root root      1290 Nov 18 00:34 config-sample.yaml
-rw-r--r-- 1 root root  98724202 Nov 18 00:18 cri-o.tar.gz
-rwxr-xr-x 1 root root       868 Nov 18 00:21 init-crio.sh*
drwxr-xr-x 1 root root       224 Nov 18 00:26 kubekey/
-rw-r--r-- 1 root root 758599552 Nov 17 22:23 kubekey-artifact.tar.gz
```

init-crio.sh
```
root@ubuntu:~/k8s_v1.25.3# cat init-crio.sh 
#!/bin/bash
registry_username=admin
registry_password=Harbor12345
registry_domain=192.168.72.15
registry_port=80
TARBALL=cri-o.tar.gz
TMPDIR="$(mktemp -d)"
trap 'rm -rf -- "$TMPDIR"' EXIT

tar xfz ./cri-o.tar.gz --strip-components=1 -C "$TMPDIR"
pushd "$TMPDIR"
echo Installing CRI-O
./install
popd
# Use other network plugin, eg: calico.
rm -rf /etc/cni/net.d/10-crio-bridge.conf

base64pwd=$(echo -n "${registry_username}:${registry_password}" | base64)
logger "username: $registry_username, password: $registry_password, base64pwd: $base64pwd"
cat > /etc/crio/config.json << eof
{
        "auths": {
                "$registry_domain:$registry_port": {
                        "auth": "$base64pwd"
                }
        }
}
eof

systemctl enable --now crio.service
check_status crio
logger "init crio success"
```

### Relevant log output

```shell
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
vm.swappiness = 1
fs.inotify.max_user_instances = 524288
kernel.pid_max = 65535
00:42:35 CST success: [node1]
00:42:35 CST [ConfigureOSModule] configure the ntp server for each node
00:42:35 CST skipped: [node1]
00:42:35 CST [CustomScriptsModule Phase:PreInstall] Phase:PreInstall(0/1) script:install crio
00:42:35 CST message: [node1]
custom script install crio Bash is empty
00:42:35 CST failed: [node1]
error: Pipeline[CreateClusterPipeline] execute failed: Module[CustomScriptsModule Phase:PreInstall] exec failed: 
failed: [node1] [Phase:PreInstall(0/1) script:install crio] exec failed after 1 retires: custom script install crio Bash is empty
root@ubuntu:~/k8s_v1.25.3#
```

**Comment by 24sama** [comment]
Maybe missing the quotes, Please try this:
```
system:
    preInstall:
      - name: install crio
        bash: "/bin/bash -x init-crio.sh"
        materials:
          - ./init-crio.sh
          - crio.tar.gz
```

**Comment by willzhang** [comment]
i have try , but same result
```
root@node1:~/k8s_v1.25.3# cat config-sample.yaml 

apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: 192.168.72.51, internalAddress: 192.168.72.51, user: root, password: "123456"}
  roleGroups:
    etcd:
    - node1
    control-plane: 
    - node1
    worker:
    - node1
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.25.3
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  system:
    preInstall:
      - name: install crio
        bash: "/bin/bash -x init-crio.sh"
        materials:
          - init-crio.sh
          - cri-o.tar.gz
  registry:
    privateRegistry: "192.168.72.15"
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
    auths:
      "192.168.72.15":
        username: "admin"
        password: "Harbor12345"
        skipTLSVerify: true
        plainHTTP: true
  addons: []
```

**Comment by 24sama** [comment]
Oh, I found it.
https://github.com/kubesphere/kubekey/blob/d0c8a9133683a1b0dca6b8c7fd9a3ca847b297ff/cmd/kk/apis/kubekey/v1alpha2/cluster_types.go#L89-L93

So the field needs to be:
```
system:
    preInstall:
      - name: install crio
        shell: "/bin/bash -x init-crio.sh"               <--- "shell"
        materials:
          - ./init-crio.sh
          - cri-o.tar.gz
```

**Comment by willzhang** [comment]
i must config Absolute path

```
system:
    preInstall:
      - name: install crio
        shell: "/bin/bash -x /tmp/kubekeyPreInstall-0-script/init-crio.sh"               <--- "shell"
        materials:
          - ./init-crio.sh
          - cri-o.tar.gz
```
```
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
vm.swappiness = 1
fs.inotify.max_user_instances = 524288
kernel.pid_max = 65535
10:24:09 CST success: [node1]
10:24:09 CST [ConfigureOSModule] configure the ntp server for each node
10:24:09 CST skipped: [node1]
10:24:09 CST [CustomScriptsModule Phase:PreInstall] Phase:PreInstall(0/1) script:install crio
Copy 0/2 materials: Scp -fr ./init-crio.sh root@192.168.72.51:/tmp/kubekeyPreInstall-0-script/init-crio.sh done, take 364.149126ms
Copy 1/2 materials: Scp -fr cri-o.tar.gz root@192.168.72.51:/tmp/kubekeyPreInstall-0-script/cri-o.tar.gz done, take 2.142264927s
10:24:12 CST message: [node1]
Exec Bash: /bin/bash -x init-crio.sh err:Failed to exec command: sudo -E /bin/bash -c "/bin/bash -x init-crio.sh" 
/bin/bash: init-crio.sh: No such file or directory: Process exited with status 127
10:24:12 CST failed: [node1]
error: Pipeline[CreateClusterPipeline] execute failed: Module[CustomScriptsModule Phase:PreInstall] exec failed: 
failed: [node1] [Phase:PreInstall(0/1) script:install crio] exec failed after 1 retires: Exec Bash: /bin/bash -x init-crio.sh err:Failed to exec command: sudo -E /bin/bash -c "/bin/bash -x init-crio.sh" 
/bin/bash: init-crio.sh: No such file or directory: Process exited with status 127
```

```
root@ubuntu:/tmp/kubekeyPreInstall-0-script# ls
cri-o.tar.gz  init-crio.sh
root@ubuntu:/tmp/kubekeyPreInstall-0-script# sudo -E /bin/bash -c "/bin/bash -x init-crio.sh" 
+ registry_username=admin
+ registry_password=Harbor12345
+ registry_domain=192.168.72.15
+ registry_port=80
+ TARBALL=cri-o.tar.gz
++ mktemp -d
+ TMPDIR=/tmp/tmp.NnhJFAkJdx
+ trap 'rm -rf -- "$TMPDIR"' EXIT
+ tar xfz ./cri-o.tar.gz --strip-components=1 -C /tmp/tmp.NnhJFAkJdx
+ pushd /tmp/tmp.NnhJFAkJdx
/tmp/tmp.NnhJFAkJdx /tmp/kubekeyPreInstall-0-script
+ echo Installing CRI-O
Installing CRI-O
+ ./install
++ install -d -m 755 /etc/cni/net.d
++ install -D -m 755 -t /opt/cni/bin cni-plugins/bandwidth cni-plugins/bridge cni-plugins/dhcp cni-plugins/firewall cni-plugins/host-device cni-plugins/host-local cni-plugins/ipvlan cni-plugins/loopback cni-plugins/macvlan cni-plugins/portmap cni-plugins/ptp cni-plugins/sbr cni-plugins/static cni-plugins/tuning cni-plugins/vlan cni-plugins/vrf
++ install -D -m 644 -t /etc/cni/net.d contrib/10-crio-bridge.conf
++ install -D -m 755 -t /usr/local/bin bin/conmon
++ install -D -m 755 -t /usr/local/bin bin/crictl
++ install -d -m 755 /usr/local/share/bash-completion/completions
++ install -d -m 755 /usr/local/share/fish/completions
++ install -d -m 755 /usr/local/share/zsh/site-functions
++ install -d -m 755 /etc/containers
++ install -D -m 755 -t /usr/local/bin bin/crio-status
++ install -D -m 755 -t /usr/local/bin bin/crio
++ install -D -m 644 -t /etc etc/crictl.yaml
++ install -D -m 644 -t /usr/local/share/oci-umount/oci-umount.d etc/crio-umount.conf
++ install -D -m 644 -t /etc/crio etc/crio.conf
++ install -D -m 644 -t /etc/crio/crio.conf.d etc/10-crun.conf
++ install -D -m 644 -t /usr/local/share/man/man5 man/crio.conf.5
++ install -D -m 644 -t /usr/local/share/man/man5 man/crio.conf.d.5
++ install -D -m 644 -t /usr/local/share/man/man8 man/crio-status.8
++ install -D -m 644 -t /usr/local/share/man/man8 man/crio.8
++ install -D -m 644 -t /usr/local/share/bash-completion/completions completions/bash/crio
++ install -D -m 644 -t /usr/local/share/fish/completions completions/fish/crio.fish
++ install -D -m 644 -t /usr/local/share/zsh/site-functions completions/zsh/_crio
++ install -D -m 644 -t /etc/containers contrib/policy.json
++ install -D -m 644 -t /usr/local/lib/systemd/system contrib/crio.service
++ install -D -m 755 -t /usr/local/bin bin/pinns
++ install -D -m 755 -t /usr/local/bin bin/crun
++ command -v runc
/usr/local/bin/runc
++ '[' -n '' ']'
+ popd
/tmp/kubekeyPreInstall-0-script
+ rm -rf /etc/cni/net.d/10-crio-bridge.conf
++ echo -n admin:Harbor12345
++ base64
+ base64pwd=YWRtaW46SGFyYm9yMTIzNDU=
+ logger 'username: admin, password: Harbor12345, base64pwd: YWRtaW46SGFyYm9yMTIzNDU='
+ cat
+ systemctl enable --now crio.service
+ rm -rf -- /tmp/tmp.NnhJFAkJdx
```
