### ISSUE TITLE
kk artifact export killed

### ISSUE THREAD

**Issue by willzhang** [kubesphere/kubekey#1616]
### What is version of KubeKey has the issue?

v3.0.1

### What is your os environment?

ubuntu 22.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Manifest
metadata:
  name: sample
spec:
  arches:
  - amd64
  operatingSystems:
  - arch: amd64
    type: linux
    id: ubuntu
    version: "22.04"
    osImage: Ubuntu 22.04 LTS
    repository:
      iso:
        localPath: 
        url: https://github.com/kubesphere/kubekey/releases/download/v3.0.1/ubuntu-22.04-debs-amd64.iso
  kubernetesDistributions:
  - type: kubernetes
    version: v1.25.3
  components:
    helm: 
      version: v3.9.0
    cni: 
      version: v0.9.1
    etcd: 
      version: v3.4.13
    containerRuntimes:
    - type: containerd
      version: 1.6.4
    crictl: 
      version: v1.24.0  
    docker-registry:
      version: "2"
    harbor:
      version: v2.5.3
    docker-compose:
      version: v2.2.2
  images:
  - docker.io/calico/cni:v3.23.2
  - docker.io/calico/kube-controllers:v3.23.2
  - docker.io/calico/node:v3.23.2
  - docker.io/calico/pod2daemon-flexvol:v3.23.2
  - docker.io/coredns/coredns:1.9.3
  - docker.io/kubesphere/k8s-dns-node-cache:1.15.12
  - docker.io/kubesphere/kube-apiserver:v1.25.3
  - docker.io/kubesphere/kube-controller-manager:v1.25.3
  - docker.io/kubesphere/kube-proxy:v1.25.3
  - docker.io/kubesphere/kube-scheduler:v1.25.3
  - docker.io/kubesphere/pause:3.8
  - docker.io/kubesphere/etcd:v3.4.13
  - docker.io/plndr/kube-vip:v0.5.0
  - docker.io/library/haproxy:2.3
  - docker.io/kubesphere/multus-cni:v3.8
  registry:
    auths: {}
```

### A clear and concise description of what happend.

root@ubuntu:/data/kubekey/test# kk artifact export -m   manifest-v1.25.3-crio.yaml

 _   __      _          _   __           
| | / /     | |        | | / /           
| |/ / _   _| |__   ___| |/ /  ___ _   _ 
|    \| | | | '_ \ / _ \    \ / _ \ | | |
| |\  \ |_| | |_) |  __/ |\  \  __/ |_| |
\_| \_/\__,_|_.__/ \___\_| \_/\___|\__, |
                                    __/ |
                                   |___/

11:36:53 CST [CheckFileExist] Check output file if existed
11:36:53 CST success: [LocalHost]
11:36:53 CST [CopyImagesToLocalModule] Copy images to a local OCI path from registries
11:36:53 CST Source: docker://docker.io/calico/cni:v3.23.2
11:36:53 CST Destination: oci:/data/kubekey/test/kubekey/artifact/images:calico:cni:v3.23.2-amd64
Getting image source signatures
Copying blob 688f87a081b4 skipped: already exists  
Copying blob 4f4fb700ef54 skipped: already exists  
Copying blob 329d65d470e8 skipped: already exists  
Copying blob 3764c813a2d8 skipped: already exists  
Copying blob 1c1f3a6b8048 skipped: already exists  
Copying blob a33c29efa196 skipped: already exists  
Copying config 27ec2290e3 done  
Writing manifest to image destination
Storing signatures
11:36:57 CST Source: docker://docker.io/calico/kube-controllers:v3.23.2
11:36:57 CST Destination: oci:/data/kubekey/test/kubekey/artifact/images:calico:kube-controllers:v3.23.2-amd64
Getting image source signatures
Copying blob b86b3270aeb9 skipped: already exists  
Copying blob 5c02ef17f43f skipped: already exists  
Copying blob ccf528eae802 skipped: already exists  
Copying blob 3433589275af skipped: already exists  
Copying blob 4c483058dc37 skipped: already exists  
Copying blob 082e383ecef6 skipped: already exists  
Copying blob 494561ed2721 skipped: already exists  
Copying blob 87913b0b2954 skipped: already exists  
Copying config 93205e23ae done  
Writing manifest to image destination
Storing signatures
11:37:01 CST Source: docker://docker.io/calico/node:v3.23.2
11:37:01 CST Destination: oci:/data/kubekey/test/kubekey/artifact/images:calico:node:v3.23.2-amd64
Getting image source signatures
Copying blob 2a9798995149 skipped: already exists  
Copying blob 99bf505ac835 skipped: already exists  
Copying config dbe74530dc done  
Writing manifest to image destination
Storing signatures
11:37:05 CST Source: docker://docker.io/calico/pod2daemon-flexvol:v3.23.2
11:37:05 CST Destination: oci:/data/kubekey/test/kubekey/artifact/images:calico:pod2daemon-flexvol:v3.23.2-amd64
Getting image source signatures
Copying blob ea183c538bf9 skipped: already exists  
Copying blob ebe436753030 skipped: already exists  
Copying blob bfaf5d042af4 skipped: already exists  
Copying blob 1c321ff716d3 skipped: already exists  
Copying blob 7318aec1a79e skipped: already exists  
Copying blob 5e33f7c30bad skipped: already exists  
Copying blob 4d0052e537c9 skipped: already exists  
Copying config 1732e1bd26 done  
Writing manifest to image destination
Storing signatures
11:37:09 CST Source: docker://docker.io/coredns/coredns:1.9.3
11:37:09 CST Destination: oci:/data/kubekey/test/kubekey/artifact/images:coredns:coredns:1.9.3-amd64
Getting image source signatures
Copying blob f2401d57212f skipped: already exists  
Copying blob d92bdee79785 skipped: already exists  
Copying config a2fe663586 done  
Writing manifest to image destination
Storing signatures
11:37:13 CST Source: docker://docker.io/kubesphere/k8s-dns-node-cache:1.15.12
11:37:13 CST Destination: oci:/data/kubekey/test/kubekey/artifact/images:kubesphere:k8s-dns-node-cache:1.15.12-amd64
Getting image source signatures
Copying blob a26fb514c1f6 skipped: already exists  
Copying blob 597de8ba0c30 skipped: already exists  
Copying blob 4fc0092efb17 skipped: already exists  
Copying config bc653b8b2a done  
Writing manifest to image destination
Storing signatures
11:37:16 CST Source: docker://docker.io/kubesphere/kube-apiserver:v1.25.3
11:37:16 CST Destination: oci:/data/kubekey/test/kubekey/artifact/images:kubesphere:kube-apiserver:v1.25.3-amd64
Getting image source signatures
Copying blob b913ed5667fb skipped: already exists  
Copying blob 79e0d8860fad skipped: already exists  
Copying blob 78ef12c4eeb6 skipped: already exists  
Copying config 43c1476986 done  
Writing manifest to image destination
Storing signatures
11:37:21 CST Source: docker://docker.io/kubesphere/kube-controller-manager:v1.25.3
11:37:21 CST Destination: oci:/data/kubekey/test/kubekey/artifact/images:kubesphere:kube-controller-manager:v1.25.3-amd64
Getting image source signatures
Copying blob f04c5f7b8e15 skipped: already exists  
Copying blob 79e0d8860fad skipped: already exists  
Copying blob 78ef12c4eeb6 skipped: already exists  
Copying config f37b1c9be7 done  
Writing manifest to image destination
Storing signatures
11:37:25 CST Source: docker://docker.io/kubesphere/kube-proxy:v1.25.3
11:37:25 CST Destination: oci:/data/kubekey/test/kubekey/artifact/images:kubesphere:kube-proxy:v1.25.3-amd64
Getting image source signatures
Copying blob 8bd04c8f2ed1 skipped: already exists  
Copying blob 01b10be092f3 skipped: already exists  
Copying config b37e7578f1 done  
Writing manifest to image destination
Storing signatures
11:37:29 CST Source: docker://docker.io/kubesphere/kube-scheduler:v1.25.3
11:37:29 CST Destination: oci:/data/kubekey/test/kubekey/artifact/images:kubesphere:kube-scheduler:v1.25.3-amd64
Getting image source signatures
Copying blob 640696bfc7d7 skipped: already exists  
Copying blob 79e0d8860fad skipped: already exists  
Copying blob 78ef12c4eeb6 skipped: already exists  
Copying config 890912e6ed done  
Writing manifest to image destination
Storing signatures
11:37:33 CST Source: docker://docker.io/kubesphere/pause:3.8
11:37:33 CST Destination: oci:/data/kubekey/test/kubekey/artifact/images:kubesphere:pause:3.8-amd64
Getting image source signatures
Copying blob 9457426d6899 skipped: already exists  
Copying config 23de5be0ba done  
Writing manifest to image destination
Storing signatures
11:37:37 CST Source: docker://docker.io/kubesphere/etcd:v3.4.13
11:37:37 CST Destination: oci:/data/kubekey/test/kubekey/artifact/images:kubesphere:etcd:v3.4.13-amd64
Getting image source signatures
Copying blob 5699b9d03e0f skipped: already exists  
Copying blob 44fecd6a0530 skipped: already exists  
Copying blob 39fafc05754f skipped: already exists  
Copying blob 55e324bf8b2b skipped: already exists  
Copying blob fef29bc17c99 skipped: already exists  
Copying blob a03f0963b089 skipped: already exists  
Copying config 8f9e3e2e77 done  
Writing manifest to image destination
Storing signatures
11:37:40 CST Source: docker://docker.io/plndr/kube-vip:v0.5.0
11:37:40 CST Destination: oci:/data/kubekey/test/kubekey/artifact/images:plndr:kube-vip:v0.5.0-amd64
Getting image source signatures
Copying blob 3b78d1d407d3 skipped: already exists  
Copying blob 756d383ebb5f skipped: already exists  
Copying config 6b91c45746 done  
Writing manifest to image destination
Storing signatures
11:37:45 CST Source: docker://docker.io/library/haproxy:2.3
11:37:45 CST Destination: oci:/data/kubekey/test/kubekey/artifact/images:library:haproxy:2.3-amd64
Getting image source signatures
Copying blob 3e40e9210971 skipped: already exists  
Copying blob 55af2836c5dc skipped: already exists  
Copying blob 461246efe0a7 skipped: already exists  
Copying blob 18f7339da51c skipped: already exists  
Copying blob f665b14ac015 skipped: already exists  
Copying config 3aff3ac43a done  
Writing manifest to image destination
Storing signatures
11:37:50 CST Source: docker://docker.io/kubesphere/multus-cni:v3.8
11:37:50 CST Destination: oci:/data/kubekey/test/kubekey/artifact/images:kubesphere:multus-cni:v3.8-amd64
Getting image source signatures
Copying blob 769f11026ee4 skipped: already exists  
Copying blob 2d473b07cdd5 skipped: already exists  
Copying blob edeab1ba6b38 skipped: already exists  
Copying config 73852300c6 done  
Writing manifest to image destination
Storing signatures
11:37:54 CST success: [LocalHost]
11:37:54 CST [ArtifactBinariesModule] Download manifest expect binaries
11:37:54 CST message: [localhost]
downloading amd64 kubeadm v1.25.3 ...
11:37:54 CST message: [localhost]
downloading amd64 kubelet v1.25.3 ...
11:37:55 CST message: [localhost]
downloading amd64 kubectl v1.25.3 ...
11:37:55 CST message: [localhost]
downloading amd64 helm v3.9.0 ...
11:37:55 CST message: [localhost]
downloading amd64 kubecni v0.9.1 ...
11:37:55 CST message: [localhost]
downloading amd64 etcd v3.4.13 ...
11:37:55 CST message: [localhost]
downloading amd64 containerd 1.6.4 ...
11:37:56 CST message: [localhost]
downloading amd64 runc v1.1.1 ...
11:37:56 CST message: [localhost]
downloading amd64 crictl v1.24.0 ...
11:37:56 CST message: [localhost]
downloading amd64 registry 2 ...
11:37:56 CST message: [localhost]
downloading amd64 harbor v2.5.3 ...
Killed
root@ubuntu:/data/kubekey/test# 

### Relevant log output

```shell
oot@ubuntu:/data/kubekey/test# ls kubekey/
artifact/ logs/     
root@ubuntu:/data/kubekey/test# du -sh kubekey/
1.6G    kubekey/
root@ubuntu:/data/kubekey/test# ls kubekey/
artifact/ logs/     
root@ubuntu:/data/kubekey/test# ls kubekey/artifact/
cni/        containerd/ crictl/     etcd/       helm/       images/     kube/       registry/   runc/       
root@ubuntu:/data/kubekey/test# ls kubekey/artifact/r
registry/ runc/     
root@ubuntu:/data/kubekey/test# ls kubekey/artifact/registry/harbor/v2.5.3/amd64/
harbor-offline-installer-v2.5.3.tgz
root@ubuntu:/data/kubekey/test#
```

**Comment by willzhang** [comment]
Cancelling the Harbor can be packed normally

```
    docker-compose:
      version: v2.2.2
    docker-registry:
      version: "2"
    #harbor:
    #  version: v2.5.3
```
