### ISSUE TITLE
kk推送镜像到harbor仓库故障

### ISSUE THREAD

**Issue by jinwendaiya** [kubesphere/kubekey#1635]
### What is version of KubeKey has the issue?

kubekeyV3.0.2

### What is your os environment?

centos7.6

### KubeKey config file

```yaml
domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.21.14
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: docker
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    type: harbor
    auths:
      "dockerhub.kubekey.local":
        username: admin
        password: Harbor12345
        skipTLSVerify: true
        certsPath: "/etc/docker/cert.d/dockerhub.kubekey.local/"
    privateRegistry: "dockerhub.kubekey.local"
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

在使用kubekey做离线部署的时候，使用kubekey init harbor ，但是harbor主页面无法访问，harbor-nginx一直在803重定向，
使用curl请求harbor地址状况如下：
![harbor-ningx故障](https://user-images.githubusercontent.com/30795466/204078708-251381aa-4573-4ed3-8906-b914fbbe396c.png)
最重要的问题是 在使用./kk artifact image push -f config-sample.yaml -a kubekey-artifact.tar.gz 时出现如下故障：
![push推送问题](https://user-images.githubusercontent.com/30795466/204078904-90c1cc61-64ea-4c20-92e9-6afdcfdda9ce.png)
在registry的节点上，容器状态都为up正常
![harbor容器状态](https://user-images.githubusercontent.com/30795466/204078749-e6398ff3-88ec-4023-8f3a-4e154389179f.png)

### Relevant log output

```shell
15:02:00 CST message: [LocalHost]py image 0c1:/opt/ks/kubekey/images:kubesphereio:kube-apiserver:vl.21.14-ad64 to docker://dckertub.kubekey. local/kubesphere10/kube-apiserver:vl1.14-amd64 failed: trying to reuse bloh sha256:ab2f6dae3h543fb156bbc4ce6368b84fd76fcb0Befb54fh9345240e9f4e34 at destination: checking mhetherblob sha256:ab2f6dae3b543cfb15c6bbc4ce6368bb84fd76fcb08eocal/kubesphereio/kube-apiserver: unautorized: authentication required5:02:00 csT failed :[LocaHost!rror: Pipeline[ArtifactImagesPushPipeline] execute failed:ModulelCopyImagesToRegistryMfailedailed;[LocalHost][CopyImagesToRegistrylfailed afterl retiresimage oci:/opt/ks/kubekey/images:kubesphereio:kubeapiserver:w] 2114execCODYtrying to reuse blob sha256:ab2f6dae3b543cfb15c6bbc4cemd64 to docker://dockerhub .kubekey.local/kubesphereio/kube-
apiserver:v1.21.faijed368bb84fd76fcb08efb54fb9345240e9f4e34 at destination: checking whethesha256:ab2f6dae3b543cfb15c6bbc4ce6368bb84fd76fcb08efb54fb9345240e9f4300034 exists in dockerhub.kubekey.local/kubesphereio/kube-apiserver11031170011Zeautherticat10rreouirec
```

### Additional information

在命令行登录harbor仓库地址可以成功
![从域名登录harbor正常 ](https://user-images.githubusercontent.com/30795466/204079062-14754c8c-dbd3-4aa6-adc3-e2e319a7a5f5.png)
以下为harbor-nginx的容器日志
![harbor-nginx日志](https://user-images.githubusercontent.com/30795466/204079121-bcab7ac8-6bc7-48bc-b9a8-56567fe8336c.png)
