### ISSUE TITLE
CIDRNotAvailable 34 Works and 2 CP+ETCD

### ISSUE THREAD

**Issue by antikilahdjs** [kubesphere/kubekey#1647]
### What is version of KubeKey has the issue?

3.0.2

### What is your os environment?

Ubuntu 20.04 / RedHat 8

### KubeKey config file

```yaml
controlPlaneEndpoint:
    internalLoadbalancer: haproxy      
    domain: lb.er.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.22.10
    imageRepo: kubesphere
    containerManager: docker
    clusterName: "mycluster-er.local"
    #dnsDomain: "mycluster-er.local"
    nodelocaldns: true
    masqueradeAll: false
    maxPods: 220
    nodeCidrMaskSize: 21
    proxyMode: ipvs
    featureGates:
      CSIStorageCapacity: true
      ExpandCSIVolumes: true
      RotateKubeletServerCertificate: true
      TTLAfterFinished: true
  network:
    plugin: calico
    calico:
      ipipMode: Never
      vxlanMode: Never
      vethMTU: 9000
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    multusCNI:
      enabled: true
```

### A clear and concise description of what happend.

I just installed using the KK and I have 36 Nodes 2 of them is a Control Plane and the other ones is Worker. I am using Calico with /18 and all the time I got the information the CIDR is not Available. My Internal CIIRD is /23 . I was wondering to know if I made something wrong using the KK installation.

### Relevant log output

```shell
3m2s        Normal    CIDRNotAvailable          node/er08                                                                     Node s08 status is now: CIDRNotAvailable
4m2s        Normal    CIDRNotAvailable          node/er09                                                                       Node s09 status is now: CIDRNotAvailable
4m18s       Normal    CIDRNotAvailable          node/er10
```

### Additional information

![image](https://user-images.githubusercontent.com/33559260/206170356-6c702ef1-3230-45c5-84b2-b3c2969d462d.png)
