### ISSUE TITLE
kk delete cluster will stop harbor container

### ISSUE THREAD

**Issue by willzhang** [kubesphere/kubekey#1654]
### What is version of KubeKey has the issue?

v3.0.2

### What is your os environment?

ubuntu 22.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: ubuntu, address: 192.168.11.20, internalAddress: 192.168.11.20, user: root, password: "xxx"}
  roleGroups:
    etcd:
    - ubuntu
    control-plane:
    - ubuntu
    worker:
    - ubuntu
  controlPlaneEndpoint:
    domain: 192.168.11.20
    address: ""
    port: 6443
  kubernetes:
    version: v1.25.3
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: crio
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    multusCNI:
      enabled: true
  system:
    preInstall:
      - name: install crio
        bash: "pushd /tmp/kubekeyPreInstall-0-script/crio/crio/scripts/ && /bin/bash -x init-crio.sh"
        materials:
          - ./artifact_v1.25.3/crio
  registry:
    privateRegistry: "192.168.11.20"
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
    auths:
      "192.168.11.20":
        username: "admin"
        password: "Harbor12345"
        skipTLSVerify: false
        plainHTTP: false
        certsPath: "./artifact_v1.25.3/crio/certs.d/192.168.11.20"
  addons: []
```

### A clear and concise description of what happend.

1、install docker in node20

2、install harbor in node20 manaul , not use kk

3、create cluster with kk in node20

4、reset cluster in node20
```
kk delete cluster -f cluster-config-20.yaml
```
5、some harbor docker container will be stoped by kk

```
root@ubuntu:/data/kubernetes# docker ps |grep harbor
50c4aa4c995d   goharbor/nginx-photon:v2.6.2        "nginx -g 'daemon of…"   21 hours ago   Restarting (1) 32 seconds ago                                                 nginx
bd593cb29446   goharbor/harbor-jobservice:v2.6.2   "/harbor/entrypoint.…"   21 hours ago   Restarting (2) 32 seconds ago                                                 harbor-jobservice
04a7ecd706bf   goharbor/harbor-core:v2.6.2         "/harbor/entrypoint.…"   21 hours ago   Up 3 seconds (health: starting)                                               harbor-core
d777b8e956a4   goharbor/registry-photon:v2.6.2     "/home/harbor/entryp…"   21 hours ago   Up 5 minutes (healthy)                                                        registry
5156eeb02cab   goharbor/harbor-db:v2.6.2           "/docker-entrypoint.…"   21 hours ago   Up 5 minutes (healthy)                                                        harbor-db
e65853e1968e   goharbor/harbor-log:v2.6.2          "/bin/sh -c /usr/loc…"   21 hours ago   Up 5 minutes (healthy)            127.0.0.1:1514->10514/tcp                   harbor-log
root@ubuntu:/data/kubernetes# 
```
