### ISSUE TITLE
CreateClusterPipeline failed

### ISSUE THREAD

**Issue by willzhang** [kubesphere/kubekey#1657]
### What is version of KubeKey has the issue?

v3.0.2

### What is your os environment?

ubuntu 22.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: ubuntu, address: 172.17.10.200, internalAddress: 172.17.10.200, user: root, password: "xxx"}
  roleGroups:
    etcd:
    - ubuntu
    control-plane:
    - ubuntu
    worker:
    - ubuntu
  controlPlaneEndpoint:
    domain: 172.17.10.200
    address: ""
    port: 6443
  kubernetes:
    version: v1.25.3
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: crio
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    multusCNI:
      enabled: true
  system:
    preInstall:
      - name: install crio
        bash: "pushd /tmp/kubekeyPreInstall-0-script/crio/crio/scripts/ && /bin/bash -x init-crio.sh"
        materials:
          - ./artifact_v1.25.3/crio
  registry:
    privateRegistry: "172.17.10.10"
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
    auths:
      "172.17.10.10":
        username: "admin"
        password: "Harbor12345"
        skipTLSVerify: false
        plainHTTP: false
        certsPath: "./artifact_v1.25.3/crio/certs.d/172.17.10.10"
  addons: []
```

### A clear and concise description of what happend.
```
root@ubuntu:/data/kubernetes# kk create cluster -f ./cluster-config-200.yaml ./artifact_v1.25.3/kubekey/artifact-v1.25.3.tar.gz --with-packages -y --debug


 _   __      _          _   __           
| | / /     | |        | | / /           
| |/ / _   _| |__   ___| |/ /  ___ _   _ 
|    \| | | | '_ \ / _ \    \ / _ \ | | |
| |\  \ |_| | |_) |  __/ |\  \  __/ |_| |
\_| \_/\__,_|_.__/ \___\_| \_/\___|\__, |
                                    __/ |
                                   |___/

17:50:59 CST [GreetingsModule] Greetings
17:51:29 CST failed: [node200]
error: Pipeline[CreateClusterPipeline] execute failed: Module[GreetingsModule] exec failed: 
failed: [node200] execute task timeout, Timeout=30s
root@ubuntu:/data/kubernetes# ^C
root@ubuntu:/data/kubernetes# 
```

### Relevant log output

i can not get detail logs

### Additional information

I have a network card with a special vlan configuration. The primary network card has no IP address，So I'm not sure if this is the reason for the failure.

two vlan link to ens16f3.

```
root@node200:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens1f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 40:a6:b7:97:56:4c brd ff:ff:ff:ff:ff:ff
    altname enp24s0f0
    inet6 fe80::42a6:b7ff:fe97:564c/64 scope link 
       valid_lft forever preferred_lft forever
3: ens16f0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether c4:c0:63:c0:1a:08 brd ff:ff:ff:ff:ff:ff
    altname enp49s0f0
4: ens1f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 40:a6:b7:97:56:4d brd ff:ff:ff:ff:ff:ff
    altname enp24s0f1
    inet6 fe80::42a6:b7ff:fe97:564d/64 scope link 
       valid_lft forever preferred_lft forever
5: ens16f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether c4:c0:63:c0:1a:09 brd ff:ff:ff:ff:ff:ff
    altname enp49s0f1
6: ens2f0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 40:a6:b7:97:63:d0 brd ff:ff:ff:ff:ff:ff
    altname enp75s0f0
7: ens16f2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether c4:c0:63:c0:1a:0a brd ff:ff:ff:ff:ff:ff
    altname enp49s0f2
8: ens2f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 40:a6:b7:97:63:d1 brd ff:ff:ff:ff:ff:ff
    altname enp75s0f1
9: ens16f3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether c4:c0:63:c0:1a:0b brd ff:ff:ff:ff:ff:ff
    altname enp49s0f3
    inet6 fe80::c6c0:63ff:fec0:1a0b/64 scope link 
       valid_lft forever preferred_lft forever
10: vlan2002@ens16f3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether c4:c0:63:c0:1a:0b brd ff:ff:ff:ff:ff:ff
    inet 172.17.10.200/27 brd 172.17.10.223 scope global vlan2002
       valid_lft forever preferred_lft forever
    inet6 fe80::c6c0:63ff:fec0:1a0b/64 scope link 
       valid_lft forever preferred_lft forever
11: vlan2351@ens16f3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether c4:c0:63:c0:1a:0b brd ff:ff:ff:ff:ff:ff
    inet 173.1.4.200/24 brd 173.1.4.255 scope global vlan2351
       valid_lft forever preferred_lft forever
    inet6 fe80::c6c0:63ff:fec0:1a0b/64 scope link 
       valid_lft forever preferred_lft forever
```
