### ISSUE TITLE
Why do you add kubectl and kube config on all worker nodes?

### ISSUE THREAD

**Issue by Nello-Angelo** [kubesphere/kubekey#1663]
### What is version of KubeKey has the issue?

2.2.2

### What is your os environment?

debian 11.5

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: debian-master, address: 192.168.101.154, internalAddress: 192.168.101.154, user: root, password: "123", timeout: 60}
  - {name: debian-worker-1, address: 192.168.101.155, internalAddress: 192.168.101.155, user: angelo, password: "123", timeout: 60}
  - {name: debian-worker-2, address: 192.168.101.156, internalAddress: 192.168.101.156, user: angelo, password: "123", timeout: 60}
  - {name: debian-worker-3, address: 192.168.101.157, internalAddress: 192.168.101.157, user: angelo, password: "123", timeout: 60}
  roleGroups:
    etcd:
    - debian-master
    control-plane:
    - debian-master
    worker:
    - debian-worker-1
    - debian-worker-2
    - debian-worker-3
  controlPlaneEndpoint:
    internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.24.1
    clusterName: cluster.local
    masqueradeAll: false
    maxPods: 110
    nodeCidrMaskSize: 24
    proxyMode: ipvs
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubeadm
  network:
    plugin: calico
    calico:
      ipipMode: Never
      vxlanMode: Never
      vethMTU: 1440
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

Why do you add kubectl and kube config on all worker nodes? 
When kubekey do installation it adds kubectl and kube config on all worker nodes. I understand why it needs on masters but why it needs on workers i don`t understand i think it is like security bug of installation
