### ISSUE TITLE
kk create cluster Blocking at `[RepositoryModule] Install packages`

### ISSUE THREAD

**Issue by willzhang** [kubesphere/kubekey#1686]
### What is version of KubeKey has the issue?

v3.0.6

### What is your os environment?

Ubuntu 22.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node32, address: 192.168.72.32, internalAddress: 192.168.72.32, user: root, password: "123456"}
  roleGroups:
    etcd:
    - node32
    control-plane:
    - node32
    worker:
    - node32
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.25.3
    imageRepo: kubesphere
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: crio
  etcd:
    type: kubekey
  network:
    plugin: calico
    calico:
      ipipMode: Never
      vxlanMode: Always
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    multusCNI:
      enabled: true
  registry:
    privateRegistry: "repository.cucc.cn:13380"
    namespaceOverride: "kubesphere"
    registryMirrors: []
    insecureRegistries: []
    auths:
      "repository.cucc.cn:13380":
        username: "admin"
        password: "Harbor12345"
        skipTLSVerify: false
        plainHTTP: false
        certsPath: ""
  addons:
```

### A clear and concise description of what happend.

kk create cluster always in this step 
```
17:19:08 CST [RepositoryModule] Add local repository
17:19:08 CST stdout: [node195]
Get:1 file:/tmp/kubekey/iso  InRelease
Ign:1 file:/tmp/kubekey/iso  InRelease
Get:2 file:/tmp/kubekey/iso  Release
Ign:2 file:/tmp/kubekey/iso  Release
Get:3 file:/tmp/kubekey/iso  Packages
Ign:3 file:/tmp/kubekey/iso  Packages
Get:4 file:/tmp/kubekey/iso  Translation-en_US
Ign:4 file:/tmp/kubekey/iso  Translation-en_US
Get:5 file:/tmp/kubekey/iso  Translation-en
Ign:5 file:/tmp/kubekey/iso  Translation-en
Get:3 file:/tmp/kubekey/iso  Packages
Ign:3 file:/tmp/kubekey/iso  Packages
Get:4 file:/tmp/kubekey/iso  Translation-en_US
Ign:4 file:/tmp/kubekey/iso  Translation-en_US
Get:5 file:/tmp/kubekey/iso  Translation-en
Ign:5 file:/tmp/kubekey/iso  Translation-en
Get:3 file:/tmp/kubekey/iso  Packages
Ign:3 file:/tmp/kubekey/iso  Packages
Get:4 file:/tmp/kubekey/iso  Translation-en_US
Ign:4 file:/tmp/kubekey/iso  Translation-en_US
Get:5 file:/tmp/kubekey/iso  Translation-en
Ign:5 file:/tmp/kubekey/iso  Translation-en
Get:3 file:/tmp/kubekey/iso  Packages [53.8 kB]
Get:4 file:/tmp/kubekey/iso  Translation-en_US
Ign:4 file:/tmp/kubekey/iso  Translation-en_US
Get:5 file:/tmp/kubekey/iso  Translation-en
Ign:5 file:/tmp/kubekey/iso  Translation-en
Get:4 file:/tmp/kubekey/iso  Translation-en_US
Ign:4 file:/tmp/kubekey/iso  Translation-en_US
Get:5 file:/tmp/kubekey/iso  Translation-en
Ign:5 file:/tmp/kubekey/iso  Translation-en      
Get:4 file:/tmp/kubekey/iso  Translation-en_US   
Ign:4 file:/tmp/kubekey/iso  Translation-en_US   
Get:5 file:/tmp/kubekey/iso  Translation-en      
Ign:5 file:/tmp/kubekey/iso  Translation-en      
Get:4 file:/tmp/kubekey/iso  Translation-en_US   
Ign:4 file:/tmp/kubekey/iso  Translation-en_US   
Get:5 file:/tmp/kubekey/iso  Translation-en      
Ign:5 file:/tmp/kubekey/iso  Translation-en      
Reading package lists... Done                    
17:19:08 CST success: [node195]
17:19:08 CST [RepositoryModule] Install packages

```
