### ISSUE TITLE
GetNodeInterface remote task output redundant interface names leads to failure of kubevip pod

### ISSUE THREAD

**Issue by lwabish** [kubesphere/kubekey#1690]
### What is version of KubeKey has the issue?

release 3.0.6 & git commit ec903fe13dfed73ffd3f72f4beec3123675ce4d0

### What is your os environment?

Ubuntu 22.04.1 LTS

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: lab
spec:
  hosts:
    - {
        name: master1,
        address: 10.0.0.161,
        internalAddress: 10.0.0.161,
        user: root,
        privateKeyPath: "~/.ssh/id_ed25519",
      }
    - {
        name: master2,
        address: 10.0.0.149,
        internalAddress: 10.0.0.149,
        user: root,
        privateKeyPath: "~/.ssh/id_ed25519",
      }
    - {
        name: master3,
        address: 10.0.0.216,
        internalAddress: 10.0.0.216,
        user: root,
        privateKeyPath: "~/.ssh/id_ed25519",
      }
  roleGroups:
    etcd:
      - master1
      - master2
      - master3
    control-plane:
      - master1
      - master2
      - master3
    worker:
      - master1
      - master2
      - master3
  controlPlaneEndpoint:
    internalLoadbalancer: kube-vip
    domain: lb.kubesphere.local
    address: "10.0.0.200"
    port: 6443
  kubernetes:
    type: kubernetes
    version: v1.21.14
    imageRepo: kubesphere
    containerManager: docker
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: "10.233.64.0/18"
    kubeServiceCIDR: "10.233.0.0/18"
```

### A clear and concise description of what happend.

kubevip pod rendered as follow:
```
    - name: vip_interface
      value: ens160
ens160
ens160
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
```

### Additional information

Did some code debug: problematic code should be here
https://github.com/kubesphere/kubekey/blob/ec903fe13dfed73ffd3f72f4beec3123675ce4d0/cmd/kk/pkg/loadbalancer/tasks.go#L166-L169

On my node,  `ip route | grep 10.0.0.216` result is like this , three lines appeared, which leads to the final redundant interface names.
```
root@ubuntu:~# ip route | grep 10.0.0.216
default via 10.0.0.1 dev ens160 proto dhcp src 10.0.0.216 metric 100
10.0.0.0/24 dev ens160 proto kernel scope link src 10.0.0.216 metric 100
10.0.0.1 dev ens160 proto dhcp scope link src 10.0.0.216 metric 100
```
