### ISSUE TITLE
openebs not installed

### ISSUE THREAD

**Issue by willzhang** [kubesphere/kubekey#1694]
### What is version of KubeKey has the issue?

v3.0.5

### What is your os environment?

ubuntu 22.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node35, address: 192.168.72.35, internalAddress: 192.168.72.35, user: root, password: "123456"}
  roleGroups:
    etcd:
    - node35
    control-plane:
    - node35
    worker:
    - node35
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.25.3
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: true
  storage:
    openebs:
      basePath: /var/openebs/local
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

config-sample.yaml  have the follow content ,but openebs not installed
```
  storage:
    openebs:
      basePath: /var/openebs/local
```

### Additional information

pods
```
root@node35:~# kubectl get pods -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-75c594996d-7h6xh   1/1     Running   0          7m28s
kube-system   calico-node-wv4kd                          1/1     Running   0          7m28s
kube-system   coredns-67ddbf998c-q5q9r                   1/1     Running   0          7m28s
kube-system   coredns-67ddbf998c-wcnxz                   1/1     Running   0          7m28s
kube-system   kube-apiserver-node35                      1/1     Running   0          7m41s
kube-system   kube-controller-manager-node35             1/1     Running   0          7m41s
kube-system   kube-multus-ds-27hgd                       1/1     Running   0          7m28s
kube-system   kube-proxy-6vzqb                           1/1     Running   0          7m28s
kube-system   kube-scheduler-node35                      1/1     Running   0          7m42s
kube-system   nodelocaldns-cdwfv                         1/1     Running   0          7m28s
root@node35:~# 
```

similar issue: https://github.com/kubesphere/kubekey/issues/159

**Comment by 24sama** [comment]
There are 2 cases in which kk will install openebs:
* install k8s and ks both
* install k8s only and the command with the flag `--with-local-storage`
    ```
    ./kk create cluster -f config.yaml --with-local-storage
    ```

**Comment by 24sama** [comment]
I think this issue can be closed, feel free to reopen it.

/close

**Comment by willzhang** [comment]
1、should add notes for this point to [config-example.md](https://github.com/kubesphere/kubekey/blob/master/docs/config-example.md)
2、add `enabled: true` will alse a good way, thanks anyway
```
  storage:
    openebs:
       enabled: true
      basePath: /var/openebs/local
```
