### ISSUE TITLE
kube-vip loadbalancer not working because kube-proxy cleans ipvs rules

### ISSUE THREAD

**Issue by lwabish** [kubesphere/kubekey#1702]
### What is version of KubeKey has the issue?

3.0.6

### What is your os environment?

Ubuntu 22.04.1 LTS

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: lab
spec:
  hosts:
    - {
        name: master1,
        address: 10.0.0.161,
        internalAddress: 10.0.0.161,
        user: root,
        privateKeyPath: "~/.ssh/id_ed25519",
      }
    - {
        name: master2,
        address: 10.0.0.149,
        internalAddress: 10.0.0.149,
        user: root,
        privateKeyPath: "~/.ssh/id_ed25519",
      }
    - {
        name: master3,
        address: 10.0.0.216,
        internalAddress: 10.0.0.216,
        user: root,
        privateKeyPath: "~/.ssh/id_ed25519",
      }
  roleGroups:
    etcd:
      - master1
      - master2
      - master3
    control-plane:
      - master1
      - master2
      - master3
    worker:
      - master1
      - master2
      - master3
  controlPlaneEndpoint:
    internalLoadbalancer: kube-vip
    domain: lb.kubesphere.local
    address: "10.0.0.200"
    port: 6443
  kubernetes:
    type: kubernetes
    version: v1.21.14
    imageRepo: kubesphere
    containerManager: docker
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: "10.233.64.0/18"
    kubeServiceCIDR: "10.233.0.0/18"
```

### A clear and concise description of what happend.

After the cluster is deployed successfully, inspect ipvs rules with `ipvsadm -Ln` on the vip master node.
Only kube-proxy ipvs rules were found.
kube-vip is always trying to add ipvs rule, but at the same time kube-proxy is always cleaning all rules.

### Relevant log output

```shell
kube-vip pod log:
time="2023-01-12T02:54:15Z" level=error msg="Error querying backends file does not exist"
time="2023-01-12T02:54:15Z" level=info msg="Created Load-Balancer services on [10.0.0.200:6443]"
time="2023-01-12T02:54:15Z" level=info msg="Added backend for [10.0.0.200:6443] on [10.0.0.216:6443]"
time="2023-01-12T02:55:15Z" level=error msg="Error querying backends file does not exist"
time="2023-01-12T02:55:15Z" level=info msg="Created Load-Balancer services on [10.0.0.200:6443]"
time="2023-01-12T02:55:15Z" level=info msg="Added backend for [10.0.0.200:6443] on [10.0.0.149:6443]"
time="2023-01-12T02:56:37Z" level=error msg="Error querying backends file does not exist"
time="2023-01-12T02:56:37Z" level=info msg="Created Load-Balancer services on [10.0.0.200:6443]"
time="2023-01-12T02:56:37Z" level=info msg="Added backend for [10.0.0.200:6443] on [10.0.0.161:6443]"
time="2023-01-12T02:59:16Z" level=error msg="Error querying backends file does not exist"
time="2023-01-12T02:59:16Z" level=info msg="Created Load-Balancer services on [10.0.0.200:6443]"
```

### Additional information

After adding node ip cidr to kube-proxy config , this bug could be fixed.
```yaml
ipvs:
  excludeCIDRs:
    - 10.0.0.0/24
```
As to kubekey, should we optimize the logic of kube-proxy configuration in GenerateKubeadmConfig Action?
I'd love to implement it if the solution looks good.

**Comment by 24sama** [comment]
Good catch! Normally, our node address is `19.168.x.x` or `172.x.x.x` and the Kubernetes network CIDR is `10.233.64.0/18`, so we didn't find this bug.

As the following code:
https://github.com/kubesphere/kubekey/blob/e2ecb9f12be1858b3575d1e6b3347bcb780c3919/cmd/kk/apis/kubekey/v1alpha2/kubernetes_types.go#L45

I think we can customize our config like this to solve this problem:
```
kubernetes:
    type: kubernetes
    version: v1.21.14
    imageRepo: kubesphere
    containerManager: docker
    clusterName: cluster.local
    kubeProxyArgs: ["--ipvs-exclude-cidrs=10.0.0.0/24"]
```

More info about kube-proxy, please see:https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/#options

**Comment by lwabish** [comment]
I searched the code usage of KubeProxyArgs. It's only been used in k3s and k8e pipelines. 
As to k8s pipeline, it uses KubeProxyConfiguration to accept users' custom configuration.
And Shall we add some doc to config example to remind users about this?

**Comment by 24sama** [comment]
> t's only been used in k3s and k8e pipelines.
As to k8s pipeline, it uses KubeProxyConfiguration to accept users' custom configuration.

Oh, sorry, I forgot and you are right. I think we can add more examples to this [doc](https://github.com/kubesphere/kubekey/blob/master/docs/config-example.md), are you interested in it?

**Comment by lwabish** [comment]
Also Is is possible that we add some logic to automatically add this into KubeProxyConfiguration?
Maybe something like this, but the cidr value seems necessary for users to manually input
```
	if kubeConf.Cluster.ControlPlaneEndpoint.IsInternalLBEnabledVip() && kubeConf.Cluster.Kubernetes.ProxyMode == v1alpha2.DefaultProxyMode {
		defaultKubeProxyConfiguration["ipvs"] = map[string]interface{}{"excludeCIDRs": kubeConf.Cluster.Hosts}
	}
```
Which is better to you?

**Comment by 24sama** [comment]
Using `KubeProxyConfiguration` is also easy, if I am not mistaken it should be like this:
```
kubernetes:
  type: kubernetes
  version: v1.21.14
  kubeProxyConfiguration:
    ipvs: 
      excludeCIDRs: 
        - 10.0.0.0/24
```
