### ISSUE TITLE
Two warnings that I cannot find the cause for ... 

### ISSUE THREAD

**Issue by aram535** [kubesphere/kubekey#1720]
### What is version of KubeKey has the issue?

kk version: &version.Info{Major:"3", Minor:"0", GitVersion:"v3.0.7", GitCommit:"e755baf67198d565689d7207378174f429b508ba", GitTreeState:"clean", BuildDate:"2023-01-18T01:57:24Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### What is your os environment?

Ubuntu 22.04.01 LTS

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts: 
  ##You should complete the ssh information of the hosts
  - {name: master, address: 192.168.1.110, internalAddress: 192.168.1.110}
  - {name: node1, address: 192.168.1.111, internalAddress: 192.168.1.111}
  - {name: node2, address: 192.168.1.112, internalAddress: 192.168.1.112}
  - {name: node3, address: 192.168.1.113, internalAddress: 192.168.1.113}
  - {name: node4, address: 192.168.1.114, internalAddress: 192.168.1.114}
  roleGroups:
    etcd:
    - master
    master:
    - master
    worker:
    - node1
    - node2
    - node3
    - node4
  controlPlaneEndpoint:
    ##Internal loadbalancer for apiservers
    internalLoadbalancer: haproxy

    ##If the external loadbalancer was used, 'address' should be set to loadbalancer's ip.
    domain: lb.basement.lab
    address: ""
    port: 6443
  kubernetes:
    version: v1.22.16
    clusterName: cluster.local
    proxyMode: ipvs
    masqueradeAll: false
    maxPods: 110
    nodeCidrMaskSize: 24
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    privateRegistry: ""
```

### A clear and concise description of what happend.

While adding a new node the following warnings appears in the console but I cannot find any documentation or source where these values are coming from and how to fix either of them. 

[preflight] Running pre-flight checks
        [WARNING SystemVerification]: missing optional cgroups: hugetlb
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
W0203 06:38:41.455742    3118 utils.go:69] The recommended value for "clusterDNS" in "KubeletConfiguration" is: [10.233.0.10]; the provided value is: [169.254.25.10]
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"

### Relevant log output

```shell
$ kubectl -n kube-system get cm kubeadm-config -o yaml | grep -i dns -A3
    dns:
      imageRepository: coredns
      imageTag: 1.8.0
    etcd:
      external:
--
      dnsDomain: cluster.local
      podSubnet: 10.233.64.0/18
      serviceSubnet: 10.233.0.0/18
    scheduler:
```
