### ISSUE TITLE
pods/ks-apiserver-955c6479f-8qffx -n kubesphere-system pod CrashLoopBackOff

### ISSUE THREAD

**Issue by zuoyangs** [kubesphere/kubekey#1731]
### What is version of KubeKey has the issue?

kk version: &version.Info{Major:"3", Minor:"0", GitVersion:"v3.0.7", GitCommit:"e755baf67198d565689d7207378174f429b508ba", GitTreeState:"clean", BuildDate:"2023-01-18T01:57:24Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### What is your os environment?

3.10.0-1160.el7.x86_64（CentOS Linux release 7.9.2009 (Core)）

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: k8s-master-0-11, address: 192.168.0.11, internalAddress: 192.168.0.11, user: root, password: "redhatqwer"}
  - {name: k8s-master-0-12, address: 192.168.0.12, internalAddress: 192.168.0.12, user: root, password: "redhatqwer"}
  - {name: k8s-master-0-13, address: 192.168.0.13, internalAddress: 192.168.0.13, user: root, password: "redhatqwer"}
  - {name: k8s-worker-0-15, address: 192.168.0.15, internalAddress: 192.168.0.15, user: root, password: "redhatqwer"}
  - {name: k8s-worker-0-16, address: 192.168.0.16, internalAddress: 192.168.0.16, user: root, password: "redhatqwer"}
  - {name: k8s-worker-0-17, address: 192.168.0.17, internalAddress: 192.168.0.17, user: root, password: "redhatqwer"}
  - {name: k8s-worker-0-18, address: 192.168.0.18, internalAddress: 192.168.0.18, user: root, password: "redhatqwer"}
  roleGroups:
    etcd:
    - k8s-master-0-11
    - k8s-master-0-12
    - k8s-master-0-13
    control-plane: 
    - k8s-master-0-11
    - k8s-master-0-12
    - k8s-master-0-13
    worker:
    - k8s-worker-0-15
    - k8s-worker-0-16
    - k8s-worker-0-17
    - k8s-worker-0-18
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    #internalLoadbalancer: haproxy
    domain: lb.kubesphere.local
    address: "192.168.0.11"
    port: 6443
  kubernetes:
    version: v1.25.3
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []



---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.3.2
spec:
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  zone: ""
  local_registry: ""
  namespace_override: ""
  # dev_tag: ""
  etcd:
    monitoring: true
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    apiserver:
      resources: {}
    controllerManager:
      resources: {}
    redis:
      enabled: true
      volumeSize: 2Gi
    openldap:
      enabled: true
      volumeSize: 2Gi
    minio:
      volumeSize: 20Gi
    monitoring:
      type: external
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      GPUMonitoring:
        enabled: false
    gpu:
      kinds:
      - resourceName: "nvidia.com/gpu"
        resourceType: "GPU"
        default: true
    es:
      master:
        volumeSize: 4Gi
        replicas: 1
        resources: {}
      data:
        volumeSize: 20Gi
        replicas: 1
        resources: {}
      logMaxAge: 7
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchHost: ""
      externalElasticsearchPort: ""
  alerting:
    enabled: true
    thanosruler:
      replicas: 1
      resources: {}
  auditing:
    enabled: true
    operator:
      resources: {}
    webhook:
      resources: {}
  devops:
    enabled: true
    resources: {}
    jenkinsMemoryLim: 8Gi
    jenkinsMemoryReq: 4Gi
    jenkinsVolumeSize: 8Gi
  events:
    enabled: true
    operator:
      resources: {}
    exporter:
      resources: {}
    ruler:
      enabled: true
      replicas: 2
      resources: {}
  logging:
    enabled: true
    logsidecar:
      enabled: true
      replicas: 2
      # resources: {}
  metrics_server:
    enabled: true
  monitoring:
    storageClass: ""
    node_exporter:
      port: 9100
      resources: {}
    kube_rbac_proxy:
      resources: {}
    kube_state_metrics:
      resources: {}
    prometheus:
      replicas: 1
      volumeSize: 20Gi
      resources: {}
      operator:
        resources: {}
    alertmanager:
      replicas: 1
      resources: {}
    notification_manager:
      resources: {}
      operator:
        resources: {}
      proxy:
        resources: {}
    gpu:
      nvidia_dcgm_exporter:
        enabled: false
        # resources: {}
  multicluster:
    clusterRole: none
  network:
    networkpolicy:
      enabled: true
    ippool:
      type: none
    topology:
      type: none
  openpitrix:
    store:
      enabled: false
  servicemesh:
    enabled: true
    istio:
      components:
        ingressGateways:
        - name: istio-ingressgateway
          enabled: true
        cni:
          enabled: true
  edgeruntime:
    enabled: true
    kubeedge:
      enabled: true
      cloudCore:
        cloudHub:
          advertiseAddress:
            - ""
        service:
          cloudhubNodePort: "30000"
          cloudhubQuicNodePort: "30001"
          cloudhubHttpsNodePort: "30002"
          cloudstreamNodePort: "30003"
          tunnelNodePort: "30004"
        # resources: {}
        # hostNetWork: false
      iptables-manager:
        enabled: true
        mode: "external"
        # resources: {}
      # edgeService:
      #   resources: {}
  terminal:
    timeout: 600
```

### A clear and concise description of what happend.

kk 安装好后，提示：
