### ISSUE TITLE
create cluster by kk v3.0.2 with config file, dns failed

### ISSUE THREAD

**Issue by oulinbao** [kubesphere/kubekey#1748]
### What is version of KubeKey has the issue?

3.0.2

### What is your os environment?

ubuntu 22.04.1

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: master
spec:
  hosts:
  ##You should complete the ssh information of the hosts
  - {name: master, address: 10.106.55.164, internalAddress: 10.106.55.164}
  - {name: node3, address: 10.106.55.163, internalAddress: 10.106.55.163}
  roleGroups:
    etcd:
    - master
    master:
    - master
    worker:
    - master
    - node3
  controlPlaneEndpoint:
    ##Internal loadbalancer for apiservers
    #internalLoadbalancer: haproxy

    ##If the external loadbalancer was used, 'address' should be set to loadbalancer's ip.
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.23.10
    clusterName: cluster.local
    proxyMode: ipvs
    masqueradeAll: false
    maxPods: 1000
    nodeCidrMaskSize: 24
  network:
    plugin: cilium
    kubePodsCIDR: 10.233.0.0/16
    kubeServiceCIDR: 10.244.0.0/16
  registry:
    privateRegistry: ""
```

### A clear and concise description of what happend.

install kubesphere in bare metal server with kk.
if using -f cluster.yaml for the first time, it will report dns error.
I must install it without config file (all in one), then add nodes for the second time.

### Relevant log output

```shell
<-- GET /kapis/monitoring.kubesphere.io/v1alpha3/cluster?metrics_filter=cluster_cpu_usage%7Ccluster_cpu_total%7Ccluster_cpu_utilisation%7Ccluster                                                           _memory_usage_wo_cache%7Ccluster_memory_total%7Ccluster_memory_utilisation%7Ccluster_disk_size_usage%7Ccluster_disk_size_capacity%7Ccluster_disk_si                                                           ze_utilisation%7Ccluster_pod_running_count%7Ccluster_pod_quota%24 2023/02/23T03:59:39.525
  <-- GET /kapis/monitoring.kubesphere.io/v1alpha3/components/apiserver?metrics_filter=apiserver_request_latencies%7Capiserver_request_by_verb_late                                                           ncies%7Capiserver_request_rate%24 2023/02/23T03:59:39.532
  <-- GET /kapis/resources.kubesphere.io/v1alpha2/componenthealth 2023/02/23T03:59:41.119
Error: getaddrinfo EAI_AGAIN ks-apiserver
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'ks-apiserver'
}
Error: getaddrinfo EAI_AGAIN ks-apiserver
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'ks-apiserver'
}
Error: getaddrinfo EAI_AGAIN ks-apiserver
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'ks-apiserver'
}
  --> GET /kapis/monitoring.kubesphere.io/v1alpha3/cluster?metrics_filter=cluster_cpu_usage%7Ccluster_cpu_total%7Ccluster_cpu_utilisation%7Ccluster                                                           _memory_usage_wo_cache%7Ccluster_memory_total%7Ccluster_memory_utilisation%7Ccluster_disk_size_usage%7Ccluster_disk_size_capacity%7Ccluster_disk_si                                                           ze_utilisation%7Ccluster_pod_running_count%7Ccluster_pod_quota%24 500 5,007ms - 2023/02/23T03:59:44.532
  --> GET /kapis/monitoring.kubesphere.io/v1alpha3/components/apiserver?metrics_filter=apiserver_request_latencies%7Capiserver_request_by_verb_late                                                           ncies%7Capiserver_request_rate%24 500 5,000ms - 2023/02/23T03:59:44.532
  --> GET /kapis/resources.kubesphere.io/v1alpha2/componenthealth 500 3,413ms - 2023/02/23T03:59:44.532
  <-- GET /kapis/monitoring.kubesphere.io/v1alpha3/components/scheduler?metrics_filter=scheduler_schedule_attempts%7Cscheduler_schedule_attempt_rat                                                           e%24 2023/02/23T03:59:44.612
```
