### ISSUE TITLE
Failed to install k8s after single-core cpu installation failed

### ISSUE THREAD

**Issue by HeyChiang** [kubesphere/kubekey#1753]
### What is version of KubeKey has the issue?

kk version: &version.Info{Major:"3", Minor:"0", GitVersion:"v3.0.7", GitCommit:"e755baf67198d565689d7207378174f429b508ba", GitTreeState:"clean", BuildDate:"2023-01-18T01:57:24Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### What is your os environment?

Linux master 5.10.134-13.al8.x86_64 #1 SMP Mon Jan 9 10:50:49 CST 2023 x86_64 x86_64 x86_64 GNU/Linux

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master, address: 192.168.2.146, internalAddress: 192.168.2.146, user: root, password: "xxxx"}
  - {name: node1, address: 192.168.2.145, internalAddress: 192.168.2.145, user: root, password: "xxxx"}
  roleGroups:
    etcd:
    - master
    control-plane:
    - master
    worker:
    - node1
    - master
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: 1.26.0
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

Step 1：failed to install k8s after single-core cpu installation failed，and prompt that at least 2 cores of CPU are required.
Step 2：In Alibaba Cloud, upgrade the server to a 2-core CPU, and install it again:

`error #0: dial tcp 192.168.2.146:2379: connect: connection refused: Process exited with status 1
09:49:29 CST retry: [master]
09:49:34 CST message: [master]
etcd health check failed: Failed to exec command: sudo -E /bin/bash -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-master.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-master-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://192.168.2.146:2379 cluster-health | grep -q 'cluster is healthy'" 
Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 192.168.2.146:2379: connect: connection refused`

### Additional information

If the installation conditions are not met, prompt earlier
