### ISSUE TITLE
如何在安装集群时指定docker的数据目录和k8s的数据目录？

### ISSUE THREAD

**Issue by ivanmissu** [kubesphere/kubekey#1755]
如何在安装集群时指定docker的数据目录和k8s的数据目录？

**Comment by ivanmissu** [comment]
> 翻了下源代码, 配置docker数据目录需要在安装的yaml文件配置
> 
> ```yaml
> spec:
>   registry:
>     dataRoot: /data/docker
> ```

感谢， k8s数据目录知道吗，比如openebs的目录和kubelet的   我现在是磁盘不足用的软连接  出现了很多权限的问题 - -

**Comment by redscholar** [comment]
在3.0.7版本中进行如下配置
```yaml
spec:
  registry:
    dockerDataDir:  # docker作为k8s集群的cri时数据目录配置
  etcd:
    dataDir: # k8s集群数据目录配置
```
完整配置参考：https://github.com/kubesphere/kubekey/blob/master/docs/config-example.md
