### ISSUE TITLE
Installation problems in offline mode

### ISSUE THREAD

**Issue by phoenixzjh** [kubesphere/kubekey#1762]
### What is version of KubeKey has the issue?

3.0.7

### What is your os environment?

CentOS 9 

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: 192.168.8.20, internalAddress: 192.168.8.20, user: root, password: "A123123"}
  roleGroups:
    etcd:
    - node1
    control-plane: 
    - node1
    worker:
    - node1
    registry:
    - node1
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.25.5
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: dockerhub.kubekey.local
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

Execute the following command line
kk create cluster - f k8s.yaml - a kubekey.tar.gz 

Installation failed with the following error message

### Relevant log output

```shell
FATA[0000] pulling image: rpc error: code = Unknown desc = failed to pull and unpack image "dockerhub.kubekey.local/kubesphere/pause:3.8": failed to resolve reference "dockerhub.kubekey.local/kubesphere/pause:3.8": failed to do request: Head "https://dockerhub.kubekey.local/v2/kubesphere/pause/manifests/3.8": x509: certificate signed by unknown authority: Process exited with status 1
```

**Comment by phoenixzjh** [comment]
fund bus , change the /etc/containerd/config.toml file。

    [plugins."io.containerd.grpc.v1.cri".registry.configs]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."dockerhub.kubekey.local".tls]
        ca_file = "/etc/docker/certs.d/dockerhub.kubekey.local/dockerhub.kubekey.local.cert"

**Comment by xiaods** [comment]
howto add config.toml config to kubekey config

**Comment by phoenixzjh** [comment]
> howto add config.toml config to kubekey config
run command "kk create cluster - f k8s.yaml - a kubekey.tar.gz" until error , then config.toml be make

**Comment by phoenixzjh** [comment]
> howto add config.toml config to kubekey config

howto add config.toml config to kubekey config
run command "kk create cluster - f k8s.yaml - a kubekey.tar.gz" until error , then config.toml be make

**Comment by xiaods** [comment]
PR welcome

**Comment by Taurus-Le** [comment]
Modify `registry` in `config-sample.yaml` as below might solve the problem:
```yaml
registry:
    type: harbor
    auths:
      "dockerhub.kubekey.local":
        username: admin
        password: Harbor12345
        certsPath: "/etc/docker/certs.d/dockerhub.kubekey.local"
    privateRegistry: "dockerhub.kubekey.local"
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
```
