### ISSUE TITLE
Read configuration error to use ./kk create config --from-cluster 

### ISSUE THREAD

**Issue by HeyChiang** [kubesphere/kubekey#1769]
### What is version of KubeKey has the issue?

kk version: &version.Info{Major:"3", Minor:"0", GitVersion:"v3.0.7", GitCommit:"e755baf67198d565689d7207378174f429b508ba", GitTreeState:"clean", BuildDate:"2023-01-18T01:57:24Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### What is your os environment?

Linux node3 5.10.134-13.al8.x86_64 #1 SMP Mon Jan 9 10:50:49 CST 2023 x86_64 x86_64 x86_64 GNU/Linux

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master, address: 192.168.1.122, internalAddress: 192.168.1.122, user: root, password: "Chiang2022"}
  - {name: node1, address: 192.168.1.123, internalAddress: 192.168.1.123, user: root, password: "Chiang2022"}
  - {name: node2, address: 192.168.1.124, internalAddress: 192.168.1.124, user: root, password: "Chiang2022"}
  - {name: node3, address: 192.168.1.125, internalAddress: 192.168.1.125, user: root, password: "Chiang2022"}
  roleGroups:
    etcd:
    - node1
    - master
    - node2
    - node3
    control-plane: 
    - node1
    - node3
    - master
    - node2
    worker:
    - node1
    - node3
    - node2
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: 1.25.5
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

internalLoadbalancer is error.   #Should not exist！

`
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts: 
  ##You should complete the ssh information of the hosts
  - {name: master, address: 192.168.1.122, internalAddress: 192.168.1.122}
  - {name: node1, address: 192.168.1.123, internalAddress: 192.168.1.123}
  - {name: node2, address: 192.168.1.124, internalAddress: 192.168.1.124}
  - {name: node3, address: 192.168.1.125, internalAddress: 192.168.1.125}
  roleGroups:
    etcd:
    - SHOULD_BE_REPLACED
    master:
    worker:
    - master
    - node1
    - node2
    - node3
  controlPlaneEndpoint:
    ##Internal loadbalancer for apiservers
    #internalLoadbalancer: haproxy

    ##If the external loadbalancer was used, 'address' should be set to loadbalancer's ip.
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.25.5
    clusterName: cluster.local
    proxyMode: ipvs
    masqueradeAll: false
    maxPods: 110
    nodeCidrMaskSize: 24
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    privateRegistry: ""
`
