### ISSUE TITLE
Can't upgrade k8s from v1.25.5 to v1.26.0

### ISSUE THREAD

**Issue by HeyChiang** [kubesphere/kubekey#1773]
### What is version of KubeKey has the issue?

.kk version: &version.Info{Major:"3", Minor:"0", GitVersion:"v3.0.7", GitCommit:"e755baf67198d565689d7207378174f429b508ba", GitTreeState:"clean", BuildDate:"2023-01-18T01:57:24Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### What is your os environment?

Linux master 5.10.134-13.al8.x86_64 #1 SMP Mon Jan 9 10:50:49 CST 2023 x86_64 x86_64 x86_64 GNU/Linux

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master, address: 172.23.2.112, internalAddress: 172.23.2.112, user: root, password: "Chiang2022"}
  - {name: node1, address: 172.23.2.113, internalAddress: 172.23.2.113, user: root, password: "Chiang2022"}
  roleGroups:
    etcd:
    - node1
    - master
    control-plane:
    - node1
    - master
    worker:
    - node1
    - master
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: 1.25.5
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

[root@k8s-000000 ~]# ./kk upgrade --with-kubernetes v1.26.0 -f config-sample.yaml 

 _   __      _          _   __           
| | / /     | |        | | / /           
| |/ / _   _| |__   ___| |/ /  ___ _   _ 
|    \| | | | '_ \ / _ \    \ / _ \ | | |
| |\  \ |_| | |_) |  __/ |\  \  __/ |_| |
\_| \_/\__,_|_.__/ \___\_| \_/\___|\__, |
                                    __/ |
                                   |___/

14:08:37 CST [GreetingsModule] Greetings
14:08:37 CST message: [master]
Greetings, KubeKey!
14:08:37 CST message: [node1]
Greetings, KubeKey!
14:08:37 CST success: [master]
14:08:37 CST success: [node1]
14:08:37 CST [NodePreCheckModule] A pre-check on nodes
14:08:37 CST success: [master]
14:08:37 CST success: [node1]
14:08:37 CST [ClusterPreCheckModule] Get KubeConfig file
14:08:37 CST skipped: [master]
14:08:37 CST success: [node1]
14:08:37 CST [ClusterPreCheckModule] Get all nodes Kubernetes version
14:08:38 CST success: [master]
14:08:38 CST success: [node1]
14:08:38 CST [ClusterPreCheckModule] Calculate min Kubernetes version
14:08:38 CST skipped: [master]
14:08:38 CST success: [node1]
14:08:38 CST [ClusterPreCheckModule] Check desired Kubernetes version
14:08:38 CST message: [node1]
does not support upgrade to Kubernetes v1.26.0
14:08:38 CST retry: [node1]
14:08:43 CST message: [node1]
does not support upgrade to Kubernetes v1.26.0
14:08:43 CST retry: [node1]
14:08:48 CST message: [node1]
does not support upgrade to Kubernetes v1.26.0
14:08:48 CST skipped: [master]
14:08:48 CST failed: [node1]
error: Pipeline[UpgradeClusterPipeline] execute failed: Module[ClusterPreCheckModule] exec failed: 
failed: [node1] [CheckDesiredK8sVersion] exec failed after 3 retires: does not support upgrade to Kubernetes v1.26.0
[root@k8s-000000 ~]# ./kk version
.kk version: &version.Info{Major:"3", Minor:"0", GitVersion:"v3.0.7", GitCommit:"e755baf67198d565689d7207378174f429b508ba", GitTreeState:"clean", BuildDate:"2023-01-18T01:57:24Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
