### ISSUE TITLE
Failed to scale the all-in-one to HA cluster

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubekey#181]
My config file:

```
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: config-sample
spec:
  hosts:
  - {name: ks-allinone, address: 192.168.0.2, internalAddress: 192.168.0.2, password: Qcloud@123}
  - {name: master2, address: 192.168.0.3, internalAddress: 192.168.0.3, password: Qcloud@123}
  - {name: master3, address: 192.168.0.4, internalAddress: 192.168.0.4, password: Qcloud@123}
  - {name: node1, address: 192.168.0.5, internalAddress: 192.168.0.5, password: Qcloud@123}
  - {name: node2, address: 192.168.0.6, internalAddress: 192.168.0.6, password: Qcloud@123}
  roleGroups:
    etcd:
    - ks-allinone
    - master2
    - master3
    master:
    - ks-allinone
    - master2
    - master3
    worker:
    - node1
    - node2
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: "192.168.0.253"
    port: "6443"
  kubernetes:
    version: v1.17.9
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: [https://4fnani4g.mirror.aliyuncs.com]
    insecureRegistries: []
  storage:
    defaultStorageClass: localVolume
    localVolume:
      storageClassName: local


---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.0.0
spec:
  local_registry: ""
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  etcd:
    monitoring: true
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    es:
      elasticsearchDataReplicas: 1
      elasticsearchDataVolumeSize: 20Gi
      elasticsearchMasterReplicas: 1
      elasticsearchMasterVolumeSize: 4Gi
      elkPrefix: logstash
      logMaxAge: 7
    mysqlVolumeSize: 20Gi
    minioVolumeSize: 20Gi
    etcdVolumeSize: 20Gi
    openldapVolumeSize: 2Gi
    redisVolumSize: 2Gi
  console:
    enableMultiLogin: false  # enable/disable multi login
    port: 30880
  alerting:
    enabled: true
  auditing:
    enabled: true
  devops:
    enabled: true
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 512m
    jenkinsJavaOpts_Xmx: 512m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: true
    ruler:
      enabled: true
      replicas: 2
  logging:
    enabled: true
    logsidecarReplicas: 2
  metrics_server:
    enabled: true
  monitoring:
    prometheusReplicas: 1
    prometheusMemoryRequest: 400Mi
    prometheusVolumeSize: 20Gi
    alertmanagerReplicas: 1
  multicluster:
    clusterRole: none  # host | member | none
  networkpolicy:
    enabled: true
  notification:
    enabled: true
  openpitrix:
    enabled: true
  servicemesh:
    enabled: true
```

After I execute the command `./kk scale -f config-sample.yaml`, it returns: 

```
Error: Failed to download cluster config: Unable to unmarshal the given cluster configuration file: yaml: line 7: mapping values are not allowed in this context
Usage:
  kk scale [flags]

Flags:
  -f, --file string   Path to a configuration file
  -h, --help          help for scale
  -y, --yes           Skip pre-check of the installation

Global Flags:
      --debug   Print detailed information (default true)

Failed to download cluster config: Unable to unmarshal the given cluster configuration file: yaml: line 7: mapping values are not allowed in this context
```

Any errors in line 7?
