### ISSUE TITLE
使用kubekey离线安装时，必须要下载镜像仓库，但离线状态不能联网

### ISSUE THREAD

**Issue by FumingD** [kubesphere/kubekey#1845]
### What is version of KubeKey has the issue?

3.0.7

### What is your os environment?

centos 7.9

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2

kind: Cluster

metadata:

  name: sample

spec:

  hosts:

  - {name: master1, address: 192.168.0.3, internalAddress: 192.168.0.3, user: root, password: "<REPLACE_WITH_YOUR_ACTUAL_PASSWORD>"}
  - {name: master2, address: 192.168.0.4, internalAddress: 192.168.0.4, user: root, password: "<REPLACE_WITH_YOUR_ACTUAL_PASSWORD>"}
  - {name: master2, address: 192.168.0.6, internalAddress: 192.168.0.6, user: root, password: "<REPLACE_WITH_YOUR_ACTUAL_PASSWORD>"}

  - {name: node1, address: 192.168.0.5, internalAddress: 192.168.0.5, user: root, password: "<REPLACE_WITH_YOUR_ACTUAL_PASSWORD>"}



  roleGroups:

    etcd:

    - master1
    - master2
    - master3
    control-plane:
    - master1
    - master2
    - master3

    worker:

    - node1

    # 如需使用 kk 自动部署镜像仓库，请设置该主机组 （建议仓库与集群分离部署，减少相互影响）

    registry:

    - node1

  controlPlaneEndpoint:

    ## Internal loadbalancer for apiservers

    # internalLoadbalancer: haproxy



    domain: lb.kubesphere.local

    address: ""

    port: 6443

  kubernetes:

    version: v1.22.12

    clusterName: cluster.local

  network:

    plugin: calico

    kubePodsCIDR: 10.233.64.0/18

    kubeServiceCIDR: 10.233.0.0/18

    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni

    multusCNI:

      enabled: false

  registry:

    # 如需使用 kk 部署 harbor, 可将该参数设置为 harbor，不设置该参数且需使用 kk 创建容器镜像仓库，将默认使用docker registry。

    type: harbor

    # 如使用 kk 部署的 harbor 或其他需要登录的仓库，可设置对应仓库的auths，如使用 kk 创建的 docker registry 仓库，则无需配置该参数。

    # 注意：如使用 kk 部署 harbor，该参数请于 harbor 启动后设置。

    #auths:

    #  "dockerhub.kubekey.local":

    #    username: admin

    #    password: Harbor12345

    # 设置集群部署时使用的私有仓库

    privateRegistry: ""

    namespaceOverride: ""

    registryMirrors: []

    insecureRegistries: []

  addons: []
```

### A clear and concise description of what happend.

1. 按照官网上的步骤，首先在线部署了1个master节点，一个node节点的集群，部署成功，node节点上部署了harbor。
2. 使用这个已经部署好的k8s集群，生成离线制品和manifest。
3. 导出这个离线制品和manifest到离线环境，开始离线部署。
4. 执行./kk init registry -f config-sample.yaml -a kubesphere.tar.gz  这个命令创建镜像仓库harbor。
屏幕打印需要download harbor-offline-2.5.3 压缩包，但是无法联网，curl 下载命令执行失败。
尝试绕过下载，将之前已经下载的harbor-offline-2.5.3压缩包，放置于需要放置的地方（执行命令屏幕提示了，下载后放置的地方），然而并没有绕过harbor这个下载步骤。
看下能否通过提前准备离线制品方式，绕过harbor下载的步骤呢？

### Relevant log output

```shell
因为离线环境，无法拍照和拷贝，只能大概描述：
执行./kk init registry -f config-sample.yaml -a kubesphere.tar.gz， 后需要下载harbor
```

### Additional information

百分百复现，导致无法按照官网的操作步骤，离线部署一套k8s
