### ISSUE TITLE
Considering support install addon from a tar file which located in an URL

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/kubekey#1888]
### Describe this feature

For many open-source projects, we could found the manifest files from the GitHub release tar file. It would be great if we could only specific the URL instead of downloading it and unzip.

### Describe the solution you'd like

The example usage likes:
```yaml
  addons:
  - url: https://github.com/foo/bar/xxx.tar.gz
    format: yaml | kustomizaion
```
