### ISSUE TITLE
ARM64执行安装时，ks-installer和kube-controller容器无法启动

### ISSUE THREAD

**Issue by q11w2212** [kubesphere/kubekey#1891]
### What is version of KubeKey has the issue?

v3.0.7-dirty

### What is your os environment?

CentOS-7-aarch64-Minimal-2009

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: 172.18.97.20, internalAddress: 172.18.97.20, user: root, password: "111111", arch: arm64}
  - {name: node2, address: 172.18.97.21, internalAddress: 172.18.97.21, user: root, password: "111111", arch: arm64}
  - {name: node3, address: 172.18.97.22, internalAddress: 172.18.97.22, user: root, password: "111111", arch: arm64}
  - {name: node4, address: 172.18.97.23, internalAddress: 172.18.97.23, user: root, password: "111111", arch: arm64}
  roleGroups:
    etcd:
    - node1
    control-plane:
    - node1
    worker:
    - node2
    - node3
    - node4
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.23.10
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: docker
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []



---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: 3.2.0
spec:
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  zone: ""
  local_registry: ""
  # dev_tag: ""
  etcd:
    monitoring: false
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    # apiserver:
    #  resources: {}
    # controllerManager:
    #  resources: {}
    redis:
      enabled: false
      volumeSize: 2Gi
    openldap:
      enabled: false
      volumeSize: 2Gi
    minio:
      volumeSize: 20Gi
    monitoring:
      # type: external
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      GPUMonitoring:
        enabled: false
    gpu:
      kinds:
      - resourceName: "nvidia.com/gpu"
        resourceType: "GPU"
        default: true
    es:
      # master:
      #   volumeSize: 4Gi
      #   replicas: 1
      #   resources: {}
      # data:
      #   volumeSize: 20Gi
      #   replicas: 1
      #   resources: {}
      logMaxAge: 7
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchUrl: ""
      externalElasticsearchPort: ""
  alerting:
    enabled: false
    # thanosruler:
    #   replicas: 1
    #   resources: {}
  auditing:
    enabled: false
    # operator:
    #   resources: {}
    # webhook:
    #   resources: {}
  devops:
    enabled: false
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 512m
    jenkinsJavaOpts_Xmx: 512m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: false
    # operator:
    #   resources: {}
    # exporter:
    #   resources: {}
    # ruler:
    #   enabled: true
    #   replicas: 2
    #   resources: {}
  logging:
    enabled: false
    containerruntime: docker
    logsidecar:
      enabled: true
      replicas: 2
      # resources: {}
  metrics_server:
    enabled: false
  monitoring:
    storageClass: ""
    # kube_rbac_proxy:
    #   resources: {}
    # kube_state_metrics:
    #   resources: {}
    # prometheus:
    #   replicas: 1
    #   volumeSize: 20Gi
    #   resources: {}
    #   operator:
    #     resources: {}
    #   adapter:
    #     resources: {}
    # node_exporter:
    #   resources: {}
    # alertmanager:
    #   replicas: 1
    #   resources: {}
    # notification_manager:
    #   resources: {}
    #   operator:
    #     resources: {}
    #   proxy:
    #     resources: {}
    gpu:
      nvidia_dcgm_exporter:
        enabled: false
        # resources: {}
  multicluster:
    clusterRole: none
  network:
    networkpolicy:
      enabled: false
    ippool:
      type: none
    topology:
      type: none
  openpitrix:
    store:
      enabled: false
  servicemesh:
    enabled: false
  kubeedge:
    enabled: false
    cloudCore:
      nodeSelector: {"node-role.kubernetes.io/worker": ""}
      tolerations: []
      cloudhubPort: "10000"
      cloudhubQuicPort: "10001"
      cloudhubHttpsPort: "10002"
      cloudstreamPort: "10003"
      tunnelPort: "10004"
      cloudHub:
        advertiseAddress:
          - ""
        nodeLimit: "100"
      service:
        cloudhubNodePort: "30000"
        cloudhubQuicNodePort: "30001"
        cloudhubHttpsNodePort: "30002"
        cloudstreamNodePort: "30003"
        tunnelNodePort: "30004"
    edgeWatcher:
      nodeSelector: {"node-role.kubernetes.io/worker": ""}
      tolerations: []
      edgeWatcherAgent:
        nodeSelector: {"node-role.kubernetes.io/worker": ""}
        tolerations: []
```

### A clear and concise description of what happend.

kubectl get po -A
NAMESPACE           NAME                                           READY   STATUS             RESTARTS          AGE
kube-system         calico-kube-controllers-676c86494f-r7jkm       1/1     Running            0                 12h
kube-system         calico-node-j72tx                              1/1     Running            0                 12h
kube-system         calico-node-mknq7                              1/1     Running            0                 12h
kube-system         calico-node-x62bk                              1/1     Running            0                 12h
kube-system         calico-node-xtz2m                              1/1     Running            0                 12h
kube-system         coredns-757cd945b-l2c57                        1/1     Running            0                 12h
kube-system         coredns-757cd945b-ldkvm                        1/1     Running            0                 12h
kube-system         kube-apiserver-node1                           1/1     Running            0                 12h
kube-system         kube-controller-manager-node1                  1/1     Running            0                 12h
kube-system         kube-proxy-48rn6                               1/1     Running            0                 12h
kube-system         kube-proxy-bnqhp                               1/1     Running            0                 12h
kube-system         kube-proxy-jh2wf                               1/1     Running            0                 12h
kube-system         kube-proxy-qqlz4                               1/1     Running            0                 12h
kube-system         kube-scheduler-node1                           1/1     Running            0                 12h
kube-system         nodelocaldns-9n86l                             1/1     Running            0                 12h
kube-system         nodelocaldns-dmfwq                             1/1     Running            0                 12h
kube-system         nodelocaldns-hnjqb                             1/1     Running            0                 12h
kube-system         nodelocaldns-qmfmb                             1/1     Running            0                 12h
kube-system         openebs-localpv-provisioner-7974b86588-2htt2   1/1     Running            0                 12h
kubesphere-system   ks-installer-7b5566b777-vg9f2                  0/1     CrashLoopBackOff   154 (4m40s ago)   12h
