### ISSUE TITLE
install k3s with kk

### ISSUE THREAD

**Issue by mymickey** [kubesphere/kubekey#1908]
### What is version of KubeKey has the issue?

kk version: &version.Info{Major:"3", Minor:"0", GitVersion:"v3.0.7", GitCommit:"e755baf67198d565689d7207378174f429b508ba", GitTreeState:"clean", BuildDate:"2023-01-18T01:57:24Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### What is your os environment?

Linux ubuntu 6.3.12-orbstack-00209-ga2cd8129a099 #1 SMP Mon Jul 10 05:35:25 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master1, address: xxx, internalAddress: xxx, user: root, password: "123"}
  roleGroups:
    etcd:
    - master1
    control-plane: 
    - master1
    worker:
    - master1
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.21.4-k3s
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: docker
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []



---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.3.2
spec:
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  zone: ""
  local_registry: ""
  namespace_override: ""
  # dev_tag: ""
  etcd:
    monitoring: false
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    # apiserver:
    #  resources: {}
    # controllerManager:
    #  resources: {}
    redis:
      enabled: false
      volumeSize: 2Gi
    openldap:
      enabled: false
      volumeSize: 2Gi
    minio:
      volumeSize: 20Gi
    monitoring:
      # type: external
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      GPUMonitoring:
        enabled: false
    gpu:
      kinds:
      - resourceName: "nvidia.com/gpu"
        resourceType: "GPU"
        default: true
    es:
      # master:
      #   volumeSize: 4Gi
      #   replicas: 1
      #   resources: {}
      # data:
      #   volumeSize: 20Gi
      #   replicas: 1
      #   resources: {}
      logMaxAge: 7
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchHost: ""
      externalElasticsearchPort: ""
  alerting:
    enabled: false
    # thanosruler:
    #   replicas: 1
    #   resources: {}
  auditing:
    enabled: false
    # operator:
    #   resources: {}
    # webhook:
    #   resources: {}
  devops:
    enabled: false
    # resources: {}
    jenkinsMemoryLim: 8Gi
    jenkinsMemoryReq: 4Gi
    jenkinsVolumeSize: 8Gi
  events:
    enabled: false
    # operator:
    #   resources: {}
    # exporter:
    #   resources: {}
    # ruler:
    #   enabled: true
    #   replicas: 2
    #   resources: {}
  logging:
    enabled: false
    logsidecar:
      enabled: true
      replicas: 2
      # resources: {}
  metrics_server:
    enabled: false
  monitoring:
    storageClass: ""
    node_exporter:
      port: 9100
      # resources: {}
    # kube_rbac_proxy:
    #   resources: {}
    # kube_state_metrics:
    #   resources: {}
    # prometheus:
    #   replicas: 1
    #   volumeSize: 20Gi
    #   resources: {}
    #   operator:
    #     resources: {}
    # alertmanager:
    #   replicas: 1
    #   resources: {}
    # notification_manager:
    #   resources: {}
    #   operator:
    #     resources: {}
    #   proxy:
    #     resources: {}
    gpu:
      nvidia_dcgm_exporter:
        enabled: false
        # resources: {}
  multicluster:
    clusterRole: none
  network:
    networkpolicy:
      enabled: false
    ippool:
      type: none
    topology:
      type: none
  openpitrix:
    store:
      enabled: false
  servicemesh:
    enabled: false
    istio:
      components:
        ingressGateways:
        - name: istio-ingressgateway
          enabled: false
        cni:
          enabled: false
  edgeruntime:
    enabled: false
    kubeedge:
      enabled: false
      cloudCore:
        cloudHub:
          advertiseAddress:
            - ""
        service:
          cloudhubNodePort: "30000"
          cloudhubQuicNodePort: "30001"
          cloudhubHttpsNodePort: "30002"
          cloudstreamNodePort: "30003"
          tunnelNodePort: "30004"
        # resources: {}
        # hostNetWork: false
      iptables-manager:
        enabled: true
        mode: "external"
        # resources: {}
      # edgeService:
      #   resources: {}
  terminal:
    timeout: 600
```

### A clear and concise description of what happend.

install log on tail
`customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipreservations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/kubecontrollersconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org created
clusterrole.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrole.rbac.authorization.k8s.io/calico-node created
clusterrolebinding.rbac.authorization.k8s.io/calico-node created
daemonset.apps/calico-node created
serviceaccount/calico-node created
deployment.apps/calico-kube-controllers created
serviceaccount/calico-kube-controllers created
poddisruptionbudget.policy/calico-kube-controllers created
15:31:18 CST success: [master1]
15:31:18 CST [ConfigureKubernetesModule] Configure kubernetes
15:31:18 CST success: [master1]
15:31:18 CST [ChownModule] Chown user $HOME/.kube dir
15:31:18 CST success: [master1]
15:31:18 CST [AutoRenewCertsModule] Generate k8s certs renew script
15:31:18 CST success: [master1]
15:31:18 CST [AutoRenewCertsModule] Generate k8s certs renew service
15:31:19 CST success: [master1]
15:31:19 CST [AutoRenewCertsModule] Generate k8s certs renew timer
15:31:19 CST success: [master1]
15:31:19 CST [AutoRenewCertsModule] Enable k8s certs renew service
15:31:20 CST success: [master1]
15:31:20 CST [SaveKubeConfigModule] Save kube config as a configmap
15:31:20 CST message: [LocalHost]
Post "https://127.0.0.1:6443/api/v1/namespaces": dial tcp 127.0.0.1:6443: connect: connection refused
15:31:20 CST failed: [LocalHost]
error: Pipeline[K3sCreateClusterPipeline] execute failed: Module[SaveKubeConfigModule] exec failed:
failed: [LocalHost] [SaveKubeConfig] exec failed after 1 retires: Post "https://127.0.0.1:6443/api/v1/namespaces": dial tcp 127.0.0.1:6443: connect: connection refused`

`
root@VM-28-12-ubuntu:/home/ubuntu# journalctl -xeu k3s.service
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.358015   12891 shared_informer.go:247] Caches are synced for stateful set
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.406909   12891 shared_informer.go:247] Caches are synced for resource quota
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.408049   12891 shared_informer.go:247] Caches are synced for resource quota
Jul 11 15:31:29 master1 k3s[12891]: W0711 15:31:29.410896   12891 actual_state_of_world.go:534] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed tr>
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.412755   12891 shared_informer.go:247] Caches are synced for cronjob
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.443314   12891 shared_informer.go:247] Caches are synced for attach detach
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.457880   12891 shared_informer.go:247] Caches are synced for TTL
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.458906   12891 shared_informer.go:247] Caches are synced for GC
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.459346   12891 shared_informer.go:247] Caches are synced for persistent volume
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.472757   12891 shared_informer.go:247] Caches are synced for node
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.472811   12891 range_allocator.go:172] Starting range CIDR allocator
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.472818   12891 shared_informer.go:240] Waiting for caches to sync for cidrallocator
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.472823   12891 shared_informer.go:247] Caches are synced for cidrallocator
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.479329   12891 range_allocator.go:373] Set node master1 PodCIDR to [10.233.64.0/24]
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.480511   12891 cni.go:239] "Unable to update cni config" err="no networks found in /etc/cni/net.d"
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.481945   12891 shared_informer.go:247] Caches are synced for endpoint_slice
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.489884   12891 shared_informer.go:247] Caches are synced for taint
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.490083   12891 node_lifecycle_controller.go:1398] Initializing eviction metric for zone:
Jul 11 15:31:29 master1 k3s[12891]: W0711 15:31:29.490181   12891 node_lifecycle_controller.go:1013] Missing timestamp for Node master1. Assuming now as a timestamp.
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.490257   12891 node_lifecycle_controller.go:1164] Controller detected that all Nodes are not-Ready. Entering master disruption mode.
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.490352   12891 event.go:291] "Event occurred" object="master1" kind="Node" apiVersion="v1" type="Normal" reason="RegisteredNode" message="Node master1 event: >
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.490477   12891 taint_manager.go:187] "Starting NoExecuteTaintManager"
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.497397   12891 shared_informer.go:247] Caches are synced for daemon sets
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.509639   12891 controller.go:611] quota admission added evaluator for: replicasets.apps
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.515300   12891 event.go:291] "Event occurred" object="kube-system/coredns" kind="Deployment" apiVersion="apps/v1" type="Normal" reason="ScalingReplicaSet" mes>
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.516504   12891 event.go:291] "Event occurred" object="kube-system/calico-kube-controllers" kind="Deployment" apiVersion="apps/v1" type="Normal" reason="Scalin>
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.531636   12891 kuberuntime_manager.go:1044] "Updating runtime config through cri with podcidr" CIDR="10.233.64.0/24"
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.532794   12891 docker_service.go:359] "Docker cri received runtime config" runtimeConfig="&RuntimeConfig{NetworkConfig:&NetworkConfig{PodCidr:10.233.64.0/24,}>
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.538095   12891 kubelet_network.go:76] "Updating Pod CIDR" originalPodCIDR="" newPodCIDR="10.233.64.0/24"
Jul 11 15:31:29 master1 k3s[12891]: E0711 15:31:29.551620   12891 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:docker: network pl>
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.907222   12891 shared_informer.go:247] Caches are synced for garbage collector
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.907248   12891 garbagecollector.go:151] Garbage collector: all resource monitors have synced. Proceeding to collect garbage
Jul 11 15:31:29 master1 k3s[12891]: I0711 15:31:29.953227   12891 shared_informer.go:247] Caches are synced for garbage collector
Jul 11 15:31:29 master1 k3s[12891]: E0711 15:31:29.993451   12891 kubelet.go:2211] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:docker: network pl>
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.060236   12891 controller.go:611] quota admission added evaluator for: controllerrevisions.apps
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.074299   12891 event.go:291] "Event occurred" object="kube-system/calico-node" kind="DaemonSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulCreate" m>
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.090918   12891 topology_manager.go:187] "Topology Admit Handler"
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.110505   12891 controller.go:611] quota admission added evaluator for: events.events.k8s.io
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.120807   12891 event.go:291] "Event occurred" object="kube-system/coredns-7448499f4d" kind="ReplicaSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulC>
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.147280   12891 event.go:291] "Event occurred" object="kube-system/calico-kube-controllers-69d878584c" kind="ReplicaSet" apiVersion="apps/v1" type="Normal" rea>
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.175732   12891 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"xtables-lock\" (UniqueName: \"kubernetes.io/host-path>
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.176014   12891 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"sysfs\" (UniqueName: \"kubernetes.io/host-path/e25d4b>
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.176123   12891 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"host-local-net-dir\" (UniqueName: \"kubernetes.io/hos>
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.176211   12891 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"lib-modules\" (UniqueName: \"kubernetes.io/host-path/>
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.176299   12891 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"var-run-calico\" (UniqueName: \"kubernetes.io/host-pa>
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.176389   12891 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"var-lib-calico\" (UniqueName: \"kubernetes.io/host-pa>
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.176471   12891 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"policysync\" (UniqueName: \"kubernetes.io/host-path/e>
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.176563   12891 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-gr5mc\" (UniqueName: \"kubernetes.io/>
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.176664   12891 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"cni-bin-dir\" (UniqueName: \"kubernetes.io/host-path/>
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.176758   12891 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"cni-net-dir\" (UniqueName: \"kubernetes.io/host-path/>
Jul 11 15:31:30 master1 k3s[12891]: I0711 15:31:30.176865   12891 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"cni-log-dir\" (UniqueName: \"kubernetes.io/host-path
`
