### ISSUE TITLE
scp file /home/yibo/kubesphere/kubekey/master3/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: Failed to exec command: sudo -E /bin/bash -c "mv -f /tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh /usr/local/bin/kube-scripts/initOS.sh" 

### ISSUE THREAD

**Issue by yisampi** [kubesphere/kubekey#1909]
### What is version of KubeKey has the issue?

v3.0.7

### What is your os environment?

ubuntu20

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master1, address: 192.168.110.172, internalAddress: 192.168.1.72, user: kube, password: kube1234}
  - {name: master2, address: 192.168.110.173, internalAddress: 192.168.1.73, user: kube, password: kube1234}
  - {name: master3, address: 192.168.110.167, internalAddress: 192.168.1.67, user: kube, password: kube1234}
  - {name: worker1, address: 192.168.110.172, internalAddress: 192.168.1.72, user: kube, password: kube1234}
  - {name: worker2, address: 192.168.110.173, internalAddress: 192.168.1.73, user: kube, password: kube1234}
  - {name: worker3, address: 192.168.110.167, internalAddress: 192.168.1.67, user: kube, password: kube1234}
  roleGroups:
    etcd:
    - master1
    - master2
    - master3
    control-plane: 
    - master1
    - master2
    - master3
    worker:
    - worker1
    - worker2
    - worker3
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: "192.168.110.254"
    port: 8443
  kubernetes:
    version: v1.23.10
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: docker
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

scp file /home/yibo/kubesphere/kubekey/master3/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: Failed to exec command: sudo -E /bin/bash -c "mv -f /tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh /usr/local/bin/kube-scripts/initOS.sh" 
mv: cannot stat '/tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh': No such file or directory: Process exited with status 1
17:16:14 CST retry: [master3]
17:16:14 CST message: [worker1]
scp file /home/yibo/kubesphere/kubekey/worker1/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: Failed to exec command: sudo -E /bin/bash -c "mv -f /tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh /usr/local/bin/kube-scripts/initOS.sh" 
mv: cannot stat '/tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh': No such file or directory: Process exited with status 1
17:16:14 CST retry: [worker1]
17:16:14 CST message: [worker2]
scp file /home/yibo/kubesphere/kubekey/worker2/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: Failed to exec command: sudo -E /bin/bash -c "mv -f /tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh /usr/local/bin/kube-scripts/initOS.sh" 
mv: cannot stat '/tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh': No such file or directory: Process exited with status 1

install 3 nodes (masters and works) for kubernetes using kk
user "kube" has sudo priviledges
