### ISSUE TITLE
arm containerd install failed

### ISSUE THREAD

**Issue by yzcyayaya** [kubesphere/kubekey#1935]
### What is version of KubeKey has the issue?

kk version: &version.Info{Major:"3", Minor:"0", GitVersion:"v3.0.9-dirty", GitCommit:"14805d8a1cd94feea4f1efabc1c2fe5cf547e9f9", GitTreeState:"dirty", BuildDate:"2023-07-21T02:24:19Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}

### What is your os environment?

ubuntu 22.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master, address: 192.168.1.4, internalAddress: 192.168.1.4, user: root, password:"123456"}
  - {name: node1, address: 192.168.1.5, internalAddress: 192.168.1.5, user: root, password: "123456"}
  - {name: node2, address: 192.168.1.6, internalAddress: 192.168.1.6, user: root, password: "123456"}
  roleGroups:
    etcd:
    - master
    control-plane:
    - master
    worker:
    - node1
    - node2
  system:
    ntpServers: #  The ntp servers of chrony.
      - time1.cloud.tencent.com
      - ntp.aliyun.com
      - node1 # Set the node name in `hosts` as ntp server if no public ntp servers access.
    timezone: "Asia/Shanghai"
  kubernetes:
    version: v1.25.5
    imageRepo: kubesphere
    containerManager: containerd #  containerd, cri-o, isula. [Default: docker]
    clusterName: cluster.local
    masqueradeAll: false
    maxPods: 110
    nodeCidrMaskSize: 24
    proxyMode: ipvs
  network:
    plugin: calico
    calico:
      ipipMode: Always
      vxlanMode: Never
      vethMTU: 1440
    kubePodsCIDR: 10.20.0.0/18
    kubeServiceCIDR: 10.30.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
    privateRegistry: ""
  addons: []
```

### A clear and concise description of what happend.

```
failed: [master] [EnableContainerd] exec failed after 3 retries: enable and start containerd failed: Failed to exec command: sudo -E /bin/bash -c "systemctl daemon-reload && systemctl enable containerd && systemctl start containerd" 
Job for containerd.service failed because the control process exited with error code.
See "systemctl status containerd.service" and "journalctl -xeu containerd.service" for details.: Process exited with status 1
```
```
root@kube-master:/usr/bin# containerd 
bash: /usr/bin/containerd: cannot execute binary file: Exec format error
```
not install arm containerd?

```
root@kube-master:/usr/bin# uname -a
Linux master 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:21:56 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

### Relevant log output

```shell
install success
```

### Additional information

use docker is error
```yaml
  kubernetes:
    version: v1.25.5
    imageRepo: kubesphere
    containerManager: docker
```
```
Incorrect runtime. Please specify a container runtime other than Docker to install Kubernetes v1.24 or later.
You can set "spec.kubernetes.containerManager" in the configuration file to "containerd" or add "--container-manager containerd" to the "./kk create cluster" command.
For more information, see:
https://github.com/kubesphere/kubekey/blob/master/docs/commands/kk-create-cluster.md
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#container-runtimes
https://kubernetes.io/blog/2022/02/17/dockershim-faq/
```
