### ISSUE TITLE
arm install  have a pod  default amd64

### ISSUE THREAD

**Issue by yzcyayaya** [kubesphere/kubekey#1940]
### What is version of KubeKey has the issue?

➜  root kubekey git:(master → origin U:3 ?:19 ✗) ./bin/kk version kk version: &version.Info{Major:"3", Minor:"0", GitVersion:"v3.0.9-dirty", GitCommit:"0343e939934086b73a119c4ca6b8197f1b756f45", GitTreeState:"dirty", BuildDate:"2023-07-29T19:11:07Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/arm64"}

### What is your os environment?

ubuntu 22.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master, address: 192.168.1.11, internalAddress: 192.168.1.11, user: root, password:"123456", arch: arm64}
  - {name: node1, address: 192.168.1.12, internalAddress: 192.168.1.12, user: root, password: "123456", arch: arm64}
  - {name: node2, address: 192.168.1.13, internalAddress: 192.168.1.13, user: root, password: "123456", arch: arm64}
  roleGroups:
    etcd:
    - master
    control-plane:
    - master
    worker:
    - node1
    - node2
  system:
    ntpServers: #  The ntp servers of chrony.
      - time1.cloud.tencent.com
      - ntp.aliyun.com
      - node1 # Set the node name in `hosts` as ntp server if no public ntp servers access.
    timezone: "Asia/Shanghai"
  kubernetes:
    version: v1.25.3
    imageRepo: kubesphere
    containerManager: containerd #  containerd, cri-o, isula. [Default: docker]
    clusterName: cluster.local
    masqueradeAll: false
    maxPods: 110
    nodeCidrMaskSize: 24
    proxyMode: ipvs
  network:
    plugin: calico
    calico:
      ipipMode: Always
      vxlanMode: Never
      vethMTU: 1440
    kubePodsCIDR: 172.16.0.0/18
    kubeServiceCIDR: 10.10.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
    privateRegistry: ""
  addons: []
```

### A clear and concise description of what happend.

default:
```
image: 'mirrorgooglecontainers/defaultbackend-amd64:1.4'            
```

to
```
image: 'mirrorgooglecontainers/defaultbackend-arm64:1.4'
```
