### ISSUE TITLE
KubeKey 3.0.10 , uses a deprecated API Error

### ISSUE THREAD

**Issue by saliven1970** [kubesphere/kubekey#1949]
### What is version of KubeKey has the issue?

3.0.10

### What is your os environment?

OpenEuler 22.03 LTS SP2

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  ## - {name: k8s-master01, address: 10.1.0.11, internalAddress: 10.1.0.11, user: root,password: "cbr@4000"}
  - {name: k8s-master01, address: 10.1.0.11, internalAddress: 10.1.0.11, privateKeyPath: "~/.ssh/id_ed25519"}
  - {name: k8s-master02, address: 10.1.0.12, internalAddress: 10.1.0.12, privateKeyPath: "~/.ssh/id_ed25519"}
  - {name: k8s-master03, address: 10.1.0.13, internalAddress: 10.1.0.13, privateKeyPath: "~/.ssh/id_ed25519"}
  - {name: k8s-worker01, address: 10.1.0.14, internalAddress: 10.1.0.14, privateKeyPath: "~/.ssh/id_ed25519"}
  - {name: k8s-worker02, address: 10.1.0.15, internalAddress: 10.1.0.15, privateKeyPath: "~/.ssh/id_ed25519"}
  - {name: k8s-worker03, address: 10.1.0.16, internalAddress: 10.1.0.16, privateKeyPath: "~/.ssh/id_ed25519"}
  - {name: k8s-storage, address: 10.1.0.17, internalAddress: 10.1.0.17, privateKeyPath: "~/.ssh/id_ed25519"}
  - {name: k8s-registry, address: 10.1.0.20, internalAddress: 10.1.0.20, privateKeyPath: "~/.ssh/id_ed25519"}
  roleGroups:
    etcd:
    - k8s-master01
    - k8s-master02
    - k8s-master03
    control-plane: 
    - k8s-master01
    - k8s-master02
    - k8s-master03
    worker:
    - k8s-worker01
    - k8s-worker02
    - k8s-worker03
    registry:
    - k8s-registry
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers. Support: haproxy, kube-vip [Default: ""]
    internalLoadbalancer: haproxy
    # Determines whether to use external dns to resolve the control-plane domain. 
    # If 'externalDNS' is set to 'true', the 'address' needs to be set to "".
    externalDNS: false  
    domain: lb.aspirecn.local
    # The IP address of your load balancer. If you use internalLoadblancer in "kube-vip" mode, a VIP is required here.
    address: ""      
    port: 6443

  system:
    # The ntp servers of chrony.
    ntpServers:
      - time1.cloud.tencent.com
      - ntp.aliyun.com
      - k8s-master01 # Set the node name in `hosts` as ntp server if no public ntp servers access.
    timezone: "Asia/Shanghai"
    # Specify additional packages to be installed. The ISO file which is contained in the artifact is required.
    rpms:
      - nfs-utils
    # Specify additional packages to be installed. The ISO file which is contained in the artifact is required.
    debs: 
      - nfs-common
    #preInstall:  # Specify custom init shell scripts for each nodes, and execute according to the list order at the first stage.
    #  - name: format and mount disk  
    #    bash: /bin/bash -x setup-disk.sh
    #    materials: # scripts can has some dependency materials. those will copy to the node        
    #      - ./setup-disk.sh # the script which shell execute need
    #      -  xxx            # other tools materials need by this script
    #postInstall: # Specify custom finish clean up shell scripts for each nodes after the Kubernetes install.
    #  - name: clean tmps files
    #    bash: |
    #       rm -fr /tmp/kubekey/*
    skipConfigureOS: true # Do not pre-configure the host OS (e.g. kernel modules, /etc/hosts, sysctl.conf, NTP servers, etc). You will have to set these things up via other methods before using KubeKey.

  kubernetes:
    version: v1.26.5
    clusterName: aspirecn.local
    # Container Runtime, support: containerd, cri-o, isula. [Default: docker]
    containerManager: containerd
    # Whether to install a script which can automatically renew the Kubernetes control plane certificates. [Default: false]
    autoRenewCerts: true
    # masqueradeAll tells kube-proxy to SNAT everything if using the pure iptables proxy mode. [Default: false].
    masqueradeAll: false
    # maxPods is the number of Pods that can run on this Kubelet. [Default: 110]
    maxPods: 110
    # podPidsLimit is the maximum number of PIDs in any pod. [Default: 10000]
    podPidsLimit: 10000
    # The internal network node size allocation. This is the size allocated to each node on your network. [Default: 24]
    nodeCidrMaskSize: 24
    # Specify which proxy mode to use. [Default: ipvs]
    proxyMode: ipvs
    # enable featureGates, [Default: {"ExpandCSIVolumes":true,"RotateKubeletServerCertificate": true,"CSIStorageCapacity":true, "TTLAfterFinished":true}]
    featureGates: 
      CSIStorageCapacity: true
      ExpandCSIVolumes: true
      RotateKubeletServerCertificate: true
      TTLAfterFinished: true
    ## support kata and NFD
    # kata:
    #   enabled: true
    # nodeFeatureDiscovery
    #   enabled: true
    # additional kube-proxy configurations
    kubeProxyConfiguration:
      ipvs:
        # CIDR's to exclude when cleaning up IPVS rules.
        # necessary to put node cidr here when internalLoadbalancer=kube-vip and proxyMode=ipvs
        # refer to: https://github.com/kubesphere/kubekey/issues/1702
        excludeCIDRs:
          - 172.16.0.2/24
  etcd:
    type: kubekey
  network:
    plugin: calico
    calico:
      ipipMode: Never  # IPIP Mode to use for the IPv4 POOL created at start up. If set to a value other than Never, vxlanMode should be set to "Never". [Always | CrossSubnet | Never] [Default: Always]
      vxlanMode: Always  # VXLAN Mode to use for the IPv4 POOL created at start up. If set to a value other than Never, ipipMode should be set to "Never". [Always | CrossSubnet | Never] [Default: Never]
      vethMTU: 0  # The maximum transmission unit (MTU) setting determines the largest packet size that can be transmitted through your network. By default, MTU is auto-detected. [Default: 0]
    kubePodsCIDR: 10.233.64.0/24
    kubeServiceCIDR: 10.233.0.0/24
  registry:
    ## `docker registry` is used to create local registry by default.  
    ## `harbor` can be also set for type.
    # type: "harbor"  
    privateRegistry: docker.kubekey.local
    auths:
      "docker.kubekey.local":
        username: admin
        password: Harbor12345
    registryMirrors: []
    insecureRegistries: []
  addons:
  - name: nfs-client
    namespace: kube-system
    sources: 
      chart: 
        name: nfs-client-provisioner
        repo: https://charts.kubesphere.io/main
        # valuesFile: /mycluster/nfs/custom-nfs-client-values.yaml  # or https://raw.githubusercontent.com/kubesphere/helm-charts/master/src/main/nfs-client-provisioner/values.yaml
        # values also supports parameter lists
        values:
        - storageClass.defaultClass=true
        - storageClass.name=nfs-client
        - nfs.server=10.1.0.17
        - nfs.path=/NfsData
```

### A clear and concise description of what happend.

init kubernetes cluster failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubeadm init --config=/etc/kubernetes/kubeadm-config.yaml --ignore-preflight-errors=FileExisting-crictl,ImagePull" 

### Relevant log output

```shell
......
21:07:43 CST [InitKubernetesModule] Generate kubeadm config
21:07:47 CST skipped: [k8s-master03]
21:07:47 CST skipped: [k8s-master02]
21:07:47 CST success: [k8s-master01]
21:07:47 CST [InitKubernetesModule] Generate audit policy
21:07:47 CST skipped: [k8s-master03]
21:07:47 CST skipped: [k8s-master01]
21:07:47 CST skipped: [k8s-master02]
21:07:47 CST [InitKubernetesModule] Generate audit webhook
21:07:47 CST skipped: [k8s-master03]
21:07:47 CST skipped: [k8s-master01]
21:07:47 CST skipped: [k8s-master02]
21:07:47 CST [InitKubernetesModule] Init cluster using kubeadm
21:07:48 CST stdout: [k8s-master01]
......
21:07:49 CST message: [k8s-master01]
init kubernetes cluster failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubeadm init --config=/etc/kubernetes/kubeadm-config.yaml --ignore-preflight-errors=FileExisting-crictl,ImagePull" 
W0808 21:07:48.609129   43948 common.go:84] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta2". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0808 21:07:48.612534   43948 common.go:84] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta2". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0808 21:07:48.618083   43948 utils.go:69] The recommended value for "clusterDNS" in "KubeletConfiguration" is: [10.233.0.10]; the provided value is: [169.254.25.10]
```
