### ISSUE TITLE
export offline artifactory, error: No SHA256 found for kubecni. v1.2.0 is not supported. 

### ISSUE THREAD

**Issue by uplogin** [kubesphere/kubekey#1970]
### What is version of KubeKey has the issue?

v3.0.7 and v3.0.10

### What is your os environment?

centos7

### KubeKey config file

```yaml
cat manifest-sample.yaml 

apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Manifest
metadata:
  name: sample
spec:
  arches:
  - amd64
  operatingSystems:
  - arch: amd64
    type: linux
    id: centos
    version: "7"
    osImage: CentOS Linux 7 (Core)
    repository:
      iso:
        localPath: 
        url:
  kubernetesDistributions:
  - type: kubernetes
    version: v1.24.7
  components:
    helm: 
      version: v3.9.0
    cni: 
      version: v1.2.0
    etcd: 
      version: v3.4.13
    containerRuntimes:
    - type: containerd
      version: 1.6.4
    crictl: 
      version: v1.24.0
    ## 
    # docker-registry:
    #   version: "2"
    # harbor:
    #   version: v2.4.1
    # docker-compose:
    #   version: v2.2.2
  images:
  - docker.io/calico/cni:v3.23.2
  - docker.io/calico/kube-controllers:v3.23.2
  - docker.io/calico/node:v3.23.2
  - docker.io/calico/pod2daemon-flexvol:v3.23.2
  - docker.io/coredns/coredns:1.8.6
  - docker.io/csiplugin/snapshot-controller:v4.0.0
  - docker.io/kubesphere/k8s-dns-node-cache:1.15.12
  - docker.io/kubesphere/ks-apiserver:v3.4.0
  - docker.io/kubesphere/ks-console:v3.4.0
  - docker.io/kubesphere/ks-controller-manager:v3.4.0
  - docker.io/kubesphere/ks-installer:v3.4.0
  - docker.io/kubesphere/kube-apiserver:v1.24.7
  - docker.io/kubesphere/kube-controller-manager:v1.24.7
  - docker.io/kubesphere/kube-proxy:v1.24.7
  - docker.io/kubesphere/kube-rbac-proxy:v0.11.0
  - docker.io/kubesphere/kube-scheduler:v1.24.7
  - docker.io/kubesphere/kube-state-metrics:v2.6.0
  - docker.io/kubesphere/kubectl:v1.22.0
  - docker.io/kubesphere/metrics-server:v0.4.2
  - docker.io/kubesphere/notification-manager-operator:v2.3.0
  - docker.io/kubesphere/notification-manager:v2.3.0
  - docker.io/kubesphere/notification-tenant-sidecar:v3.2.0
  - docker.io/kubesphere/pause:3.7
  - docker.io/kubesphere/prometheus-config-reloader:v0.55.1
  - docker.io/kubesphere/prometheus-operator:v0.55.1
  - docker.io/library/haproxy:2.3
  - docker.io/mirrorgooglecontainers/defaultbackend-amd64:1.4
  - docker.io/openebs/linux-utils:3.3.0
  - docker.io/openebs/provisioner-localpv:3.3.0
  - docker.io/prom/alertmanager:v0.23.0
  - docker.io/prom/node-exporter:v1.3.1
  - docker.io/prom/prometheus:v2.39.1
  registry:
    auths: {}
```

### A clear and concise description of what happend.

I setup a single node cluster with command ./kk create config --with-kubernetes v1.24.7 --with-kubesphere, and it worked.When I export the artifactory to offline package, it stoped with error.

11:05:21 CST message: [LocalHost]
Failed to download kubecni binary: curl -L -o /opt/kubernetes/kubekey/artifact/cni/v1.2.0/amd64/cni-plugins-linux-amd64-v1.2.0.tgz https://containernetworking.pek3b.qingstor.com/plugins/releases/download/v1.2.0/cni-plugins-linux-amd64-v1.2.0.tgz error: No SHA256 found for kubecni. v1.2.0 is not supported. 
11:05:21 CST failed: [LocalHost]
error: Pipeline[ArtifactExportPipeline] execute failed: Module[ArtifactBinariesModule] exec failed: 
failed: [LocalHost] [DownloadBinaries] exec failed after 1 retires: Failed to download kubecni binary: curl -L -o /opt/kubernetes/kubekey/artifact/cni/v1.2.0/amd64/cni-plugins-linux-amd64-v1.2.0.tgz https://containernetworking.pek3b.qingstor.com/plugins/releases/download/v1.2.0/cni-plugins-linux-amd64-v1.2.0.tgz error: No SHA256 found for kubecni. v1.2.0 is not supported. 

I have tried v3.0.7 and v3.0.10

### Relevant log output

```shell
11:05:21 CST message: [LocalHost]
Failed to download kubecni binary: curl -L -o /opt/kubernetes/kubekey/artifact/cni/v1.2.0/amd64/cni-plugins-linux-amd64-v1.2.0.tgz https://containernetworking.pek3b.qingstor.com/plugins/releases/download/v1.2.0/cni-plugins-linux-amd64-v1.2.0.tgz error: No SHA256 found for kubecni. v1.2.0 is not supported. 
11:05:21 CST failed: [LocalHost]
error: Pipeline[ArtifactExportPipeline] execute failed: Module[ArtifactBinariesModule] exec failed: 
failed: [LocalHost] [DownloadBinaries] exec failed after 1 retires: Failed to download kubecni binary: curl -L -o /opt/kubernetes/kubekey/artifact/cni/v1.2.0/amd64/cni-plugins-linux-amd64-v1.2.0.tgz https://containernetworking.pek3b.qingstor.com/plugins/releases/download/v1.2.0/cni-plugins-linux-amd64-v1.2.0.tgz error: No SHA256 found for kubecni. v1.2.0 is not supported.
```
