### ISSUE TITLE
ETCD environment is not configured in env when include in the cluster YAML config

### ISSUE THREAD

**Issue by antikilahdjs** [kubesphere/kubekey#1971]
### What is version of KubeKey has the issue?

kk version: &version.Info{Major:"3", Minor:"0", GitVersion:"v3.0.10", GitCommit:"3e381c6d5556117d132326b58c5177e0b0e839b6", GitTreeState:"clean", BuildDate:"2023-07-28T06:08:59Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### What is your os environment?

Redhat 8.5

### KubeKey config file

```yaml
etcd:
    # Specify the type of etcd used by the cluster. When the cluster type is k3s, setting this parameter to kubeadm is invalid. [kubekey | kubeadm | external] [Default: kubekey]
    type: kubekey
    ## The following parameters need to be added only when the type is set to external.
    ## caFile, certFile and keyFile need not be set, if TLS authentication is not enabled for the existing etcd.
    # external:
    #   endpoints:
    #     - https://192.168.6.6:2379
    #   caFile: /pki/etcd/ca.crt
    #   certFile: /pki/etcd/etcd.crt
    #   keyFile: /pki/etcd/etcd.key
    dataDir: "/var/lib/etcd"
    # Time (in milliseconds) of a heartbeat interval.
    heartbeatInterval: 250
    # Time (in milliseconds) for an election to timeout.
    electionTimeout: 5000
    # Number of committed transactions to trigger a snapshot to disk.
    snapshotCount: 10000
    # Auto compaction retention for mvcc key value store in hour. 0 means disable auto compaction.
    autoCompactionRetention: 8
    # Set level of detail for etcd exported metrics, specify 'extensive' to include histogram metrics.
    metrics: basic
    ## Etcd has a default of 2G for its space quota. If you put a value in etcd_memory_limit which is less than
    ## etcd_quota_backend_bytes, you may encounter out of memory terminations of the etcd cluster. Please check
    ## etcd documentation for more information.
    # 8G is a suggested maximum size for normal environments and etcd warns at startup if the configured value exceeds it.
    quotaBackendBytes: 4294967296
    # Maximum client request size in bytes the server will accept.
    # etcd is designed to handle small key value pairs typical for metadata.
    # Larger requests will work, but may increase the latency of other requests
    maxRequestBytes: 1572864
    # Maximum number of snapshot files to retain (0 is unlimited)
    maxSnapshots: 5
    # Maximum number of wal files to retain (0 is unlimited)
    maxWals: 5
    logLevel: info
    monitoring: true
    endpointIps: localhost
    port: 2379
    tlsEnable: true
```

### A clear and concise description of what happend.

In the YAML file to configure the cluster did not working as expected with the environment inside to etcd.env. 

As an example, I need to increase the Quota for ETCD but the kk is not fill the etcd.env correctly. In ,y config the value has been configured to  4294967296.

### Relevant log output

```shell
The pipeline works perfectly but in my env the quota is empty

13:16:24 -05 [ChownModule] Chown user $HOME/.kube dir
13:16:24 -05 success: [s04]
13:16:24 -05 success: [s01]
13:16:24 -05 success: [s08]
13:16:24 -05 Pipeline[AddNodesPipeline] execute successfully
```

### Additional information

      # Environment file for etcd v3.4.13
      ETCD_DATA_DIR=/var/lib/etcd
      ETCD_ADVERTISE_CLIENT_URLS=https://172.30.86.58:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS=https://172.30.86.58:2380
      ETCD_INITIAL_CLUSTER_STATE=existing
      ETCD_METRICS=basic
      ETCD_LISTEN_CLIENT_URLS=https://172.30.86.58:2379,https://127.0.0.1:2379
      ETCD_INITIAL_CLUSTER_TOKEN=k8s_etcd
      ETCD_LISTEN_PEER_URLS=https://172.30.86.58:2380
      ETCD_NAME=etcd-s01
      ETCD_PROXY=off
      ETCD_ENABLE_V2=true
      ETCD_INITIAL_CLUSTER=etcd-s01=https://172.30.86.58:2380,etcd-s04=https://172.30.86.61:2380,etcd-s08=https://172.30.86.67:2380,etcd-s02=https://172.30.86.59:2380,etcd-s03=https://172.30.86.60:2380
      ETCD_ELECTION_TIMEOUT=5000
      ETCD_HEARTBEAT_INTERVAL=250
      ETCD_AUTO_COMPACTION_RETENTION=8
      ETCD_SNAPSHOT_COUNT=10000
      
      # TLS settings
      ETCD_TRUSTED_CA_FILE=/etc/ssl/etcd/ssl/ca.pem
      ETCD_CERT_FILE=/etc/ssl/etcd/ssl/member-s01.pem
      ETCD_KEY_FILE=/etc/ssl/etcd/ssl/member-s01-key.pem
      ETCD_CLIENT_CERT_AUTH=true
      
      ETCD_PEER_TRUSTED_CA_FILE=/etc/ssl/etcd/ssl/ca.pem
      ETCD_PEER_CERT_FILE=/etc/ssl/etcd/ssl/member-s01.pem
      ETCD_PEER_KEY_FILE=/etc/ssl/etcd/ssl/member-s01-key.pem
      ETCD_PEER_CLIENT_CERT_AUTH=True
      
      # CLI settings
      ETCDCTL_ENDPOINTS=https://127.0.0.1:2379
      ETCDCTL_CA_FILE=/etc/ssl/etcd/ssl/ca.pem
      ETCDCTL_KEY_FILE=/etc/ssl/etcd/ssl/admin-s01-key.pem
      ETCDCTL_CERT_FILE=/etc/ssl/etcd/ssl/admin-s01.pem

I saw in the code this line https://github.com/kubesphere/kubekey/blob/ebfde7ce2320e985a6e02177ee7908ac1dc350f5/cmd/kk/pkg/etcd/templates/etcd_env.go#L66
