### ISSUE TITLE
Obtain kubeconfig after `kk create cluster`

### ISSUE THREAD

**Issue by siredmar** [kubesphere/kubekey#1997]
### What is version of KubeKey has the issue?

v3.0.10

### What is your os environment?

Ubuntu 22.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: core-cluser
spec:
  hosts:
    - name: dog-control-plane-1
      address: 172.104.xxx.xxx
      internalAddress: 192.168.128.174
      privateKeyPath: /credentials/sshPrivateKey
    - name: dog-control-plane-2
      address: 139.162.xxx.xxx
      internalAddress: 192.168.170.183
      privateKeyPath: /credentials/sshPrivateKey
    - name: dog-master
      address: 143.42.xxx.xxx
      internalAddress: 192.168.138.171
      privateKeyPath: /credentials/sshPrivateKey
  roleGroups:
    etcd:
      - dog-control-plane-1
      - dog-control-plane-2
      - dog-master
    control-plane: []
    workers: []
    master:
      - dog-control-plane-1
      - dog-control-plane-2
      - dog-master
  controlPlaneEndpoint:
    address: "139.144.xxx.xxx"
    domain: ""
    port: 6443
  kubernetes:
    version: v1.22.15
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: docker
    kubeProxyConfiguration:
      featureGates: # 1. enable EndpointSliceProxying feature gate.
        EndpointSliceProxying: true
      clientConnection:
        kubeconfig: ""
  etcd:
    type: kubekey
  network:
    plugin: flannel
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  addons: []
```

### A clear and concise description of what happend.

I created the cluster using `kk create cluster -f /tmp/kubekey.yaml -y` with the config file referenced.
After everything was done i'd expect that that there is a kubeconfig lying around somewhere to access the cluster. 
I can't seem to find a kubeconfig file or a command or parameter to make this happen. 

I thought it would be easy to create the kubeconfig, because the Cluster manifest has everything it needs. It has the control-plane loadbalancer IP and it has SSH access to the control-plane nodes to retrieve needed information.

Am i missing something? Anyway, i need to find a programmable way of obtaining a kubeconfig after the cluster was created.
