### ISSUE TITLE
kubectl top pod 只能获取master1几点pod信息，无法获取master2、node1节点pod信息

### ISSUE THREAD

**Issue by chaowang66** [kubesphere/kubekey#2012]
### What is version of KubeKey has the issue?

v3.0.2

### What is your os environment?

centos

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: Rpa_K8s_Cluster
spec:
  hosts:
  - {name: master1, address: 10.103.142.159, internalAddress: 10.103.142.159, user: root, password: "RPAprod@666"}
  - {name: master2, address: 10.103.142.163, internalAddress: 10.103.142.163, user: root, password: "RPAprod@666"}
  - {name: node1, address: 10.103.142.33, internalAddress: 10.103.142.33, user: root, password: "RPAprod@666"}
  roleGroups:
    etcd:
    - master1
    - master2
    - node1
    control-plane: 
    - master1
    - master2
    worker:
    - master1
    - master2
    - node1
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kuberpa.local
    address: ""
    port: 6443
  kubernetes:
    version: 1.20.4
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: docker
  etcd:
    type: kubekey
  network:
    plugin: flannel
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

kubectl top pod 只能获取master1几点pod信息，无法获取master2、node1节点pod信息
