### ISSUE TITLE
support for customizing plugins

### ISSUE THREAD

**Issue by pixiake** [kubesphere/kubekey#204]
I think KubeKey should provide a way to support the installation of custom plugins, such as some storage plugins.

I think it is possible to provide custom configurations in the config file.

```
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: example
spec:
  hosts:
  - {name: node1, address: 172.16.0.2, internalAddress: 172.16.0.2, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: node2, address: 172.16.0.3, internalAddress: 172.16.0.3, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: node3, address: 172.16.0.4, internalAddress: 172.16.0.4, privateKeyPath: "~/.ssh/id_rsa"}
  ...
  customPlugins:
  - name: qingcloud-csi
    repo: 
       name: test
       url: "https://charts.kubesphere.io/test"
    chart: csi-qingcloud
    values:
      config:
        qy_access_key_id: xxx
        qy_secret_access_key: xxx
      sc:
        defaultClass: true
  - name: ceph-csi
    repo:
      name: ceph-csi
      url: "https://ceph.github.io/csi-charts"
    chart: ceph-csi-rbd
    values:
      plugin:
        image:
          repository: 192.168.0.66:500/cephcsi/cephcsi
  - name: qingcloud-lb-plugin
    repo:
      name: test
      url: "https://charts.kubesphere.io/test"
    chart: lb-plugin-qingcloud
    values:
      zone: ap2a
      defaultVxNetForLB: vxnet-lddzg8e
```

**Comment by FeynmanZhou** [comment]
Looks much flexible than before, I agree with this way of customizing storage client configuration from my personal view.

**Comment by pixiake** [comment]
@rayzhou2017 @min-zh  I think using this approach solves the problem of integrating many storage or other plugins, and kubekey is completely decoupled from those plugins.

**Comment by rayzhou2017** [comment]
What does chart mean here? Is it the specific chart name from the repo? And you want to create a sc from the chart? Then Is the following better?
```
storageClass:
    name: xxxx
    default: true
```

```
 - name: qingcloud-csi
    repo: 
       name: test
       url: "https://charts.kubesphere.io/test"
    chart: csi-qingcloud
    values:
      config:
        qy_access_key_id: xxx
        qy_secret_access_key: xxx
      sc:
        defaultClass: true
```

**Comment by pixiake** [comment]
I think all custom plugins are deployed using Helm Chart，so define the following parameters in  `customPlugins` :
`name`:  the name of custom plugins
`repo`: charts' repo where the helm-chart of the plugin is located
`chart`:   the name of custom plugin‘s helm-chart
`value`:  parameters customized when installing the plugin

Custom plugins can be storage plugins or other types of plugins (lb, clould-provider ... ), which can be installed by helm chart .

So, I think the storage’s part of the configuration stays the same. When using a custom storage plugin as the default storage, only set the `defaultStorageClass` to `custom`

For example:

When user wants to use localvolume as the default storage, configure the following:
```
  storage:
    defaultStorageClass: localVolume
    localVolume:
      storageClassName: local
```
When user wants to use qingcloud-csi as the default storage, configure the following:
```
  storage:
    defaultStorageClass: custom
  customPlugins:
  - name: qingcloud-csi
    repo: 
      name: test
      url: "https://charts.kubesphere.io/test"
    chart: csi-qingcloud
    values:
      config:
        qy_access_key_id: xxx
        qy_secret_access_key: xxx
      sc:
        defaultClass: true
```

@rayzhou2017 @zheng1 @zryfish @min-zh @calvinyv  Is this OK ？

**Comment by calvinyv** [comment]
looks good for me.

**Comment by zheng1** [comment]
How about this way?
```yaml
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: example
spec:
  hosts:
  - {name: node1, address: 172.16.0.2, internalAddress: 172.16.0.2, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: node2, address: 172.16.0.3, internalAddress: 172.16.0.3, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: node3, address: 172.16.0.4, internalAddress: 172.16.0.4, privateKeyPath: "~/.ssh/id_rsa"}
  ...
---
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: HelmRepo
metadata:
  name: ceph-csi
spec:
  url: https://ceph.github.io/csi-charts
---
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: HelmRepo
metadata:
  name: kubesphere-test
spec:
  url: https://charts.kubesphere.io/test
---
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: HelmRelease
metadata:
  name: qingcloud-csi
  namespace: kube-system
spec:
  repo: kubesphere-test
  chart: csi-qingcloud
  version: 1.2.2
  values:
    config:
      qy_access_key_id: xxx
      qy_secret_access_key: xxx
    sc:
      defaultClass: true
---
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: HelmRelease
metadata:
  name: qingcloud-loadbalancer
  namespace: kube-system
spec:
  repo: kubesphere-test
  chart: lb-plugin-qingcloud
  version: 1.3.0
  values:
    zone: ap2a
    defaultVxNetForLB: vxnet-lddzg8e
---
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: HelmRelease
metadata:
  name: cephfs-csi
  namespace: kube-system
spec:
  repo: ceph-csi
  chart: ceph-csi-cephfs
  version: 3.1.0
  values:
    plugin:
      image:
        repository: 192.168.0.66:500/cephcsi/cephcsi
```

**Comment by zheng1** [comment]
customPlugins sounds like kubekey plugins, but in fact, it is just a definition of helm release

**Comment by pixiake** [comment]
@zheng1 Yes, It seems good. But I think it's better to use a contoller to provide this functionality after the cluster is deployed，and this method may complicate configuration files before cluster is deployed.

**Comment by rayzhou2017** [comment]
Shall we put it in 3.1.0?

**Comment by pixiake** [comment]
I think it should be in 3.0.0，because many of the plugins are chart, it may affect the installation in offline environments if this is not provided. such as `nfs-client`, `ceph-csi` , these chats are not accessible in an offline environment.

**Comment by pixiake** [comment]
I think all plugins can be kubernetes' addons (Including kubesphere), these plugins can be deploy by `yaml` or `chart`.

So the custom plugins configuration should support both yaml and chart.

Explanation of parameters:

```
- name: xxx                  # the name of addon
  namespace: xxx             # namepace
  source:                    # support both yaml and chart
    chart:                          
      name: xxx              # the name of chart
      repo:  xxx             # the name of chart repo (url)
      path: xxx              # the location of chart  (path)
      values:  xxx           # specify values for chart (url / path / string)
    yaml: 
      path:                  # the location of yaml (path / url) 
```
example:
```
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: example
spec:
  hosts:
  - {name: node1, address: 172.16.0.2, internalAddress: 172.16.0.2, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: node2, address: 172.16.0.3, internalAddress: 172.16.0.3, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: node3, address: 172.16.0.4, internalAddress: 172.16.0.4, privateKeyPath: "~/.ssh/id_rsa"}
  ...
  addons:
  - name: glusterfs
    namespace: kube-system
    source: 
      yaml: 
        path: /mycluster/glusterfs/glusterfs.yaml
  
  - name: qingcloud-csi
    namespace: kube-system
    source:
      chart: 
        name: qingcloud-csi
        repo: https://charts.kubesphere.io/main
        values: |
          config:
            qy_access_key_id: xxx
            qy_secret_access_key: xxx
          sc:
            defaultClass: true

  - name: nfs-client
    namespace: kube-system
    source: 
      chart: 
        name: nfs-client-provisioner
        path: /mycluster/nfs
        values: /mycluster/nfs/custom-nfs-client-values.yaml

  - name: ceph-csi
    namespace: kube-system
    source: 
      chart: 
        name: ceph-csi
        repo: https://charts.kubesphere.io/main
        values: |
          plugin:
            image:
              repository: 192.168.0.66:500/cephcsi/cephcsi
      yaml: 
        path: /mycluster/ceph/ceph-rbd-sc.yaml
```

**Comment by rayzhou2017** [comment]
How to make KubeSphere as plugin in the example?

**Comment by pixiake** [comment]
@rayzhou2017 
```
- name: kubesphere
  source: 
    yaml: 
      path: /mycluster/kubesphere/kubesphere-minimal.yaml

```
or
```
- name: kubesphere
  source: 
    yaml: 
      path: https://raw.githubusercontent.com/kubesphere/ks-installer/master/kubesphere-minimal.yaml
```
