### ISSUE TITLE
国产化统信UOS，单集群安装kubesphere能成功，但后续add nodes或最开始使用多节点方式安装，都报错execute task timeout

### ISSUE THREAD

**Issue by DraPure** [kubesphere/kubekey#2066]
### What is version of KubeKey has the issue?

v3.0.7

### What is your os environment?

统信UOS 20

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts: 
  ##You should complete the ssh information of the hosts
  - {name: master, address: 192.168.199.181, internalAddress: 192.168.199.181, user: uos, password: "uos123456", timeout: 120}
  - {name: node1, address: 192.168.199.27, internalAddress: 192.168.199.27, user: uos, password: "uos123456", timeout: 120}
  roleGroups:
    etcd:
    - master
    master:
    - master
    worker:
    - master
    - node1
  controlPlaneEndpoint:
    ##Internal loadbalancer for apiservers
    #internalLoadbalancer: haproxy

    ##If the external loadbalancer was used, 'address' should be set to loadbalancer's ip.
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.22.12
    clusterName: cluster.local
    proxyMode: ipvs
    masqueradeAll: false
    maxPods: 110
    nodeCidrMaskSize: 24
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    privateRegistry: ""
```

### A clear and concise description of what happend.

使用kk单集群安装kubesphere成功，但后续add nodes或者最开始使用多节点安装，都报错execute task timeout

### Relevant log output

```shell
./kk add nodes -f sample.yaml


 _   __      _          _   __           
| | / /     | |        | | / /           
| |/ / _   _| |__   ___| |/ /  ___ _   _ 
|    \| | | | '_ \ / _ \    \ / _ \ | | |
| |\  \ |_| | |_) |  __/ |\  \  __/ |_| |
\_| \_/\__,_|_.__/ \___\_| \_/\___|\__, |
                                    __/ |
                                   |___/

09:21:55 CST [GreetingsModule] Greetings
09:25:55 CST failed: [node1]
09:25:55 CST failed: [master]
error: Pipeline[AddNodesPipeline] execute failed: Module[GreetingsModule] exec failed: 
failed: [node1] execute task timeout, Timeout=4m
failed: [master] execute task timeout, Timeout=4m
```

### Additional information

看之前的issue应该是ssh问题，尝试过免密登录yml配置privateKeyPath: "~/.ssh/id_rsa"，会报错：
09:33:24 CST [GreetingsModule] Greetings
09:33:24 CST failed: [master]
09:33:24 CST failed: [node1]
error: Pipeline[AddNodesPipeline] execute failed: Module[GreetingsModule] exec failed: 
failed: [master] failed to connect to 192.168.199.181: could not establish connection to 192.168.199.181:22: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
failed: [node1] failed to connect to 192.168.199.27: could not establish connection to 192.168.199.27:22: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

也设置了timeout，只是增加了等待时间，到了时间还是报错execute task timeout。

看到有说“kk 会自动输入 sudo 密码，这个看起来是因为操作系统是中文，没有匹配到输入密码的关键字。”这个原因的，但因为使用国产化统信UOS，即使设置了系统英文，su提示还是中文的“请输入密码”，不知道有什么好的解决办法。
