### ISSUE TITLE
使用插件 cilium 升级版本的生成现有集群配置文件失败

### ISSUE THREAD

**Issue by wqwangwei** [kubesphere/kubekey#2071]
### What is version of KubeKey has the issue?

v3.0.13

### What is your os environment?

Ubuntu 22.04

### KubeKey config file

```yaml
kubernetes:
    version: v1.24.14
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
    disableKubeProxy: true   # 禁用 kube-proxy 组件,用 cilium 替换 
  network:
    plugin: cilium      # calico 都有
```

### A clear and concise description of what happend.

应该是禁用 kube-proxy 组件问题。

### Relevant log output

```shell
error: configmaps "kube-proxy" not found
```
