### ISSUE TITLE
pull time error: PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"registry.cn-beijing.aliyuncs.com/kubesphereio/cilium:v1.11.7\

### ISSUE THREAD

**Issue by Shuimo03** [kubesphere/kubekey#2106]
### What is version of KubeKey has the issue?

kk version: &version.Info{Major:"3", Minor:"0", GitVersion:"v3.0.12", GitCommit:"b2f957f81b011db13024128efae942a7e9cdfdeb", GitTreeState:"clean", BuildDate:"2023-10-23T10:08:34Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### What is your os environment?

centos8

### KubeKey config file

```yaml
kubernetes:
    version: v1.23.0
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: cilium
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

 crictl pull registry.cn-beijing.aliyuncs.com/kubesphereio/cilium:v1.11.7 --platform amd64

registry.cn-beijing.aliyuncs.com/kubesphereio/cilium:v1.11.7 --platform amd64

![image](https://github.com/kubesphere/kubekey/assets/22347407/64a85201-b9f2-41aa-aaa4-ff764c11f574)
