### ISSUE TITLE
non root user with password-less ssh installation 

### ISSUE THREAD

**Issue by li-wu** [kubesphere/kubekey#2109]
### Your current KubeKey version

1.1.1

### Describe this feature

Does `kubekey` support installation with non-root user and password-less installation? 

Example config:
```
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: config-standalone
spec:
  hosts:
  - {name: node1, address: 172.16.11.1, internalAddress: 172.16.11.1, user: abc, privateKeyPath: "/home/abc/.ssh/id_ed25519"}
  roleGroups:
    etcd:
    - node1
    master:
    - node1
    worker:
    - node1
  controlPlaneEndpoint:
    domain: node1
    address: ""
    port: 6443
  kubernetes:
    version: v1.19.9
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: ["localhost:5001"]
    privateRegistry: localhost:5001
  addons: []
```

### Describe the solution you'd like

I would like to have password-less and non-root user support with `kubekey`.

### Additional information

OS: RHEL 7.X and 8.X.
