### ISSUE TITLE
local iso not being referenced 

### ISSUE THREAD

**Issue by lbrigman124** [kubesphere/kubekey#2141]
### What is version of KubeKey has the issue?

3.1.0-alpha.7

### What is your os environment?

Rocky 9

### KubeKey config file

```yaml
Sub section of the config:
  arches:
  - amd64
  operatingSystems:
  - arch: amd64
    type: linux
    id: rocky
    version: "9"
    osImage: Rocky Linux release 9.2 (Blue Onyx)
    repository:
      iso:
        localPath: rockylinux-9-amd64-rpms.iso
```

### A clear and concise description of what happend.

When the above section of the kubekey config file is set. The actual file that is being referenced is:
......./kubekey/repository/amd64/rocky/9.3/rocky-9.3-amd64.iso
Path prefix is based on the directory where kk is being run from.

### Relevant log output

```shell
failed: [sample.lab.local] [SyncRepositoryISOFile] exec failed after 2 retries: scp /home/XXXX/kubekey/repository/amd64/rocky/9.3/rocky-9.3-amd64.iso to /tmp/kubekey/rocky-9.3-amd64.iso failed: get file stat failed: stat /home/XXXX/kubekey/repository/amd64/rocky/9.3/rocky-9.3-amd64.iso: no such file or directory
+ exit 1
```

### Additional information

If the directory referenced above is created and the iso is copied to that location.
The process works.

Secondary issue: if the version is not a quoted string the ISO process is not used and no output about it is in the logs.

**Comment by lbrigman124** [comment]
The location being referenced may be due to using kk init os with the -a artifact.tgz
However, the artifact file didn't have any ISO images within it.

**Comment by will4j** [comment]
if you use kk init os with the -a artifact.tgz, which means expecting install os packages from iso file, and the artifact.tgz should have specific iso files in it.

In other words, config
```yaml
repository:
  iso:
    localPath: rockylinux-9-amd64-rpms.iso
```
is used when running command `kk artifact export`, not for command `kk init os`
