### ISSUE TITLE
bug after "update cri-dockerd support"

### ISSUE THREAD

**Issue by andrewfung729** [kubesphere/kubekey#2149]
### What is version of KubeKey has the issue?

v3.1.0-alpha

### What is your os environment?

Ubuntu 22.04

### KubeKey config file

```yaml
kubernetes:
    version: v1.26.13
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
    masqueradeAll: false
    maxPods: 110
    nodeCidrMaskSize: 24
    proxyMode: ipvs
```

### A clear and concise description of what happend.

I tried to build a KubeKey by myself. when I started deploying a cluster by running kk with the above config (containerManager: containerd), it triggered cri-dockerd errors. I don't think this should happen.

I have never write go code before. But I found that if I add the following skip function, it can skip the exception.

```go
// kubekey/cmd/kk/pkg/container/module.go
func (p *InstallCriDockerdModule) IsSkip() bool {
	return p.Skip
}
```

### Relevant log output

```shell
get KubeBinary key cri-dockerd by pipeline cache failed
sync cri-dockerd binaries failed
```
