### ISSUE TITLE
v3.1.0-rc1部署完集群没有存储

### ISSUE THREAD

**Issue by Forevery1** [kubesphere/kubekey#2175]
### What is version of KubeKey has the issue?

v3.1.0-rc1

### What is your os environment?

centos 8

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: k8s-master, address: 192.168.40.3, internalAddress: 192.168.40.3, user: root, password: "123456"}
  - {name: k8s-node1, address: 192.168.40.4, internalAddress: 192.168.40.4, user: root, password: "123456"}
  - {name: k8s-node2, address: 192.168.40.5, internalAddress: 192.168.40.5, user: root, password: "123456"}
  roleGroups:
    etcd:
    - k8s-master
    control-plane: 
    - k8s-master
    worker:
    - k8s-node1
    - k8s-node2
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.26.13
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

<img width="903" alt="image" src="https://github.com/kubesphere/kubekey/assets/19872771/6d63f1db-2e34-4526-af69-0f67e4626fe3">

### Relevant log output

```shell
[root@k8s-master ~]# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.13", GitCommit:"7ba444e261616cb572b2c9e3aa6ee8876140f46a", GitTreeState:"clean", BuildDate:"2024-01-17T13:45:13Z", GoVersion:"go1.20.13", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.13", GitCommit:"7ba444e261616cb572b2c9e3aa6ee8876140f46a", GitTreeState:"clean", BuildDate:"2024-01-17T13:37:06Z", GoVersion:"go1.20.13", Compiler:"gc", Platform:"linux/amd64"}
[root@k8s-master ~]# kubectl get sc
No resources found
[root@k8s-master ~]#
```
