### ISSUE TITLE
offline deploy , miss containerd and runc

### ISSUE THREAD

**Issue by zmoon460** [kubesphere/kubekey#2186]
### What is version of KubeKey has the issue?

 kk version: &version.Info{Major:"3", Minor:"1", GitVersion:"v3.1.0-rc.1", GitCommit:"9cd0db0eef876201c6deaaec4a1cb962787b70f6", GitTreeState:"clean", BuildDate:"2024-03-15T07:29:19Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### What is your os environment?

centos 7.9

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Manifest
metadata:
  name: appcluster 
spec:
  arches:
  - amd64
  operatingSystems:
  - arch: amd64
    type: linux
    id: centos
    version: "7"
    osImage: CentOS Linux 7 (Core)
    repository:
      iso:
        localPath: 
        url:  
  kubernetesDistributions:
  - type: kubernetes
    version: v1.26.13
  components:
    helm: 
      version: v3.13.3
    cni: 
      version: v1.2.0
    etcd: 
      version: v3.5.6
    containerRuntimes:
    - type: containerd
      version: 1.7.13
    crictl: 
      version: v1.29.0
    calicoctl:
      version: v3.27.2
    docker-registry:
      version: "2"
    harbor:
      version: v2.5.3
    docker-compose:
      version: v2.2.2
  images:
  - registry.cn-beijing.aliyuncs.com/kubesphereio/cni:v3.27.2
  - registry.cn-beijing.aliyuncs.com/kubesphereio/coredns:1.9.3
  - registry.cn-beijing.aliyuncs.com/kubesphereio/haproxy:2.3
  - registry.cn-beijing.aliyuncs.com/kubesphereio/k8s-dns-node-cache:1.22.20
  - registry.cn-beijing.aliyuncs.com/kubesphereio/kube-apiserver:v1.26.13
  - registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controller-manager:v1.26.13
  - registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controllers:v3.27.2
  - registry.cn-beijing.aliyuncs.com/kubesphereio/kube-proxy:v1.26.13
  - registry.cn-beijing.aliyuncs.com/kubesphereio/kube-scheduler:v1.26.13
  - registry.cn-beijing.aliyuncs.com/kubesphereio/node:v3.27.2
  - registry.cn-beijing.aliyuncs.com/kubesphereio/pause:3.8
  - registry.cn-beijing.aliyuncs.com/kubesphereio/pause:3.9
  - registry.cn-beijing.aliyuncs.com/kubesphereio/pod2daemon-flexvol:v3.27.2
  - registry.cn-hangzhou.aliyuncs.com/google_containers/metrics-server:v0.6.4
  registry:
    auths: {}
```

### A clear and concise description of what happend.

use kk v3.1.0.rc1  make  offline install artifact   ;   During offline installation process miss containerd 1.7.13  and runc 1.1.12  program always，resulting in downloading these two programs online every time , try add  

`    containerd: 
      version: 1.7.13
    runc:
      version: 1.1.12`

no help

The files in the kubekey directory exist, but it seems that the process of packaging artifacts was missed

# ls -lR | grep runc
drwxr-xr-x 3 root root 21 Mar 27 18:33 runc
./runc:
./runc/v1.1.12:
./runc/v1.1.12/amd64:
-rw-r--r-- 1 root root 10709696 Mar 27 18:33 runc.amd64

# ls -lR | grep containerd
drwxr-xr-x 3 root root 20 Mar 27 18:32 containerd
./containerd:
./containerd/1.7.13:
./containerd/1.7.13/amd64:
-rw-r--r-- 1 root root 47970232 Mar 27 18:33 containerd-1.7.13-linux-amd64.tar.gz

### Relevant log output

```shell
18:34:05 CST message: [localhost]
downloading amd64 containerd 1.7.13 ...
18:34:05 CST message: [localhost]
containerd exists
18:34:05 CST message: [localhost]
downloading amd64 runc v1.1.12 ...
18:34:05 CST message: [localhost]
runc exists
```
