### ISSUE TITLE
生成的配置，为什么还有4个缩进呢，要么就统一，还有安装 1.26.5 kubelet 起不来

### ISSUE THREAD

**Issue by ygqygq2** [kubesphere/kubekey#2225]
### What is version of KubeKey has the issue?

3.1.1

### What is your os environment?

Ubuntu 22.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: vdi-k8s
spec:
  hosts:
    - {name: master1, address: 10.xxx, internalAddress: 10.xxx, user: root, privateKeyPath: "~/.ssh/id_ed25519"}
    - {name: master2, address: 10.xxx, internalAddress: 10.xxx, user: root, privateKeyPath: "~/.ssh/id_ed25519"}
    - {name: master3, address: 10.xxx, internalAddress: 10.xxx, user: root, privateKeyPath: "~/.ssh/id_ed25519"}
    - {name: node4, address: 10.xxx, internalAddress: 10.xxx, user: root, privateKeyPath: "~/.ssh/id_ed25519"}
  roleGroups:
    etcd:
    - master1
    - master2
    - master3
    control-plane: 
    - master1
    - master2
    - master3
    worker:
    - node4
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.26.5
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

1. yaml 还是4个空格缩进的。
2. kubelet 启不来，没有配置 runtime socket 路径，读不到 containerd socket路径。
```yaml
scheduler:
  extraArgs:
    bind-address: 0.0.0.0
    feature-gates: RotateKubeletServerCertificate=true

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.111.3.53
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    cgroup-driver: cgroupfs
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
clusterCIDR: 10.233.64.0/18
iptables:
    masqueradeAll: false
    masqueradeBit: 14
    minSyncPeriod: 0s
    syncPeriod: 30s
mode: ipvs
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
clusterDNS:
    - 169.254.25.10
clusterDomain: cluster.local
containerLogMaxFiles: 3
containerLogMaxSize: 5Mi
evictionHard:
    memory.available: 5%
    pid.available: 10%
evictionMaxPodGracePeriod: 120
evictionPressureTransitionPeriod: 30s
evictionSoft:
    memory.available: 10%
evictionSoftGracePeriod:
    memory.available: 2m
featureGates:
    RotateKubeletServerCertificate: true
kubeReserved:
    cpu: 200m
    memory: 250Mi
maxPods: 110
podPidsLimit: 10000
rotateCertificates: true
systemReserved:
    cpu: 200m
    memory: 250Mi
```

报错： the container runtime endpoint address was not specified or empty, use --container-runtime-endpoint to set"
