### ISSUE TITLE
kk supports mirror warehouse configuration, not just for dockerhub warehouse

### ISSUE THREAD

**Issue by snail2sky** [kubesphere/kubekey#2296]
### Your current KubeKey version

kk version: &version.Info{Major:"3", Minor:"1", GitVersion:"v3.1.1", GitCommit:"7a184f786b02bec20d5534af137896f50e510396", GitTreeState:"clean", BuildDate:"2024-04-16T04:28:43Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### Describe this feature

Currently kk can create a mirror for the dockerhub image when initializing the cluster. After the creation is completed, it is found that the mirror has indeed been added to the containerd configuration file, but it seems that it cannot add mirrors for other mirror sites, such as quay.io and other public site

### Describe the solution you'd like

```yaml
registry:
  registryMirrors:
    hub.docker.com:
    - docker.mirror-demo.com
    - docker.mirror-demo1.com
    - docker.mirror-demo2.com
    quay.io:
    - quay.mirror-demo.com
    - quay.mirror-demo1.com
```

### Additional information

In this case, you can directly configure the image and other things during initialization. KK has done a very good job, and I hope it can do better.
