### ISSUE TITLE
v1.28.3 image cannot pull 

### ISSUE THREAD

**Issue by lkad** [kubesphere/kubekey#2377]
### What is version of KubeKey has the issue?

kk version: &version.Info{Major:"3", Minor:"1", GitVersion:"v3.1.5", GitCommit:"8347277057bf9f84e89fec174019a675d582b23b", GitTreeState:"clean", BuildDate:"2024-08-15T11:55:51Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### What is your os environment?

ubuntu 20.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: 10.204.53.155, internalAddress: 10.204.53.155, user: root}
  - {name: node2, address: 10.204.53.156, internalAddress: 10.204.53.156, user: root}
  - {name: node3, address: 10.204.53.157, internalAddress: 10.204.53.157, user: root}
  - {name: node4, address: 10.204.53.158, internalAddress: 10.204.53.158, user: root}
  roleGroups:
    etcd:
    - node1
    control-plane:
    - node1
    worker:
    - node1
    - node2
    - node3
    - node4
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: 1.28.3
    clusterName: cluster.localtest
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 192.168.64.0/18
    kubeServiceCIDR: 192.168.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

the readme doc wirte supoort v1.28.3,but image can not pull

### Relevant log output

```shell
failed to pull image registry.cn-beijing.aliyuncs.com/kubesphereio/kube-apiserver:v1.28.3
[WARNING ImagePull]: failed to pull image registry.cn-beijing.aliyuncs.com/kubesphereio/kube-proxy:v1.28.3
 [WARNING ImagePull]: failed to pull image registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controller-manager:v1.28.3
[WARNING ImagePull]: failed to pull image registry.cn-beijing.aliyuncs.com/kubesphereio/kube-scheduler:v1.28.3:
```
