### ISSUE TITLE
sample.yaml 文件获取不到 etcd

### ISSUE THREAD

**Issue by zlianzhuang** [kubesphere/kubekey#2379]
### What is version of KubeKey has the issue?

v3.0.13

### What is your os environment?

ubuntu 22.04

### KubeKey config file

```yaml
roleGroups:
    etcd:
    - SHOULD_BE_REPLACED
```

### A clear and concise description of what happend.

每次获取 sample.yaml 的时候，etcd 都是 should_be_replaced ，即使已经设置了，下一次获取sample.yaml的时候 还是这个
