### ISSUE TITLE
scp etcd certs file failed: Failed to exec command: sudo -E /bin/bash -c "mv -f /tmp/kubekey/etc/ssl/etcd/ssl/ca.pem /etc/ssl/etcd/ssl/ca.pem" 

### ISSUE THREAD

**Issue by web3creator** [kubesphere/kubekey#2384]
### What is version of KubeKey has the issue?

3.1.5

### What is your os environment?

ubuntu22.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master1, address: 10.50.0.242, internalAddress: 10.50.0.242,user: root,password: M}
  - {name: master2, address: 10.50.0.243, internalAddress: 10.50.0.243,user: root,password: T=&M}
  - {name: master3, address: 10.50.0.244, internalAddress: 10.50.0.244,user: root,password: Tu=&M}
  roleGroups:
    etcd:
    - master1
    - master1
    - master1
    control-plane:
    - master1
    - master2
    - master3
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.26.5
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: [10.50.0.240]
  addons: []



---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.4.1
spec:
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  local_registry: ""
  # dev_tag: ""
  etcd:
    monitoring: false
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    # apiserver:
    #  resources: {}
    # controllerManager:
    #  resources: {}
    redis:
      enabled: false
      enableHA: false
      volumeSize: 2Gi
    openldap:
      enabled: false
      volumeSize: 2Gi
    minio:
      volumeSize: 20Gi
    monitoring:
      # type: external
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      GPUMonitoring:
        enabled: false
    gpu:
      kinds:
      - resourceName: "nvidia.com/gpu"
        resourceType: "GPU"
        default: true
    es:
      # master:
      #   volumeSize: 4Gi
      #   replicas: 1
      #   resources: {}
      # data:
      #   volumeSize: 20Gi
      #   replicas: 1
      #   resources: {}
      enabled: false
      logMaxAge: 7
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchHost: ""
      externalElasticsearchPort: ""
    opensearch:
      # master:
      #   volumeSize: 4Gi
      #   replicas: 1
      #   resources: {}
      # data:
      #   volumeSize: 20Gi
      #   replicas: 1
      #   resources: {}
      enabled: true
      logMaxAge: 7
      opensearchPrefix: whizard
      basicAuth:
        enabled: true
        username: "admin"
        password: "admin"
      externalOpensearchHost: ""
      externalOpensearchPort: ""
      dashboard:
        enabled: false
  alerting:
    enabled: false
    # thanosruler:
    #   replicas: 1
    #   resources: {}
  auditing:
    enabled: false
    # operator:
    #   resources: {}
    # webhook:
    #   resources: {}
  devops:
    enabled: false
    jenkinsCpuReq: 0.5
    jenkinsCpuLim: 1
    jenkinsMemoryReq: 4Gi
    jenkinsMemoryLim: 4Gi
    jenkinsVolumeSize: 16Gi
  events:
    enabled: false
    # operator:
    #   resources: {}
    # exporter:
    #   resources: {}
    ruler:
      enabled: true
      replicas: 2
    #   resources: {}
  logging:
    enabled: false
    logsidecar:
      enabled: true
      replicas: 2
      # resources: {}
  metrics_server:
    enabled: false
  monitoring:
    storageClass: ""
    node_exporter:
      port: 9100
      # resources: {}
    # kube_rbac_proxy:
    #   resources: {}
    # kube_state_metrics:
    #   resources: {}
    # prometheus:
    #   replicas: 1
    #   volumeSize: 20Gi
    #   resources: {}
    #   operator:
    #     resources: {}
    # alertmanager:
    #   replicas: 1
    #   resources: {}
    # notification_manager:
    #   resources: {}
    #   operator:
    #     resources: {}
    #   proxy:
    #     resources: {}
    gpu:
      nvidia_dcgm_exporter:
        enabled: false
        # resources: {}
  multicluster:
    clusterRole: none
  network:
    networkpolicy:
      enabled: false
    ippool:
      type: none
    topology:
      type: none
  openpitrix:
    store:
      enabled: false
  servicemesh:
    enabled: false
    istio:
      components:
        ingressGateways:
        - name: istio-ingressgateway
          enabled: false
        cni:
          enabled: false
  edgeruntime:
    enabled: false
    kubeedge:
      enabled: false
      cloudCore:
        cloudHub:
          advertiseAddress:
            - ""
        service:
          cloudhubNodePort: "30000"
          cloudhubQuicNodePort: "30001"
          cloudhubHttpsNodePort: "30002"
          cloudstreamNodePort: "30003"
          tunnelNodePort: "30004"
        # resources: {}
        # hostNetWork: false
      iptables-manager:
        enabled: true
        mode: "external"
        # resources: {}
      # edgeService:
      #   resources: {}
  gatekeeper:
    enabled: false
    # controller_manager:
    #   resources: {}
    # audit:
    #   resources: {}
  terminal:
    timeout: 600
  zone: ""
```

### A clear and concise description of what happend.

12:26:01 CST success: [master1]
12:26:01 CST [CertsModule] Generate etcd Certs
[certs] Generating "ca" certificate and key
[certs] admin-master1 serving cert is signed for DNS names [etcd etcd.kube-system etcd.kube-system.svc etcd.kube-system.svc.cluster.local lb.kubesphere.local localhost master1 master2 master3 worker10001-RTX-4080-SUPER-32760] and IPs [127.0.0.1 ::1 10.50.0.242 10.50.0.243 10.50.0.244 10.50.0.11]
[certs] member-master1 serving cert is signed for DNS names [etcd etcd.kube-system etcd.kube-system.svc etcd.kube-system.svc.cluster.local lb.kubesphere.local localhost master1 master2 master3 worker10001-RTX-4080-SUPER-32760] and IPs [127.0.0.1 ::1 10.50.0.242 10.50.0.243 10.50.0.244 10.50.0.11]
[certs] node-master1 serving cert is signed for DNS names [etcd etcd.kube-system etcd.kube-system.svc etcd.kube-system.svc.cluster.local lb.kubesphere.local localhost master1 master2 master3 worker10001-RTX-4080-SUPER-32760] and IPs [127.0.0.1 ::1 10.50.0.242 10.50.0.243 10.50.0.244 10.50.0.11]
[certs] node-master2 serving cert is signed for DNS names [etcd etcd.kube-system etcd.kube-system.svc etcd.kube-system.svc.cluster.local lb.kubesphere.local localhost master1 master2 master3 worker10001-RTX-4080-SUPER-32760] and IPs [127.0.0.1 ::1 10.50.0.242 10.50.0.243 10.50.0.244 10.50.0.11]
[certs] node-master3 serving cert is signed for DNS names [etcd etcd.kube-system etcd.kube-system.svc etcd.kube-system.svc.cluster.local lb.kubesphere.local localhost master1 master2 master3 worker10001-RTX-4080-SUPER-32760] and IPs [127.0.0.1 ::1 10.50.0.242 10.50.0.243 10.50.0.244 10.50.0.11]
12:26:03 CST success: [LocalHost]
12:26:03 CST [CertsModule] Synchronize certs file
12:26:03 CST message: [master1]
scp etcd certs file failed: Failed to exec command: sudo -E /bin/bash -c "mv -f /tmp/kubekey/etc/ssl/etcd/ssl/ca.pem /etc/ssl/etcd/ssl/ca.pem" 
mv: cannot stat '/tmp/kubekey/etc/ssl/etcd/ssl/ca.pem': No such file or directory: Process exited with status 1
12:26:03 CST message: [master1]
scp etcd certs file failed: Failed to exec command: sudo -E /bin/bash -c "mv -f /tmp/kubekey/etc/ssl/etcd/ssl/ca.pem /etc/ssl/etcd/ssl/ca.pem" 
mv: cannot stat '/tmp/kubekey/etc/ssl/etcd/ssl/ca.pem': No such file or directory: Process exited with status 1
12:26:03 CST failed: [master1]
12:26:03 CST failed: [master1]
12:26:03 CST success: [master1]
error: Pipeline[CreateClusterPipeline] execute failed: Module[CertsModule] exec failed: 
failed: [master1] [SyncCertsFile] exec failed after 1 retries: scp etcd certs file failed: Failed to exec command: sudo -E /bin/bash -c "mv -f /tmp/kubekey/etc/ssl/etcd/ssl/ca.pem /etc/ssl/etcd/ssl/ca.pem" 
mv: cannot stat '/tmp/kubekey/etc/ssl/etcd/ssl/ca.pem': No such file or directory: Process exited with status 1
failed: [master1] [SyncCertsFile] exec failed after 1 retries: scp etcd certs file failed: Failed to exec command: sudo -E /bin/bash -c "mv -f /tmp/kubekey/etc/ssl/etcd/ssl/ca.pem /etc/ssl/etcd/ssl/ca.pem" 
mv: cannot stat '/tmp/kubekey/etc/ssl/etcd/ssl/ca.pem': No such file or directory: Process exited with status 1

### Relevant log output

```shell
.
```

### Additional information

.
