### ISSUE TITLE
pull images failed

### ISSUE THREAD

**Issue by jiangxuhui** [kubesphere/kubekey#2434]
### What is version of KubeKey has the issue?

v3.1.6

### What is your os environment?

ubuntu 18.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master, address: 192.168.228.130, internalAddress: 192.168.228.130, user: root, password: "123456"}
  roleGroups:
    etcd:
    - master
    control-plane: 
    - master
    worker:
    - master
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.27.4
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

I have download images by myself and tag images a new name.
```
crictl images ls 
```
![image](https://github.com/user-attachments/assets/b06b27a8-b443-4268-833e-8248f6603072)

but it still not work.
```
journalctl -xe -f 
```
```
Oct 24 07:37:36 master containerd[38557]: time="2024-10-24T07:37:36.816606943Z" level=error msg="CreateContainer within sandbox \"3a1a819c132a8bddf9d4f725ff00501f5042069443f8d4d8c20134da9eaacf2a\" for &ContainerMetadata{Name:kube-controller-manager,Attempt:0,} failed" error="rpc error: code = NotFound desc = failed to get image from containerd \"sha256:f466468864b7a960b22d9bc40e713c0dfc86d4544b1d1460ea6f120f13f286a5\": image \"docker.io/kubesphere/kube-controller-manager:v1.27.4\": not found"
```
![image](https://github.com/user-attachments/assets/399db160-e33c-4235-b3f6-d3fe178182e6)
