### ISSUE TITLE
feature for custom registry and images of kubernetes components - api, kubelet and etc.

### ISSUE THREAD

**Issue by Nello-Angelo** [kubesphere/kubekey#2468]
### Describe this feature

feature for custom registry and images of kubernetes components - api, kubelet and etc.

can i setup another regisry ?

```
  registry:
    registryMirrors: []  <--------- HERE??? if yes can you update docs because it's not obvious
    insecureRegistries: []
    privateRegistry: "dockerhub.kubekey.local"
    namespaceOverride: ""
    auths: # if docker add by `docker login`, if containerd append to `/etc/containerd/config.toml`
      "dockerhub.kubekey.local":
        username: "xxx"
        password: "***"
        skipTLSVerify: false # Allow contacting registries over HTTPS with failed TLS verification.
        plainHTTP: false # Allow contacting registries over HTTP.
        certsPath: "/etc/docker/certs.d/dockerhub.kubekey.local"
```

### Describe the solution you'd like

feature for custom registry and images of kubernetes components - api, kubelet and etc.

can i setup another regisry ?

```
  registry:
    registryMirrors: []  <--------- HERE??? if yes can you update docs because it's not obvious
    insecureRegistries: []
    privateRegistry: "dockerhub.kubekey.local"
    namespaceOverride: ""
    auths: # if docker add by `docker login`, if containerd append to `/etc/containerd/config.toml`
      "dockerhub.kubekey.local":
        username: "xxx"
        password: "***"
        skipTLSVerify: false # Allow contacting registries over HTTPS with failed TLS verification.
        plainHTTP: false # Allow contacting registries over HTTP.
        certsPath: "/etc/docker/certs.d/dockerhub.kubekey.local"
```
