### ISSUE TITLE
kk部署k8s v1.23.10三节点，其中一个节点calico node启动失败

### ISSUE THREAD

**Issue by fuwei4** [kubesphere/kubekey#2480]
### What is version of KubeKey has the issue?

v3.0.13

### What is your os environment?

RedHat 8.6

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: assistant
spec:
  hosts:
  - {name: kme-23-18, address: 172.16.23.18, internalAddress: 172.16.23.18, user: root, password: "sugon_web.com@."}
  - {name: kme-23-20, address: 172.16.23.20, internalAddress: 172.16.23.20, user: root, password: "sugon_web.com@."}
  - {name: kme-24-15, address: 172.16.24.15, internalAddress: 172.16.24.15, user: root, password: "sugon_web.com@."}
  roleGroups:
    etcd:
    - kme-23-18
    - kme-23-20
    - kme-24-15
    control-plane:
    - kme-23-18
    - kme-23-20
    - kme-24-15
    worker:
    - kme-23-18
    - kme-23-20
    - kme-24-15
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    internalLoadbalancer: haproxy
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.23.10
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: docker
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: "172.16.23.18:5000"
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

只部署k8s三节点，其中一个节点的calico node pod启动失败：
<img width="999" alt="calico_node" src="https://github.com/user-attachments/assets/4e49bff2-4c96-4637-9898-f5ea247bd14d" />
发现异常的节点上calico生成的配置IP加了个中括号：
<img width="629" alt="calico_config" src="https://github.com/user-attachments/assets/987f33a0-4019-4e4d-88a1-cdf49b2c5674" />
