### ISSUE TITLE
Expect to add support for kubeadm v1beta4

### ISSUE THREAD

**Issue by caozhengyx** [kubesphere/kubekey#2493]
### Your current KubeKey version

v3.1.7

### Describe this feature

Although kubekey has configured a systemd scheduled task on the master node by default to automatically update the certificate, it is currently not possible to specify the expiration time of the CA root certificate and leaf certificate. 

### Describe the solution you'd like

kubeadm v1beta4 now supports:

```yaml
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
certificateValidityPeriod: 8760h # Default: 365 days × 24 hours = 1 year
caCertificateValidityPeriod: 87600h # Default: 365 days × 24 hours * 10 = 10 years
```
