### ISSUE TITLE
【v4.x 】Unpredictable errors may occur if file definitions are referenced multiple times in a file.

### ISSUE THREAD

**Issue by redscholar** [kubesphere/kubekey#2496]
### What is version of KubeKey has the issue?

v4.x

### What is your os environment?

all

### KubeKey config file

```yaml

```

### A clear and concise description of what happend.

if defined the value in files like:
```yaml
a1: b1
a2: |
 {{- a1 -}}
a3: {{ a2 }}
```
it need two times to convert variable. but Map in golang is unordered. so it will have two results.
1. first convert
```yaml
a1: b1
a2: |
{{ - a1 -}}
a3: {{- a1 -}}
```
second convert
```
a1: b1
a2: b1
a3:b1
```
it's not a yaml format.
2. first convert
```yaml
a1: b1
a2: b1
a3: {{ a2 }}
```
second convert
```yaml
a1: b1
a2: b1
a3: b1
```
it's the correct yaml format

### Relevant log output

```shell

```
