### ISSUE TITLE
【v4.x】ssh command will escape

### ISSUE THREAD

**Issue by redscholar** [kubesphere/kubekey#2497]
### What is version of KubeKey has the issue?

4.x

### What is your os environment?

all

### KubeKey config file

```yaml

```

### A clear and concise description of what happend.

if defined command in tasks like:
```yaml
- name: test task
   command: |
     ip -br link show | grep cali[a-f0-9]* | awk -F @ '{print $1}'
```
the `$1` will Trigger script injection issue.
   

### Relevant log output

```shell

```
