### ISSUE TITLE
通过 kubekey 创建的k8s 集群，负载均衡器使用的是 kube-vip, 如何更新 ca证书

### ISSUE THREAD

**Issue by junlintianxiazhifulinzhongguo** [kubesphere/kubekey#2508]
配置如下
```
[root@k8s-master-01 ~]# cat config-sample.yaml

apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: k8s-master-01, address: 192.168.30.121, internalAddress: 192.168.30.121, user: root, password: "Yztx@2023"}
  roleGroups:
    etcd:
    - k8s-master-01
    control-plane:
    - k8s-master-01
    worker:
    - k8s-master-01
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    internalLoadbalancer: kube-vip

    domain: lb.kubesphere.local
    address: "192.168.30.120"
    port: 6443
  system:
    # The ntp servers of chrony.
    ntpServers:
      - ntp.aliyun.com
      - k8s-master-01 # Set the node name in `hosts` as ntp server if no public ntp servers access.
    timezone: "Asia/Shanghai"
  kubernetes:
    version: v1.28.13
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []



```
安装后的效果
```
[root@k8s-master-01 pki]# kubectl get pods -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS      AGE
kube-system   calico-kube-controllers-568d4f5458-ww8rv   1/1     Running   0             6d3h
kube-system   calico-node-8kpdn                          1/1     Running   0             6d3h
kube-system   coredns-69d6fd4c5d-dfqds                   1/1     Running   0             6d3h
kube-system   coredns-69d6fd4c5d-mj986                   1/1     Running   0             6d3h
kube-system   kube-apiserver-k8s-master-01               1/1     Running   0             6d3h
kube-system   kube-controller-manager-k8s-master-01      1/1     Running   1 (11m ago)   6d3h
kube-system   kube-proxy-jhnr9                           1/1     Running   0             6d3h
kube-system   kube-scheduler-k8s-master-01               1/1     Running   1 (11m ago)   6d3h
kube-system   kube-vip-k8s-master-01                     1/1     Running   1 (11m ago)   6d3h
kube-system   nodelocaldns-cd2bv                         1/1     Running   0             6d3h
[root@k8s-master-01 pki]#
[root@k8s-master-01 pki]#
[root@k8s-master-01 pki]#
[root@k8s-master-01 pki]# ip ad
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether bc:24:11:2a:52:87 brd ff:ff:ff:ff:ff:ff
    altname enp0s18
    inet 192.168.30.121/24 brd 192.168.30.255 scope global noprefixroute ens18
       valid_lft forever preferred_lft forever
    inet 192.168.30.120/32 scope global ens18
       valid_lft forever preferred_lft forever
    inet6 fe80::be24:11ff:fe2a:5287/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
5: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 10.233.109.0/32 scope global tunl0
       valid_lft forever preferred_lft forever
13: nodelocaldns: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default
    link/ether f6:0e:ee:1e:97:18 brd ff:ff:ff:ff:ff:ff
    inet 169.254.25.10/32 scope global nodelocaldns
       valid_lft forever preferred_lft forever
14: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default
    link/ether 56:2b:a3:a0:f8:ba brd ff:ff:ff:ff:ff:ff
    inet 10.233.0.1/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.233.0.3/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
17: cali65ea56c3c52@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1480 qdisc noqueue state UP group default qlen 1000
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-4d2d8514-5e8b-eddb-b77d-7b47d4cb69e0
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
18: calic893174089c@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1480 qdisc noqueue state UP group default qlen 1000
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-e708e807-69a0-5e90-dffe-311ec67791c2
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
19: calib1ab43c64af@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1480 qdisc noqueue state UP group default qlen 1000
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-4492aa6f-96b8-15a6-bf5e-10747f96626e
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
[root@k8s-master-01 pki]#


```
