### ISSUE TITLE
希望能够 给kk  工具增加一个 自定义证书过期时间的功能， 并能够自动更新ca.crt， front-proxy-ca.crt 和 etcd 的 证书过期时间

### ISSUE THREAD

**Issue by junlintianxiazhifulinzhongguo** [kubesphere/kubekey#2509]
### Describe this feature

正常情况下，ca.crt， front-proxy-ca.crt  和 etcd 的 证书过期时间都只有10年，过期更换比较麻烦， 其他组件的证书过期时间一般是一年。我想如果可以在kk 创建的config-sample.yaml可以自定义配置这两个证书的过期时间，并且 kk 自动更新证书的功能也能 自动更新 ca front-proxy-ca.crt  和 etcd 的 这些证书。

### Describe the solution you'd like

期望配置里相关配置，如：
```
[root@k8s-master-01 ~]# cat config-sample.yaml

apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: k8s-master-01, address: 192.168.30.121, internalAddress: 192.168.30.121, user: root, password: "Yztx@2023"}
  roleGroups:
    etcd:
    - k8s-master-01
    control-plane:
    - k8s-master-01
    worker:
    - k8s-master-01
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    internalLoadbalancer: kube-vip

    domain: lb.kubesphere.local
    address: "192.168.30.120"
    port: 6443
  system:
    # The ntp servers of chrony.
    ntpServers:
      - ntp.aliyun.com
      - k8s-master-01 # Set the node name in `hosts` as ntp server if no public ntp servers access.
    timezone: "Asia/Shanghai"
  kubernetes:
    version: v1.28.13
    clusterName: cluster.local
    autoRenewCerts: true
    caCertsExpireTime: 100     # 增加个自定义证书过期时间，默认10年，我想全部都是100年,
    otherCertsExpireTime: 100     # 增加个自定义证书过期时间，默认1年，我想全部都是100年
    containerManager: containerd
  etcd:
    type: kubekey
    caCertsExpireTime: 100     # 增加个自定义证书过期时间，默认10年，我想全部都是100年
    otherCertsExpireTime: 100     # 增加个自定义证书过期时间，默认1年，我想全部都是100年
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
[root@k8s-master-01 ~]#
```
