### ISSUE TITLE
无法安装部分插件

### ISSUE THREAD

**Issue by flyrun9527** [kubesphere/kubekey#2548]
### What is version of KubeKey has the issue?

3.1.9

### What is your os environment?

22.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: k8s-master, address: 192.168.130.100, internalAddress: 192.168.130.100, user: ubuntu, password: ***}
  - {name: k8s-node1, address: 192.168.130.101, internalAddress: 192.168.130.101, user: ubuntu, password: ***}
  roleGroups:
    etcd:
    - k8s-master
    control-plane:
    - k8s-master
    worker:
    - k8s-node1
  controlPlaneEndpoint:
    internalLoadbalancer: kube-vip # 如需部署⾼可⽤集群，且⽆负载均衡器可⽤，可开启该参数，做集群内部负载均衡
    externalDNS: false    
    domain: lb.kubesphere.local
    address: "192.168.130.250"
    port: 6443
  system:
    # The ntp servers of chrony.
    ntpServers:
      - time1.cloud.tencent.com
      - ntp.aliyun.com
      - k8s-master # Set the node name in `hosts` as ntp server if no public ntp servers access.
    timezone: "Asia/Shanghai"
    # Specify additional packages to be installed. The ISO file which is contained in the artifact is required.
    rpms:
      - nfs-utils
    # Specify additional packages to be installed. The ISO file which is contained in the artifact is required.
    debs: 
      - nfs-common
    postInstall:
      - name: clean tmps files
        bash: |
            rm -fr /tmp/kubekey/*      
  kubernetes:
    version: v1.28.15
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd # 部署 kubernetes v1.24+ 版本，建议将 containerManager 设置为 containerd
    apiserverArgs:
    - service-node-port-range=80-65535    
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    privateRegistry: ""
    registryMirrors: ["https://docker.1ms.run","https://hub.rat.dev","https://docker.1panel.live","https://hub.rat.dev","https://proxy.1panel.live","https://ghcr.nju.edu.cn","https://docker.registry.cyou","https://dockercf.jsdelivr.fyi","https://docker.rainbond.cc","https://registry.cn-shenzhen.aliyuncs.com","https://dockertest.jsdelivr.fyi","https://mirror.aliyuncs.com","https://mirror.baidubce.com","https://docker.mirrors.ustc.edu.cn","https://docker.mirrors.sjtug.sjtu.edu.cn","https://mirror.iscas.ac.cn","https://docker.nju.edu.cn","https://docker.m.daocloud.io","https://dockerproxy.com","https://docker.jsdelivr.fyi","https://docker-cf.registry.cyou","https://dockerhub.icu","https://registry.docker-cn.com","https://docker.mirrors.ustc.edu.cn","https://hub-mirror.c.163.com","https://mirror.baidubce.com","https://ccr.ccs.tencentyun.com"]
    insecureRegistries: ["192.168.112.124:20080"]
    dockerDataDir: "/data/docker"
    containerdDataDir: /data/containerd
    registryDataDir: /data/registry
```

### A clear and concise description of what happend.

2025-04-28T15:26:54.153845550+08:00   <-- POST /apis/kubesphere.io/v1alpha1/installplans 2025/04/28T15:26:54.153

2025-04-28T15:27:13.164052718+08:00 Error: read ECONNRESET

2025-04-28T15:27:13.164086707+08:00     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {

2025-04-28T15:27:13.164090687+08:00   errno: -104,

2025-04-28T15:27:13.164093957+08:00   code: 'ECONNRESET',

2025-04-28T15:27:13.164096887+08:00   syscall: 'read',

2025-04-28T15:27:13.164098957+08:00   headerSent: true

2025-04-28T15:27:13.164100997+08:00 }

### Relevant log output

```shell

```
