### ISSUE TITLE
ARM加上一台X86的服务器来部署harbor，kk不能把arm的镜像包推上harbor里去吗

### ISSUE THREAD

**Issue by GalenGao** [kubesphere/kubekey#2564]
### Your current KubeKey version

3.1.9

### Describe this feature

因为kk不支持arm的habor，所以规划其中一台x86的来部署harbor，但是推送镜像的时候总是推送不上去。

![Image](https://github.com/user-attachments/assets/0190c1cc-fb4c-485d-a1ee-e8f28ae14638)

### Describe the solution you'd like

我们试过下载arm 和amd的混合离线包也有问题，纯arm的离线包也有问题

**Comment by GalenGao** [comment]
配置文件config-sample.yaml

apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: host, address: 20.48.5.133, internalAddress: 20.48.5.133, user: root, password: "xxxxx",arch: arm64}
  - {name: member1, address: 20.48.1.130, internalAddress: 20.48.1.130, user: root, password: "xxxxx",arch: arm64}
  - {name: member2, address: 20.48.1.68, internalAddress: 20.48.1.68, user: root, password: "xxxxx",arch: amd}
  roleGroups:
    etcd:
    - host
    control-plane: 
    - host
    worker:
    - member1
    registry:
    - member2
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.33.0
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    type: harbor
    auths:
      "dockerhub.kubekey.local":
        username: admin
        password: Harbor12345
        skipTLSVerify: false
        plainHTTP: false # Allow contacting registries over HTTP.
        certsPath: "/etc/docker/certs.d/dockerhub.kubekey.local" # Use certificates at path (*.crt, *.cert, *.key) to connect to the registry.
    privateRegistry: "dockerhub.kubekey.local"
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
    containerdDataDir: /data/containerd
    dockerDataDir: /data/docker
    registryDataDir: /data/harbor/registry
  addons: []

**Comment by skyhhjmk** [comment]
> 配置文件config-sample.yaml
> 
> apiVersion: kubekey.kubesphere.io/v1alpha2 kind: Cluster metadata: name: sample spec: hosts:
> 
> * {name: host, address: 20.48.5.133, internalAddress: 20.48.5.133, user: root, password: "xxxxx",arch: arm64}


建议使用代码块以保留缩进并且方便阅读，使用方法：

~~~
```yaml

在里面粘贴你的配置文件

```
~~~

**Comment by GalenGao** [comment]
`
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: host, address: 20.48.5.133, internalAddress: 20.48.5.133, user: root, password: "xxxxx",arch: arm64}
  - {name: member1, address: 20.48.1.130, internalAddress: 20.48.1.130, user: root, password: "xxxxx",arch: arm64}
  - {name: member2, address: 20.48.1.68, internalAddress: 20.48.1.68, user: root, password: "xxxxx",arch: amd}
  roleGroups:
    etcd:
    - host
    control-plane: 
    - host
    worker:
    - member1
    registry:
    - member2
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.33.0
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    type: harbor
    auths:
      "dockerhub.kubekey.local":
        username: admin
        password: Harbor12345
        skipTLSVerify: false
        plainHTTP: false # Allow contacting registries over HTTP.
        certsPath: "/etc/docker/certs.d/dockerhub.kubekey.local" # Use certificates at path (*.crt, *.cert, *.key) to connect to the registry.
    privateRegistry: "dockerhub.kubekey.local"
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
    containerdDataDir: /data/containerd
    dockerDataDir: /data/docker
    registryDataDir: /data/harbor/registry
  addons: []


`

**Comment by GalenGao** [comment]
```yaml


apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: host, address: 20.48.5.133, internalAddress: 20.48.5.133, user: root, password: "xxxxx",arch: arm64}
  - {name: member1, address: 20.48.1.130, internalAddress: 20.48.1.130, user: root, password: "xxxxx",arch: arm64}
  - {name: member2, address: 20.48.1.68, internalAddress: 20.48.1.68, user: root, password: "xxxxx",arch: amd}
  roleGroups:
    etcd:
    - host
    control-plane: 
    - host
    worker:
    - member1
    registry:
    - member2
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.33.0
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    type: harbor
    auths:
      "dockerhub.kubekey.local":
        username: admin
        password: Harbor12345
        skipTLSVerify: false
        plainHTTP: false # Allow contacting registries over HTTP.
        certsPath: "/etc/docker/certs.d/dockerhub.kubekey.local" # Use certificates at path (*.crt, *.cert, *.key) to connect to the registry.
    privateRegistry: "dockerhub.kubekey.local"
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
    containerdDataDir: /data/containerd
    dockerDataDir: /data/docker
    registryDataDir: /data/harbor/registry
  addons: []


```
