### ISSUE TITLE
kubekey addons test items

### ISSUE THREAD

**Issue by pixiake** [kubesphere/kubekey#258]
chart :
- [ ] deploy a chart from repo with a remote values file

- [ ] deploy a chart from repo with a local values file

- [x] deploy a chart from repo with values list

- [ ] deploy a chart from repo without values

- [ ] deploy a chart from local path with a remote values file

- [ ] deploy a chart from local path with a local values file

- [ ] deploy a chart from local path with a values list

- [ ] deploy a chart from local path without values

yaml :
- [x] deploy a yaml from local path

- [x] deploy a yaml from remote

**Comment by zryfish** [comment]
Test passed with following configuration 

```yaml
  addons:
  - name: nfs-client
    namespace: kube-system
    sources:
      chart:
        name: nfs-client-provisioner
        repo: http://charts.kubesphere.io/main
        values:
        - storageClass.defaultClass=true
        - nfs.server=192.168.0.15
        - nfs.path=/mnt/kubesphere
```

**Comment by FeynmanZhou** [comment]
Let me test this task:  `deploy multiple yaml files from remote`. 

I will test a CSI plugin with kk addons.

**Comment by Forest-L** [comment]
Test passed with csi-qingcloud:
```
- name: csi-qingcloud
      namespace: kube-system
      sources:
        chart:
          name: csi-qingcloud
          repo: https://charts.kubesphere.io/test
          values:
          - config.qy_access_key_id=***
          - config.qy_secret_access_key=***
          - config.zone=***
          - sc.isDefaultClass=true
```

**Comment by zheng1** [comment]
Test passed with this case ` deploy multiple yaml files from remote`
```yaml
  addons:
  - name: nfs
    namespace: kube-system
    sources:
      yaml:
        path:
        - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/deploy/kubernetes/csi-nfs-driverinfo.yaml
        - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/deploy/kubernetes/csi-nodeplugin-nfsplugin.yaml
        - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/deploy/kubernetes/csi-nodeplugin-rbac.yaml
```

**Comment by zheng1** [comment]
test passed with this case `deploy a yaml from local path`
```
  addons:
  - name: nfs
    namespace: kube-system
    sources:
      yaml:
        path:
        - /root/nfs.yaml
```
