### ISSUE TITLE
3.1.9安装集群报错

### ISSUE THREAD

**Issue by sea10094** [kubesphere/kubekey#2581]
### What is version of KubeKey has the issue?

3.1.9

### What is your os environment?

ubuntu22.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: dual-node-cluster
spec:
  hosts:
    - {name: master, address: 10.12.115.34, internalAddress: 10.12.115.34, user: root, sshKey: "/root/.ssh/id_rsa"}  # 使用 SSH 密钥路径
    - {name: worker, address: 10.12.114.139, internalAddress: 10.12.114.139, user: root, sshKey: "/root/.ssh/id_rsa"}
  roleGroups:
    etcd: [master]
    control-plane: [master]
    worker: [worker]
  kubernetes:
    version: v1.23.0
    clusterName: mada
    autoRenewCerts: true
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
```

### A clear and concise description of what happend.

15:13:40 CST [JoinNodesModule] Join worker node
15:13:40 CST stdout: [worker]
[discovery.bootstrapToken.token: Invalid value: "": the bootstrap token is invalid, discovery.tlsBootstrapToken: Invalid value: "": the bootstrap token is invalid]
To see the stack trace of this error execute with --v=5 or higher
15:13:40 CST stdout: [worker]
[preflight] Running pre-flight checks
W0521 15:13:40.696722   36053 removeetcdmember.go:80] [reset] No kubeadm config, using etcd pod spec to get data directory
[reset] No etcd config found. Assuming external etcd
[reset] Please, manually reset etcd to prevent further issues
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
W0521 15:13:40.698379   36053 cleanupnode.go:109] [reset] Failed to evaluate the "/var/lib/kubelet" directory. Skipping its unmount and cleanup: lstat /var/lib/kubelet: no such file or directory
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
[reset] Deleting contents of stateful directories: [/var/lib/dockershim /var/run/kubernetes /var/lib/cni]

The reset process does not clean CNI configuration. To do so, you must remove /etc/cni/net.d

The reset process does not reset or clean up iptables rules or IPVS tables.
If you wish to reset iptables, you must do so manually by using the "iptables" command.

If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)
to reset your system's IPVS tables.

The reset process does not clean your kubeconfig files and you must remove them manually.
Please, check the contents of the $HOME/.kube/config file.
15:13:40 CST message: [worker]
join node failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubeadm join --config=/etc/kubernetes/kubeadm-config.yaml --ignore-preflight-errors=FileExisting-crictl,ImagePull"
[discovery.bootstrapToken.token: Invalid value: "": the bootstrap token is invalid, discovery.tlsBootstrapToken: Invalid value: "": the bootstrap token is invalid]
To see the stack trace of this error execute with --v=5 or higher: Process exited with status 3
15:13:40 CST retry: [worker]

### Relevant log output

```shell

```
