### ISSUE TITLE
3.19 kk初始化报错

### ISSUE THREAD

**Issue by sea10094** [kubesphere/kubekey#2582]
### What is version of KubeKey has the issue?

3.1.9

### What is your os environment?

ubuntu22.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: dual-node-cluster
spec:
  hosts:
    - {name: master, address: 10.12.115.34, internalAddress: 10.12.115.34, user: root, sshKey: "/root/.ssh/id_rsa"}  # 使用 SSH 密钥路径
    - {name: worker, address: 10.12.114.139, internalAddress: 10.12.114.139, user: root, sshKey: "/root/.ssh/id_rsa"}
  roleGroups:
    etcd: [master]
    control-plane: [master]
    worker: [worker]
  kubernetes:
    version: v1.23.0
    clusterName: mada
    autoRenewCerts: true
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
```

### A clear and concise description of what happend.

kk create cluster -f config-sample.yaml -a /root/offline_1.23.0.tar.gz

 _   __      _          _   __
| | / /     | |        | | / /
| |/ / _   _| |__   ___| |/ /  ___ _   _
|    \| | | | '_ \ / _ \    \ / _ \ | | |
| |\  \ |_| | |_) |  __/ |\  \  __/ |_| |
\_| \_/\__,_|_.__/ \___\_| \_/\___|\__, |
                                    __/ |
                                   |___/

16:25:10 CST [GreetingsModule] Greetings
16:25:11 CST message: [worker]
Greetings, KubeKey!
16:25:11 CST message: [master]
failed to get SSH session: ssh: setenv failed
16:25:11 CST retry: [master]
16:25:16 CST message: [master]
failed to get SSH session: ssh: setenv failed
16:25:16 CST retry: [master]
16:25:21 CST message: [master]
failed to get SSH session: ssh: setenv failed
16:25:21 CST success: [worker]
16:25:21 CST failed: [master]
error: Pipeline[CreateClusterPipeline] execute failed: Module[GreetingsModule] exec failed:
failed: [master] [Greetings] exec failed after 3 retries: failed to get SSH session: ssh: setenv failed

### Relevant log output

```shell

```
