### ISSUE TITLE
不知道为啥kube-vip使用ARP模式不会给网卡添加vip

### ISSUE THREAD

**Issue by jmjoy** [kubesphere/kubekey#2645]
### What is version of KubeKey has the issue?

kk version: &version.Info{Major:"3", Minor:"2", GitVersion:"v3.2.0-alpha.0.46-9cf08b6aef1cc5-dirty", GitCommit:"9cf08b6aef1cc5490a85b996558491940a27b6f3", GitTreeState:"dirty", BuildDate:"2025-06-27T07:35:03Z", GoVersion:"go1.24.0", Compiler:"gc", Platform:"linux/amd64"}

### What is your os environment?

Debian 10

### KubeKey config file

```yaml
controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    internalLoadbalancer: "kube-vip"
    domain: lb.test-kk.local
    address: "10.4.139.88"
    port: 6443
```

### A clear and concise description of what happend.

真的非常奇怪，`kubeadm init`之后，健康检查一直不成功，原因就是vip不生效，调用`kube-apiserver`接口失败。

我在第一个master节点手动调用命令：`sudo ip addr add 10.4.139.88/32 dev eth0`，才能向下跑创建成功。

但是我测试master节点的高可用性，删掉第一个master节点，看到vip能飘到第二个master节点的，看起来kube-vip也没啥问题啊。

### Relevant log output

```shell

```
