### ISSUE TITLE
$CHANNEL is undefined in scripts\docker-install.sh caused installing docker failed?

### ISSUE THREAD

**Issue by yeongjet** [kubesphere/kubekey#284]
```
ERRO[10:56:40 CST] Failed to install docker:
which: no docker in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12886  100 12886    0     0  68909      0 --:--:-- --:--:-- --:--:-- 68909
+ '[' centos = redhat ']'
+ sh -c 'yum install -y -q yum-utils'
warning: /var/cache/dnf/BaseOS-929b586ef1f72f69/packages/yum-utils-4.0.12-3.el8.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 8483c65d: NOKEY
Importing GPG key 0x8483C65D:
 Userid     : "CentOS (CentOS Official Signing Key) <security@centos.org>"
 Fingerprint: 99DB 70FA E1D7 CE22 7FB6 4882 05B5 55B3 8483 C65D
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
+ sh -c 'yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo'
Adding repo from: https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
+ '[' '' '!=' stable ']'
+ echo 'Info: Enabling channel '\'''\'' for docker-ce repo'
Info: Enabling channel '' for docker-ce repo
+ sh -c 'yum-config-manager --enable docker-ce-'
Error: No matching repo to modify: docker-ce-.: Failed to exec command: sudo -E /bin/sh -c "if [ -z $(which docker) ] || [ ! -e /var/run/docker.sock ]; then curl https://kubernetes.pek3b.qingstor.com/tools/kubekey/docker-install.sh | sh && systemctl enable docker && echo ewogICJsb2ctb3B0cyI6IHsKICAgICJtYXgtc2l6ZSI6ICI1bSIsCiAgICAibWF4LWZpbGUiOiIzIgogIH0sCiAgImV4ZWMtb3B0cyI6IFsibmF0aXZlLmNncm91cGRyaXZlcj1zeXN0ZW1kIl0KfQo= | base64 -d > /etc/docker/daemon.json && systemctl reload docker; fi" 
which: no docker in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12886  100 12886    0     0  68909      0 --:--:-- --:--:-- --:--:-- 68909
+ '[' centos = redhat ']'
+ sh -c 'yum install -y -q yum-utils'
warning: /var/cache/dnf/BaseOS-929b586ef1f72f69/packages/yum-utils-4.0.12-3.el8.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 8483c65d: NOKEY
Importing GPG key 0x8483C65D:
 Userid     : "CentOS (CentOS Official Signing Key) <security@centos.org>"
 Fingerprint: 99DB 70FA E1D7 CE22 7FB6 4882 05B5 55B3 8483 C65D
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
+ sh -c 'yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo'
Adding repo from: https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
+ '[' '' '!=' stable ']'
+ echo 'Info: Enabling channel '\'''\'' for docker-ce repo'
Info: Enabling channel '' for docker-ce repo
+ sh -c 'yum-config-manager --enable docker-ce-'
Error: No matching repo to modify: docker-ce-.: Process exited with status 1  node=192.168.1.137
```

my config:
```
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master1, address: 192.168.1.141, internalAddress: 192.168.1.141, user: root, password: abc123}
  - {name: master2, address: 192.168.1.136, internalAddress: 192.168.1.136, user: root, password: abc123}
  - {name: master3, address: 192.168.1.137, internalAddress: 192.168.1.137, user: root, password: abc123}
  - {name: worker1, address: 192.168.1.139, internalAddress: 192.168.1.139, user: root, password: abc123}
  - {name: worker2, address: 192.168.1.140, internalAddress: 192.168.1.140, user: root, password: abc123}
  - {name: worker3, address: 192.168.1.142, internalAddress: 192.168.1.142, user: root, password: abc123}
  roleGroups:
    etcd:
    - master1
    - master2
    - master3
    master:
    - master1
    - master2
    - master3
    worker:
    - worker1
    - worker2
    - worker3
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: "6443"
  kubernetes:
    version: v1.19.0
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: []


---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.0.0
spec:
  local_registry: ""
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  etcd:
    monitoring: true
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    es:
      elasticsearchDataVolumeSize: 20Gi
      elasticsearchMasterVolumeSize: 4Gi
      elkPrefix: logstash
      logMaxAge: 7
    mysqlVolumeSize: 20Gi
    minioVolumeSize: 20Gi
    etcdVolumeSize: 20Gi
    openldapVolumeSize: 2Gi
    redisVolumSize: 2Gi
  console:
    enableMultiLogin: false  # enable/disable multi login
    port: 30880
  alerting:
    enabled: false
  auditing:
    enabled: false
  devops:
    enabled: false
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 512m
    jenkinsJavaOpts_Xmx: 512m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: false
    ruler:
      enabled: true
      replicas: 2
  logging:
    enabled: false
    logsidecarReplicas: 2
  metrics_server:
    enabled: true
  monitoring:
    prometheusMemoryRequest: 400Mi
    prometheusVolumeSize: 20Gi
  multicluster:
    clusterRole: none  # host | member | none
  networkpolicy:
    enabled: false
  notification:
    enabled: false
  openpitrix:
    enabled: false
  servicemesh:
    enabled: false

```

I found these codes in scripts\docker-install.sh:
```
                if [ "$lsb_dist" = "redhat" ]; then
                    for rhel_repo in $rhel_repos ; do
                        $sh_c "$config_manager $enable_channel_flag $rhel_repo"
                    done
                    fi
                    $sh_c "$pkg_manager install -y -q $pre_reqs"
                    $sh_c "$config_manager --add-repo $yum_repo"
                    if [ "$CHANNEL" != "stable" ]; then
                        echo "Info: Enabling channel '$CHANNEL' for docker-ce repo"
                        $sh_c "$config_manager $enable_channel_flag docker-ce-$CHANNEL"
                    fi
                    $sh_c "$pkg_manager makecache fast"
                    $sh_c "$pkg_manager install -y -q docker-ce-${docker_version}"
                    if [ -d '/run/systemd/system' ]; then
                        $sh_c 'service docker start'
                    else
                        $sh_c 'systemctl start docker'
                    fi
```
$CHANNEL is non value cause this error
