### ISSUE TITLE
calico   changed  flannel   mode  vxlan or host gw，I need  how todo。

### ISSUE THREAD

**Issue by xuelangos** [kubesphere/kubekey#291]
![image](https://user-images.githubusercontent.com/13230347/92446735-d666f600-f1e8-11ea-9f86-2f5f1d0328ab.png)
what  codes I should be changed ？

**Comment by Forest-L** [comment]
@xuelangos 
If you choose flannel, refer to this configuration, such as:
```
network:
    plugin: flannel
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
```
Currently, we support VXLAN and later host GW
