### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by Sh-Zh-7** [kubesphere/kubekey#384]
Hi, I'm creating a cluster on Alibaba cloud followed by this [link](https://kubesphere.com.cn/docs/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs/).
When using kubekey to deploy a cluster I meet the following problem:
```
[root@XXXXX~]# ./kk create cluster -f config-sample.yaml
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/kubesphere/kubekey/pkg/apis/kubekey/v1alpha1.(*ClusterSpec).GroupHosts(0xc000196800, 0x0)
	/usr/src/myapp/pkg/apis/kubekey/v1alpha1/cluster_types.go:203 +0xc98
github.com/kubesphere/kubekey/pkg/apis/kubekey/v1alpha1.(*ClusterSpec).SetDefaultClusterSpec(0xc0004d2f18, 0xc0003aa100, 0x0)
	/usr/src/myapp/pkg/apis/kubekey/v1alpha1/default.go:60 +0xd1
github.com/kubesphere/kubekey/pkg/util/executor.(*Executor).CreateManager(0xc00079fc70, 0x1, 0xc000414440, 0xc00011d110)
	/usr/src/myapp/pkg/util/executor/executor.go:50 +0x4c
github.com/kubesphere/kubekey/pkg/install.Execute(0xc00079fc70, 0x12, 0x0)
	/usr/src/myapp/pkg/install/install.go:98 +0x2b
github.com/kubesphere/kubekey/pkg/install.CreateCluster(0x7ffd2f37587f, 0x12, 0x0, 0x0, 0x0, 0x0, 0xc00066c070, 0xc000000100, 0x1aa4089, 0x4)
	/usr/src/myapp/pkg/install/install.go:52 +0x245
github.com/kubesphere/kubekey/cmd.glob..func2(0x2a69e00, 0xc0007ea2a0, 0x0, 0x2, 0x0, 0x0)
	/usr/src/myapp/cmd/cluster.go:36 +0x200
github.com/spf13/cobra.(*Command).execute(0x2a69e00, 0xc0007ea280, 0x2, 0x2, 0x2a69e00, 0xc0007ea280)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x2a6adc0, 0x1abbee0, 0x16, 0xc00079ff20)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/kubesphere/kubekey/cmd.Execute()
	/usr/src/myapp/cmd/root.go:57 +0x31
main.main()
	/usr/src/myapp/kubekey.go:38 +0x1a5
```
I think there must be some problem with my `config-sample.yaml` .
Base on the [template that given by the official website](https://kubesphere.com.cn/docs/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs/#%E9%9B%86%E7%BE%A4%E9%85%8D%E7%BD%AE%E8%B0%83%E6%95%B4). I only add 2 things:

1.  necessary information about my hosts. 
 ```metadata:
  name: config-sample
  spec:
    hosts:
    - {name: master1, address: x.x.x.x internalAddress: y.y.y.y, user: root, password: Aa123456}
```
2.  address of my SLB. 
```
controlPlaneEndpoint:
  domain: lb.kubesphere.local
  address: "z.z.z.z"
  port: "6443"
```

I wondered if there are more things that need to be added into this configuration file. Or maybe there are some other things wrong.

**Comment by Forest-L** [comment]
@Sh-Zh-7 You can check the etcd parameters.

**Comment by Sh-Zh-7** [comment]
Here is my role group configuration. It is just the same as the official website
```
    roleGroups:
      etcd:
      - master1
      - master2
      - master3
      master:
      - master1
      - master2
      - master3
      worker:
      - node1
      - node2
      - node3
```
I'm new to Kubernetes and KubeSphere. Did you mean I need to add additional software dependencies except for the existing configuration on your website?

**Comment by pixiake** [comment]
> @Forest-L Here is my role group configuration, which includes etcd parameters. It is just the same as the official website
> 
> ```
>     roleGroups:
>       etcd:
>       - master1
>       - master2
>       - master3
>       master:
>       - master1
>       - master2
>       - master3
>       worker:
>       - node1
>       - node2
>       - node3
> ```
> 
> I'm new to Kubernetes and KubeSphere. Did you mean I need to add additional software dependencies except for the existing configuration on your website?
Not required.

**Comment by Sh-Zh-7** [comment]
@pixiake 
```
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: config-sample
  spec:
    hosts:
    - {name: master1, address: a.a.a.a, internalAddress: a.a.a.a, user: root, password: Aa123456}
    - {name: master2, address: b.b.b.b, internalAddress: b.b.b.b, user: root, password: Aa123456}
    - {name: master3, address: c.c.c.c, internalAddress: c.c.c.c, user: root, password: Aa123456}
    - {name: node1, address: d.d.d.d, internalAddress: d.d.d.d, user: root, password: Aa123456}
    - {name: node2, address: e.e.e.e, internalAddress: e.e.e.e, user: root, password: Aa123456}
    - {name: node3, address: f.f.f.f, internalAddress: f.f.f.f, user: root, password: Aa123456}
    roleGroups:
      etcd:
      - master1
      - master2
      - master3
      master:
      - master1
      - master2
      - master3
      worker:
      - node1
      - node2
      - node3
    controlPlaneEndpoint:
      domain: lb.kubesphere.local
      address: "x.x.x.x"
      port: "6443"
    kubernetes:
      version: v1.17.9
      imageRepo: kubesphere
      clusterName: cluster.local
      masqueradeAll: false  # masqueradeAll tells kube-proxy to SNAT everything if using the pure iptables proxy mode. [Default: false]
      maxPods: 110  # maxPods is the number of pods that can run on this Kubelet. [Default: 110]
      nodeCidrMaskSize: 24  # internal network node size allocation. This is the size allocated to each node on your network. [Default: 24]
      proxyMode: ipvs  # mode specifies which proxy mode to use. [Default: ipvs]
    network:
      plugin: calico
      calico:
        ipipMode: Always  # IPIP Mode to use for the IPv4 POOL created at start up. If set to a value other than Never, vxlanMode should be set to "Never". [Always | CrossSubnet | Never] [Default: Always]
        vxlanMode: Never  # VXLAN Mode to use for the IPv4 POOL created at start up. If set to a value other than Never, ipipMode should be set to "Never". [Always | CrossSubnet | Never] [Default: Never]
        vethMTU: 1440  # The maximum transmission unit (MTU) setting determines the largest packet size that can be transmitted through your network. [Default: 1440]
      kubePodsCIDR: 10.233.64.0/18
      kubeServiceCIDR: 10.233.0.0/18
    registry:
      registryMirrors: []
      insecureRegistries: []
      privateRegistry: dockerhub.kubekey.local
    addons: [] # add your persistent storage and LoadBalancer plugin configuration here if you have, see https://kubesphere.io/docs/installing-on-linux/introduction/storage-configuration/
```
The OS image was the **CentOS 7.8**.

The host's address I filled in is the **ECS's public IP**. And the internal address I filled in is the **same as** the `address` field.

It seems Alibaba cloud's console doesn't support modify host name but only support modify the instance name, which is totally different from Qing cloud. So I changed the **instance name** and filled it into the `name` filed. 
![QQ截图20201123142814](https://user-images.githubusercontent.com/43316505/99934375-c5199880-2d98-11eb-9389-4dda2818d52a.png)

**Comment by pixiake** [comment]
The configuration file is a direct copy from `https://github.com/kubesphere/kubekey/blob/master/docs/config-example.md` ?

You can create configuration file by `./kk create config` and try again.

**Comment by Sh-Zh-7** [comment]
OK, I found the problem.
It's the [template on the official website](https://kubesphere.com.cn/docs/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs/#%E9%9B%86%E7%BE%A4%E9%85%8D%E7%BD%AE%E8%B0%83%E6%95%B4) that made this mistake.
The field `spec` has one more indentation. That is to say, the
```
#vi ~/config-sample.yaml
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: config-sample
  spec:
    hosts:
    - {name: master1, address: 172.24.107.72, internalAddress: 172.24.107.72, user: root, password: QWEqwe123}
    - {name: master2, address: 172.24.107.73, internalAddress: 172.24.107.73, user: root, password: QWEqwe123}
    - {name: master3, address: 172.24.107.74, internalAddress: 172.24.107.74, user: root, password: QWEqwe123}
    - {name: node1, address: 172.24.107.75, internalAddress: 172.24.107.75, user: root, password: QWEqwe123}
    - {name: node2, address: 172.24.107.76, internalAddress: 172.24.107.76, user: root, password: QWEqwe123}
    - {name: node3, address: 172.24.107.77, internalAddress: 172.24.107.77, user: root, password: QWEqwe123}
    roleGroups:
      etcd:
      - master1
      - master2
      - master3
      master:
      - master1
      - master2
      - master3
      worker:
      - node1
      - node2
      - node3
    controlPlaneEndpoint:
      domain: lb.kubesphere.local
      address: "39.104.82.170"
      port: "6443"
    kubernetes:
      version: v1.17.9
      imageRepo: kubesphere
      clusterName: cluster.local
      masqueradeAll: false  # masqueradeAll tells kube-proxy to SNAT everything if using the pure iptables proxy mode. [Default: false]
      maxPods: 110  # maxPods is the number of pods that can run on this Kubelet. [Default: 110]
      nodeCidrMaskSize: 24  # internal network node size allocation. This is the size allocated to each node on your network. [Default: 24]
      proxyMode: ipvs  # mode specifies which proxy mode to use. [Default: ipvs]
    network:
      plugin: calico
      calico:
        ipipMode: Always  # IPIP Mode to use for the IPv4 POOL created at start up. If set to a value other than Never, vxlanMode should be set to "Never". [Always | CrossSubnet | Never] [Default: Always]
        vxlanMode: Never  # VXLAN Mode to use for the IPv4 POOL created at start up. If set to a value other than Never, ipipMode should be set to "Never". [Always | CrossSubnet | Never] [Default: Never]
        vethMTU: 1440  # The maximum transmission unit (MTU) setting determines the largest packet size that can be transmitted through your network. [Default: 1440]
      kubePodsCIDR: 10.233.64.0/18
      kubeServiceCIDR: 10.233.0.0/18
    registry:
      registryMirrors: []
      insecureRegistries: []
    addons: [] # add your persistent storage and LoadBalancer plugin configuration here if you have, see https://kubesphere.io/docs/installing-on-linux/introduction/storage-configuration/
```
should be
```
#vi ~/config-sample.yaml
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: config-sample
spec:
  hosts:
  - {name: master1, address: 172.24.107.72, internalAddress: 172.24.107.72, user: root, password: QWEqwe123}
  - {name: master2, address: 172.24.107.73, internalAddress: 172.24.107.73, user: root, password: QWEqwe123}
  - {name: master3, address: 172.24.107.74, internalAddress: 172.24.107.74, user: root, password: QWEqwe123}
  - {name: node1, address: 172.24.107.75, internalAddress: 172.24.107.75, user: root, password: QWEqwe123}
  - {name: node2, address: 172.24.107.76, internalAddress: 172.24.107.76, user: root, password: QWEqwe123}
  - {name: node3, address: 172.24.107.77, internalAddress: 172.24.107.77, user: root, password: QWEqwe123}
  roleGroups:
    etcd:
    - master1
    - master2
    - master3
    master:
    - master1
    - master2
    - master3
    worker:
    - node1
    - node2
    - node3
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: "39.104.82.170"
    port: "6443"
  kubernetes:
    version: v1.17.9
    imageRepo: kubesphere
    clusterName: cluster.local
    masqueradeAll: false  # masqueradeAll tells kube-proxy to SNAT everything if using the pure iptables proxy mode. [Default: false]
    maxPods: 110  # maxPods is the number of pods that can run on this Kubelet. [Default: 110]
    nodeCidrMaskSize: 24  # internal network node size allocation. This is the size allocated to each node on your network. [Default: 24]
    proxyMode: ipvs  # mode specifies which proxy mode to use. [Default: ipvs]
  network:
    plugin: calico
    calico:
      ipipMode: Always  # IPIP Mode to use for the IPv4 POOL created at start up. If set to a value other than Never, vxlanMode should be set to "Never". [Always | CrossSubnet | Never] [Default: Always]
      vxlanMode: Never  # VXLAN Mode to use for the IPv4 POOL created at start up. If set to a value other than Never, ipipMode should be set to "Never". [Always | CrossSubnet | Never] [Default: Never]
      vethMTU: 1440  # The maximum transmission unit (MTU) setting determines the largest packet size that can be transmitted through your network. [Default: 1440]
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: [] # add your persistent storage and LoadBalancer plugin configuration here if you have, see https://kubesphere.io/docs/installing-on-linux/introduction/storage-configuration/
```
Fix it and then close this issue pls.
