### ISSUE TITLE
HA server install fail on DigitalOcean

### ISSUE THREAD

**Issue by noprom** [kubesphere/kubekey#471]
My `cluster.yaml`:
```
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: cluster
spec:
  hosts:
  - {name: ks-master-01, address: 157.245.134.194, internalAddress: 157.245.134.194, user: root, privateKeyPath: "~/.ssh/id_ed25519"}
  - {name: ks-master-02, address: 67.205.158.154, internalAddress: 67.205.158.154, user: root, privateKeyPath: "~/.ssh/id_ed25519"}
  - {name: ks-master-03, address: 161.35.0.189, internalAddress: 161.35.0.189, user: root, privateKeyPath: "~/.ssh/id_ed25519"}
  - {name: ks-node-do-nyc-01, address: 67.207.89.252, internalAddress: 67.207.89.252, user: root, privateKeyPath: "~/.ssh/id_ed25519"}
  roleGroups:
    etcd:
    - ks-master-01
    - ks-master-02
    - ks-master-03
    master: 
    - ks-master-01
    - ks-master-02
    - ks-master-03
    worker:
    - ks-node-do-nyc-01
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: "167.172.0.198"
    port: "6443"
  kubernetes:
    version: v1.18.6
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: []

---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.0.0
spec:
  local_registry: ""
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  etcd:
    monitoring: false
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    es:
      elasticsearchDataVolumeSize: 20Gi
      elasticsearchMasterVolumeSize: 4Gi
      elkPrefix: logstash
      logMaxAge: 7
    mysqlVolumeSize: 20Gi
    minioVolumeSize: 20Gi
    etcdVolumeSize: 20Gi
    openldapVolumeSize: 2Gi
    redisVolumSize: 2Gi
  console:
    enableMultiLogin: false  # enable/disable multi login
    port: 30880
  alerting:
    enabled: false
  auditing:
    enabled: false
  devops:
    enabled: false
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 512m
    jenkinsJavaOpts_Xmx: 512m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: false
    ruler:
      enabled: true
      replicas: 2
  logging:
    enabled: false
    logsidecarReplicas: 2
  metrics_server:
    enabled: false
  monitoring:
    prometheusMemoryRequest: 400Mi
    prometheusVolumeSize: 20Gi
  multicluster:
    clusterRole: none  # host | member | none
  networkpolicy:
    enabled: false
  notification:
    enabled: false
  openpitrix:
    enabled: false
  servicemesh:
    enabled: false
```

My commands:
```
curl -sfL https://get-kk.kubesphere.io | VERSION=v1.0.1 sh -
chmod +x kk
./kk create cluster -f cluster.yaml
```

k8s install is ok, but openebs always fail:
```
[root@ks-master-01 ~]# kubectl -n kube-system get pods | grep -v Running
NAME                                           READY   STATUS             RESTARTS   AGE
openebs-localpv-provisioner-84446d4bd7-8s95j   0/1     CrashLoopBackOff   5          9m
[root@ks-master-01 ~]# kubectl -n kube-system logs -f openebs-localpv-provisioner-84446d4bd7-8s95j
I0306 00:17:44.052877       1 start.go:65] Starting Provisioner...
Cannot start Provisioner: failed to get Kubernetes server version: Get https://10.233.0.1:443/version?timeout=32s: dial tcp 10.233.0.1:443: i/o timeout
```
My loadbalancer is ok:
```
[root@ks-master-01 ~]# curl -k https://167.172.0.198:6443
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {

  },
  "code": 403
}
```
```
[root@ks-master-01 ~]# kubectl get nodes
NAME                STATUS   ROLES    AGE     VERSION
ks-master-01        Ready    master   8m46s   v1.18.6
ks-master-02        Ready    master   8m14s   v1.18.6
ks-master-03        Ready    master   8m13s   v1.18.6
ks-node-do-nyc-01   Ready    worker   8m14s   v1.18.6
[root@ks-master-01 ~]# kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.233.0.1   <none>        443/TCP   9m27s
```
You can try it by simply create 4 `2c4g` droplets on [digitalocean](https://digitalocean.com)
