### ISSUE TITLE
Failed to scale Muti-node(1 master 2 node) to HA (3 master, 3 node)

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubekey#54]
The failed msg is as follows:

```
Waiting for etcd to start
INFO[18:11:54 CST] Get cluster status
[node1 192.168.0.2] MSG:
/etc/kubernetes/admin.conf
[node1 192.168.0.2] MSG:
v1.17.6
WARN[18:14:10 CST] Task failed ...
WARN[18:14:10 CST] error: Failed to upload kubeadm certs: Failed to exec command: sudo -E /bin/sh -c "/usr/local/bin/kubeadm init phase upload-certs --upload-certs": Process exited with status 1
Error: Failed to get cluster status: Failed to upload kubeadm certs: Failed to exec command: sudo -E /bin/sh -c "/usr/local/bin/kubeadm init phase upload-certs --upload-certs": Process exited with status 1
Usage:
  kk scale [flags]

Flags:
      --debug          (default true)
  -f, --file string   configuration file name
  -h, --help          help for scale
```

My current config-sample.yaml:

```
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: config-sample
spec:
  hosts:
  - {name: node1, address: 192.168.0.2, internalAddress: 192.168.0.2, password: Qcloud@123}
  - {name: node2, address: 192.168.0.3, internalAddress: 192.168.0.3, password: Qcloud@123}
  - {name: node3, address: 192.168.0.4, internalAddress: 192.168.0.4, password: Qcloud@123}
  - {name: node4, address: 192.168.0.5, internalAddress: 192.168.0.5, password: Qcloud@123}
  - {name: node5, address: 192.168.0.6, internalAddress: 192.168.0.6, password: Qcloud@123}
  - {name: node6, address: 192.168.0.7, internalAddress: 192.168.0.7, password: Qcloud@123}
  roleGroups:
    etcd:
    - node1
    - node4
    - node6
    master:
    - node1
    - node4
    - node6
    worker:
    - node2
    - node3
    - node5
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: "192.168.0.253"
    port: "6443"
  kubernetes:
    version: v1.17.6
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: calico
    kube_pods_cidr: 10.233.64.0/18
    kube_service_cidr: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
```

My previous config-sample.yaml:

```
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: config-sample
spec:
  hosts:
  - {name: node1, address: 192.168.0.2, internalAddress: 192.168.0.2, password: Qcloud@123}
  - {name: node2, address: 192.168.0.3, internalAddress: 192.168.0.3, password: Qcloud@123}
  - {name: node3, address: 192.168.0.4, internalAddress: 192.168.0.4, password: Qcloud@123}
  roleGroups:
    etcd:
    - node1
    master:
    - node1
    worker:
    - node2
    - node3
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: "6443"
  kubernetes:
    version: v1.17.6
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: calico
    kube_pods_cidr: 10.233.64.0/18
    kube_service_cidr: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
```
