### ISSUE TITLE
add nodes for master and etcd cluster, failed to exec command

### ISSUE THREAD

**Issue by shihaoH** [kubesphere/kubekey#560]
failed to add master to cluster: failed to exec command: sudo env PATH=$PATH /bin/sh -c " --apiserver-advertise-address 192.168.0.5"

**Comment by 24sama** [comment]
Can you paste your config file on this site?

**Comment by shihaoH** [comment]
> Can you paste your config file on this site?


`apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: lb1, address: 192.168.161.222, internalAddress: 192.168.161.222, user: root, password: 1012}
  - {name: lb2, address: 192.168.161.223, internalAddress: 192.168.161.223, user: root, password: 1012}
  - {name: node1, address: 192.168.161.224, internalAddress: 192.168.161.224, user: root, password: 1012}
  - {name: node2, address: 192.168.161.225, internalAddress: 192.168.161.225, user: root, password: 1012}
  - {name: node3, address: 192.168.161.226, internalAddress: 192.168.161.226, user: root, password: 1012}
  roleGroups:
    etcd:
    - lb1
    - lb2
    - node1
    master: 
    - lb1
    - lb2
    - node1
    worker:
    - node1
    - node2
    - node3
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: "192.168.161.55"
    port: "6443"
  kubernetes:
    version: v1.18.6
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
    privateRegistry: docker.harbor.local
  addons: []
`

**Comment by 24sama** [comment]
Please try to change the `hosts[]` and `roleGroups` order like:
```
hosts:
  - {name: node1, address: 192.168.161.224, internalAddress: 192.168.161.224, user: root, password: 1012}
  - {name: node2, address: 192.168.161.225, internalAddress: 192.168.161.225, user: root, password: 1012}
  - {name: node3, address: 192.168.161.226, internalAddress: 192.168.161.226, user: root, password: 1012}
  - {name: lb1, address: 192.168.161.222, internalAddress: 192.168.161.222, user: root, password: 1012}
  - {name: lb2, address: 192.168.161.223, internalAddress: 192.168.161.223, user: root, password: 1012}
roleGroups:
    etcd:
    - node1
    - lb1
    - lb2
    master: 
    - node1
    - lb1
    - lb2
    worker:
    - node1
    - node2
    - node3
```

**Comment by shihaoH** [comment]
after modification nodes order
execute `./kk add nodes -f config.yaml`
`Failed to get cluster status: Failed to upload kubeadm certs: Failed to exec command: sudo -E /bin/sh -c "/usr/local/bin/kubeadm init phase upload-certs --upload-certs"`

**Comment by 24sama** [comment]
Check your `/etc/kubernetes/admin.conf` that on the node1 is correct. KK will use it to connect your cluster.

**Comment by shihaoH** [comment]
> Check your `/etc/kubernetes/admin.conf` and `~/.kube/config` that on the node1 is correct. KK will use it to connect your cluster.

```
ERRO[16:43:04 CST] Failed to add master to cluster: Failed to exec command: sudo env PATH=$PATH /bin/sh -c "/usr/local/bin/kubeadm join  192.168.161.224:6443 --token ksm1ib.j0qi5724u6888wty     --discovery-token-ca-cert-hash sha256:db48c38421bf8d19da51ebe0413585699ff2922f2e845abc94aadb732e2d25fc --control-plane --certificate-key fa934e3d8435930b59c64759a9c5a9637240787c24824f5cdc252a4327e554ff --apiserver-advertise-address 192.168.161.223"
[preflight] Running pre-flight checks
        [WARNING SystemVerification]: this Docker version is not on the list of validated versions: 20.10.6. Latest validated version: 19.03
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
```

**Comment by 24sama** [comment]
Can you use this version of kk? Here is the link:[v1.1.1](https://github.com/kubesphere/kubekey/releases/tag/v1.1.1)

**Comment by 24sama** [comment]
1. Please use the command `curl -vk https://192.168.161.55:6443` to check the haproxy server.
2. `cat /etc/hosts` to check the `192.168.161.55 lb.kubesphere.local` is matched.

**Comment by shihaoH** [comment]
haproxy.cfg
```
global
    log /dev/log  local0 warning
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon

   stats socket /var/lib/haproxy/stats

defaults
  log global
  option  httplog
  option  dontlognull
        timeout connect 5000
        timeout client 50000
        timeout server 50000

frontend kube-apiserver
  bind *:8443
  mode tcp
  option tcplog
  default_backend kube-apiserver

backend kube-apiserver
  mode tcp
  option tcplog
  option tcp-check
  balance     roundrobin
  default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100
  server  kube-apiserver-1 192.168.161.222:6443 check
  server  kube-apiserver-2 192.168.161.223:6443 check
  server  kube-apiserver-3 192.168.161.224:6443 check
```

shell
```
[root@node1 ~]# curl -vk https://192.168.161.55:8443
* About to connect() to 192.168.161.55 port 8443 (#0)
*   Trying 192.168.161.55...
* Connected to 192.168.161.55 (192.168.161.55) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* NSS error -5938 (PR_END_OF_FILE_ERROR)
* Encountered end of file
* Closing connection 0
curl: (35) Encountered end of file
[root@node1 ~]# kubectl get node
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding
```

**Comment by 24sama** [comment]
That looks your haproxy didn't work. Please check it.

**Comment by shihaoH** [comment]
Is it because I put haproxy on the master node

**Comment by 24sama** [comment]
Maybe you should modify the value of `bind`:
```
frontend  kube-apiserver
  bind 192.168.161.55:6443
  mode tcp
  option tcplog
  default_backend kube-apiserver
```

**Comment by 24sama** [comment]
check the kk config:
```
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: 192.168.161.224, internalAddress: 192.168.161.224, user: root, password: 1012}
  - {name: node2, address: 192.168.161.225, internalAddress: 192.168.161.225, user: root, password: 1012}
  - {name: node3, address: 192.168.161.226, internalAddress: 192.168.161.226, user: root, password: 1012}
  - {name: lb1, address: 192.168.161.222, internalAddress: 192.168.161.222, user: root, password: 1012}
  - {name: lb2, address: 192.168.161.223, internalAddress: 192.168.161.223, user: root, password: 1012}
  roleGroups:
    etcd:
    - node1
    - lb1
    - lb2
    master: 
    - node1
    - lb1
    - lb2
    worker:
    - node1
    - node2
    - node3
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: "192.168.161.55"
   #### the port should the same as your haproxy frontend bind port. ####
    port: "8443" 
  kubernetes:
    version: v1.18.6
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
    privateRegistry: docker.harbor.local
  addons: []
```
