### ISSUE TITLE
How to add multiple plugins

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubekey#63]
For example, I want to create config file with several plugins. Is it like this one?
```shell
./kk create config --add kubesphere,localVolume
```

**Comment by pixiake** [comment]
yes

**Comment by pixiake** [comment]
When deploying multiple nodes, should the parameters of the kubesphere not be added to the configuration file, and instead deploy kubesphere by a special parameter `--with-kubesphere`，as in allinone mode?  Or support  custom manifests of kubesphere？

**Comment by rayzhou2017** [comment]
> When deploying multiple nodes, should the parameters of the kubesphere not be added to the configuration file, and instead deploy kubesphere by a special parameter `--with-kubesphere`，as in allinone mode? Or support custom manifests of kubesphere？ @rayzhou2017 @zryfish @calvinyv

not quite sure what you mean?

**Comment by rayzhou2017** [comment]
> For example, I want to create config file with several plugins. Is it like this one?
> 
> ```shell
> ./kk create config --add kubesphere,localVolume
> ```

I tried this one, and it generated the sc as below.
```yaml
storage:
    defaultStorageClass:
    localVolume:
      storageClassName: local
```

and the installer throws error: Default StorageClass was not found

**Comment by pixiake** [comment]
Does it show default storageclass，when execute `kubectl get sc`?
![image](https://user-images.githubusercontent.com/22290449/83758073-05c70d80-a6a4-11ea-8ee3-408edf68ed3f.png)

Storage should be first：`./kk create config --add localVolume, kubesphere` 

Or set `defaultStorageClass` to `localVolume`.
```
storage:
    defaultStorageClass: localVolume
    localVolume:
      storageClassName: local
```
