### ISSUE TITLE
KubeSphere startup timeout

### ISSUE THREAD

**Issue by meilihao** [kubesphere/kubekey#654]
### What is version of KubeKey has the issue?

1.1.1

### What is your os environment?

Ubuntu 20.04.3 LTS

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: chen-aliyun, address: 192.168.0.43, internalAddress: 192.168.0.43, user: root, password: xxx}
  roleGroups:
    etcd:
    - chen-aliyun
    master: 
    - chen-aliyun
    worker:
    - chen-aliyun
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.20.6
    imageRepo: kubesphere
    clusterName: cluster.local
    containerManager: containerd
  network:
    plugin: cilium
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: []


---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.1.1
spec:
  persistence:
    storageClass: ""       
  authentication:
    jwtSecret: ""
  zone: ""
  local_registry: ""        
  etcd:
    monitoring: false      
    endpointIps: localhost  
    port: 2379             
    tlsEnable: true
  common:
    redis:
      enabled: false
    redisVolumSize: 2Gi 
    openldap:
      enabled: false
    openldapVolumeSize: 2Gi  
    minioVolumeSize: 20Gi
    monitoring:
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
    es:  
      elasticsearchMasterVolumeSize: 4Gi   
      elasticsearchDataVolumeSize: 20Gi   
      logMaxAge: 7          
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchUrl: ""
      externalElasticsearchPort: ""  
  console:
    enableMultiLogin: true 
    port: 30880
  alerting:       
    enabled: false
    # thanosruler:
    #   replicas: 1
    #   resources: {}
  auditing:    
    enabled: false
  devops:           
    enabled: false
    jenkinsMemoryLim: 2Gi     
    jenkinsMemoryReq: 1500Mi 
    jenkinsVolumeSize: 8Gi   
    jenkinsJavaOpts_Xms: 512m  
    jenkinsJavaOpts_Xmx: 512m
    jenkinsJavaOpts_MaxRAM: 2g
  events:          
    enabled: false
    ruler:
      enabled: true
      replicas: 2
  logging:         
    enabled: false
    logsidecar:
      enabled: true
      replicas: 2
  metrics_server:             
    enabled: false
  monitoring:
    storageClass: ""
    prometheusMemoryRequest: 400Mi  
    prometheusVolumeSize: 20Gi  
  multicluster:
    clusterRole: none 
  network:
    networkpolicy:
      enabled: false
    ippool:
      type: none
    topology:
      type: none
  openpitrix:
    store:
      enabled: false
  servicemesh:    
    enabled: false  
  kubeedge:
    enabled: false
    cloudCore:
      nodeSelector: {"node-role.kubernetes.io/worker": ""}
      tolerations: []
      cloudhubPort: "10000"
      cloudhubQuicPort: "10001"
      cloudhubHttpsPort: "10002"
      cloudstreamPort: "10003"
      tunnelPort: "10004"
      cloudHub:
        advertiseAddress: 
          - ""           
        nodeLimit: "100"
      service:
        cloudhubNodePort: "30000"
        cloudhubQuicNodePort: "30001"
        cloudhubHttpsNodePort: "30002"
        cloudstreamNodePort: "30003"
        tunnelNodePort: "30004"
    edgeWatcher:
      nodeSelector: {"node-role.kubernetes.io/worker": ""}
      tolerations: []
      edgeWatcherAgent:
        nodeSelector: {"node-role.kubernetes.io/worker": ""}
        tolerations: []
```

### A clear and concise description of what happend.

Can't deloy kubesphere, get error `KubeSphere startup timeout`.

### Relevant log output

```shell
`kk create`s log:

# sudo kk --debug create cluster -f config.yaml
+-------------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+
| name        | sudo | curl | openssl | ebtables | socat | ipset | conntrack | docker | nfs client | ceph client | glusterfs client | time         |
+-------------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+
| chen-aliyun | y    | y    | y       | y        | y     | y     | y         |        |            |             |                  | CST 17:37:54 |
+-------------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+

This is a simple check of your environment.
Before installation, you should ensure that your machines meet all requirements specified at
https://github.com/kubesphere/kubekey#requirements-and-recommendations

Continue this installation? [yes/no]: yes
INFO[17:37:56 CST] Downloading Installation Files               
INFO[17:37:56 CST] Downloading kubeadm ...                      
INFO[17:37:56 CST] Downloading kubelet ...                      
INFO[17:37:58 CST] Downloading kubectl ...                      
INFO[17:37:58 CST] Downloading helm ...                         
INFO[17:37:58 CST] Downloading kubecni ...                      
INFO[17:37:59 CST] Downloading etcd ...                         
INFO[17:37:59 CST] Configuring operating system ...             
[chen-aliyun 192.168.0.43] MSG:
vm.swappiness = 1
kernel.sysrq = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
fs.inotify.max_user_instances = 524288
INFO[17:38:00 CST] Start to download images on all nodes        
[chen-aliyun] Downloading image: kubesphere/pause:3.2
[chen-aliyun] Downloading image: kubesphere/kube-apiserver:v1.20.6
[chen-aliyun] Downloading image: kubesphere/kube-controller-manager:v1.20.6
[chen-aliyun] Downloading image: kubesphere/kube-scheduler:v1.20.6
[chen-aliyun] Downloading image: kubesphere/kube-proxy:v1.20.6
[chen-aliyun] Downloading image: coredns/coredns:1.6.9
[chen-aliyun] Downloading image: kubesphere/k8s-dns-node-cache:1.15.12
[chen-aliyun] Downloading image: cilium/cilium:v1.8.3
[chen-aliyun] Downloading image: cilium/operator-generic:v1.8.3
INFO[17:40:03 CST] Generating etcd certs                        
INFO[17:40:04 CST] Synchronizing etcd certs                     
INFO[17:40:04 CST] Creating etcd service                        
Push /home/chen/opt/kk/kubekey/v1.20.6/amd64/etcd-v3.4.13-linux-amd64.tar.gz to 192.168.0.43:/tmp/kubekey/etcd-v3.4.13-linux-amd64.tar.gz   Done
INFO[17:40:05 CST] Starting etcd cluster                        
[chen-aliyun 192.168.0.43] MSG:
Configuration file will be created
INFO[17:40:05 CST] Refreshing etcd configuration                
INFO[17:40:10 CST] Backup etcd data regularly                   
INFO[17:40:16 CST] Get cluster status                           
[chen-aliyun 192.168.0.43] MSG:
Cluster will be created.
INFO[17:40:16 CST] Installing kube binaries                     
Push /home/chen/opt/kk/kubekey/v1.20.6/amd64/kubeadm to 192.168.0.43:/tmp/kubekey/kubeadm   Done
Push /home/chen/opt/kk/kubekey/v1.20.6/amd64/kubelet to 192.168.0.43:/tmp/kubekey/kubelet   Done
Push /home/chen/opt/kk/kubekey/v1.20.6/amd64/kubectl to 192.168.0.43:/tmp/kubekey/kubectl   Done
Push /home/chen/opt/kk/kubekey/v1.20.6/amd64/helm to 192.168.0.43:/tmp/kubekey/helm   Done
Push /home/chen/opt/kk/kubekey/v1.20.6/amd64/cni-plugins-linux-amd64-v0.8.6.tgz to 192.168.0.43:/tmp/kubekey/cni-plugins-linux-amd64-v0.8.6.tgz   Done
INFO[17:40:21 CST] Initializing kubernetes cluster              
[chen-aliyun 192.168.0.43] MSG:
W0904 17:40:22.459458  149405 utils.go:69] The recommended value for "clusterDNS" in "KubeletConfiguration" is: [10.233.0.10]; the provided value is: [169.254.25.10]
[init] Using Kubernetes version: v1.20.6
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [chen-aliyun chen-aliyun.cluster.local kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local lb.kubesphere.local localhost] and IPs [10.233.0.1 192.168.0.43 127.0.0.1]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] External etcd mode: Skipping etcd/ca certificate authority generation
[certs] External etcd mode: Skipping etcd/server certificate generation
[certs] External etcd mode: Skipping etcd/peer certificate generation
[certs] External etcd mode: Skipping etcd/healthcheck-client certificate generation
[certs] External etcd mode: Skipping apiserver-etcd-client certificate generation
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.
[apiclient] All control plane components are healthy after 79.002014 seconds
[upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[kubelet] Creating a ConfigMap "kubelet-config-1.20" in namespace kube-system with the configuration for the kubelets in the cluster
[upload-certs] Skipping phase. Please see --upload-certs
[mark-control-plane] Marking the node chen-aliyun as control-plane by adding the labels "node-role.kubernetes.io/master=''" and "node-role.kubernetes.io/control-plane='' (deprecated)"
[mark-control-plane] Marking the node chen-aliyun as control-plane by adding the taints [node-role.kubernetes.io/master:NoSchedule]
[bootstrap-token] Using token: x1wwnw.7prv8r4xmp3zsx3e
[bootstrap-token] Configuring bootstrap tokens, cluster-info ConfigMap, RBAC Roles
[bootstrap-token] configured RBAC rules to allow Node Bootstrap tokens to get nodes
[bootstrap-token] configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstrap-token] configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstrap-token] configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstrap-token] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
[kubelet-finalize] Updating "/etc/kubernetes/kubelet.conf" to point to a rotatable kubelet client certificate and key
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy

Your Kubernetes control-plane has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

Alternatively, if you are the root user, you can run:

  export KUBECONFIG=/etc/kubernetes/admin.conf

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

You can now join any number of control-plane nodes by copying certificate authorities
and service account keys on each node and then running the following as root:

  kubeadm join lb.kubesphere.local:6443 --token x1wwnw.7prv8r4xmp3zsx3e \
    --discovery-token-ca-cert-hash sha256:37c8a2903fafa607543379c3211c4e27bca62d9c9497be76ecf2a0a65dc35866 \
    --control-plane 

Then you can join any number of worker nodes by running the following on each as root:

kubeadm join lb.kubesphere.local:6443 --token x1wwnw.7prv8r4xmp3zsx3e \
    --discovery-token-ca-cert-hash sha256:37c8a2903fafa607543379c3211c4e27bca62d9c9497be76ecf2a0a65dc35866
[chen-aliyun 192.168.0.43] MSG:
node/chen-aliyun untainted
[chen-aliyun 192.168.0.43] MSG:
node/chen-aliyun labeled
[chen-aliyun 192.168.0.43] MSG:
service "kube-dns" deleted
[chen-aliyun 192.168.0.43] MSG:
service/coredns created
[chen-aliyun 192.168.0.43] MSG:
serviceaccount/nodelocaldns created
daemonset.apps/nodelocaldns created
[chen-aliyun 192.168.0.43] MSG:
configmap/nodelocaldns created
[chen-aliyun 192.168.0.43] MSG:
I0904 17:42:10.758897  150268 version.go:254] remote version is much newer: v1.22.1; falling back to: stable-1.20
[upload-certs] Storing the certificates in Secret "kubeadm-certs" in the "kube-system" Namespace
[upload-certs] Using certificate key:
04dbf615a5c4f332791b5b906c8d1cd2f64c812cacf0476990e02e13faeededb
[chen-aliyun 192.168.0.43] MSG:
secret/kubeadm-certs patched
[chen-aliyun 192.168.0.43] MSG:
secret/kubeadm-certs patched
[chen-aliyun 192.168.0.43] MSG:
secret/kubeadm-certs patched
[chen-aliyun 192.168.0.43] MSG:
kubeadm join lb.kubesphere.local:6443 --token 5bo2ol.zo2mojwvono2jivl     --discovery-token-ca-cert-hash sha256:37c8a2903fafa607543379c3211c4e27bca62d9c9497be76ecf2a0a65dc35866
[chen-aliyun 192.168.0.43] MSG:
chen-aliyun   v1.20.6   [map[address:192.168.0.43 type:InternalIP] map[address:chen-aliyun type:Hostname]]
INFO[17:42:13 CST] Joining nodes to cluster                     
INFO[17:42:13 CST] Deploying network plugin ...                 
[chen-aliyun 192.168.0.43] MSG:
serviceaccount/cilium created
serviceaccount/cilium-operator created
configmap/cilium-config created
clusterrole.rbac.authorization.k8s.io/cilium created
clusterrole.rbac.authorization.k8s.io/cilium-operator created
clusterrolebinding.rbac.authorization.k8s.io/cilium created
clusterrolebinding.rbac.authorization.k8s.io/cilium-operator created
daemonset.apps/cilium created
deployment.apps/cilium-operator created
[chen-aliyun 192.168.0.43] MSG:
storageclass.storage.k8s.io/local created
serviceaccount/openebs-maya-operator created
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
clusterrole.rbac.authorization.k8s.io/openebs-maya-operator created
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
clusterrolebinding.rbac.authorization.k8s.io/openebs-maya-operator created
deployment.apps/openebs-localpv-provisioner created
INFO[17:42:14 CST] Deploying KubeSphere ...                     
v3.1.1
[chen-aliyun 192.168.0.43] MSG:
namespace/kubesphere-system created
namespace/kubesphere-monitoring-system created
[chen-aliyun 192.168.0.43] MSG:
secret/kube-etcd-client-certs created
[chen-aliyun 192.168.0.43] MSG:
namespace/kubesphere-system unchanged
serviceaccount/ks-installer created
customresourcedefinition.apiextensions.k8s.io/clusterconfigurations.installer.kubesphere.io created
clusterrole.rbac.authorization.k8s.io/ks-installer created
clusterrolebinding.rbac.authorization.k8s.io/ks-installer created
deployment.apps/ks-installer created
clusterconfiguration.installer.kubesphere.io/ks-installer created
WARN[18:12:43 CST] Task failed ...                              
WARN[18:12:43 CST] error: KubeSphere startup timeout.           
Error: Failed to deploy kubesphere: KubeSphere startup timeout.
Usage:
  kk create cluster [flags]

Flags:
      --download-cmd string      The user defined command to download the necessary binary files. The first param '%s' is output path, the second param '%s', is the URL (default "curl -L -o %s %s")
  -f, --filename string          Path to a configuration file
  -h, --help                     help for cluster
      --skip-pull-images         Skip pre pull images
      --with-kubernetes string   Specify a supported version of kubernetes (default "v1.19.8")
      --with-kubesphere          Deploy a specific version of kubesphere (default v3.1.0)
      --with-local-storage       Deploy a local PV provisioner
  -y, --yes                      Skip pre-check of the installation

Global Flags:
      --debug        Print detailed information (default true)
      --in-cluster   Running inside the cluster

Failed to deploy kubesphere: KubeSphere startup timeout.
```
