### ISSUE TITLE
upgrade cluster error

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubekey#658]
### What is version of KubeKey has the issue?

v1.2.0

### What is your os environment?

openEuler 21.09

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address:10.0.0.145, internalAddress: 10.0.0.145, user: root, password: xxx}
  - {name: node2, address:10.0.0.243, internalAddress: 10.0.0.243, user: root, password: xxx}
  - {name: node3, address:10.0.0.135, internalAddress: 10.0.0.135, user: root, password: xxx}
  - {name: node4, address:10.0.0.146, internalAddress: 10.0.0.146, user: root, password: xxx}
  roleGroups:
    etcd:
    - node1
    master: 
    - node1
    worker:
    - node2
    - node3
    - node4
  controlPlaneEndpoint:
    ##Internal loadbalancer for apiservers 
    #internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.20.6
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

The following error is reported when using the upgrade command :
![image](https://user-images.githubusercontent.com/36271543/132456014-9d4dccf1-637c-4b73-b50e-f85010235545.png)
