### ISSUE TITLE
Mixed SHA256 keys - Failed to download kube binaries: SHA256 no match.

### ISSUE THREAD

**Issue by gaugys** [kubesphere/kubekey#747]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"1.2.0", GitCommit:"c3068bf", GitTreeState:"", GoVersion:"go1.16.9"}

### What is your os environment?

Ubuntu 20.04.3 LTS

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: k8s-master-01, address: 192.168.0.11, internalAddress: 192.168.0.11, user: ubuntu, password: password, arch: arm64}
  - {name: k8s-slave-01, address: 192.168.0.21, internalAddress: 192.168.0.21, user: ubuntu, password: password, arch: arm64}
  - {name: k8s-slave-02, address: 192.168.0.22, internalAddress: 192.168.0.22, user: ubuntu, password: password, arch: arm64}
  - {name: k8s-slave-03, address: 192.168.0.23, internalAddress: 192.168.0.23, user: ubuntu, password: password, arch: arm64}
  roleGroups:
    etcd:
    - k8s-master-01
    master:
    - k8s-master-01
    worker:
    - k8s-slave-01
    - k8s-slave-02
    - k8s-slave-03
  controlPlaneEndpoint:
    ##Internal loadbalancer for apiservers
    #internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.21.4-k3s
    clusterName: cluster.local
  network:
    plugin: flannel
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: []



---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.2.0
spec:
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  local_registry: ""
  # dev_tag: ""
  etcd:
    monitoring: false
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    # apiserver:
    #  resources: {}
    # controllerManager:
    #  resources: {}
    redis:
      enabled: true
      volumeSize: 2Gi
    openldap:
      enabled: true
      volumeSize: 2Gi
    minio:
      volumeSize: 20Gi
    monitoring:
      # type: external
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      GPUMonitoring:
        enabled: false
    gpu:
      kinds:
      - resourceName: "nvidia.com/gpu"
        resourceType: "GPU"
        default: false
    es:
      # master:
      #   volumeSize: 4Gi
      #   replicas: 1
      #   resources: {}
      # data:
      #   volumeSize: 20Gi
      #   replicas: 1
      #   resources: {}
      logMaxAge: 7
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchUrl: ""
      externalElasticsearchPort: ""
  alerting:
    enabled: true
    # thanosruler:
    #   replicas: 1
    #   resources: {}
  auditing:
    enabled: true
    # operator:
    #   resources: {}
    # webhook:
    #   resources: {}
  devops:
    enabled: true
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 512m
    jenkinsJavaOpts_Xmx: 512m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: false
    # operator:
    #   resources: {}
    # exporter:
    #   resources: {}
    # ruler:
    #   enabled: true
    #   replicas: 2
    #   resources: {}
  logging:
    enabled: false
    containerruntime: containerd
    logsidecar:
      enabled: true
      replicas: 2
      # resources: {}
  metrics_server:
    enabled: true
  monitoring:
    storageClass: ""
    # kube_rbac_proxy:
    #   resources: {}
    # kube_state_metrics:
    #   resources: {}
    # prometheus:
    #   replicas: 1
    #   volumeSize: 20Gi
    #   resources: {}
    #   operator:
    #     resources: {}
    #   adapter:
    #     resources: {}
    # node_exporter:
    #   resources: {}
    # alertmanager:
    #   replicas: 1
    #   resources: {}
    # notification_manager:
    #   resources: {}
    #   operator:
    #     resources: {}
    #   proxy:
    #     resources: {}
    gpu:
      nvidia_dcgm_exporter:
        enabled: false
        # resources: {}
  multicluster:
    clusterRole: none
  network:
    networkpolicy:
      enabled: false
    ippool:
      type: none
    topology:
      type: none
  openpitrix:
    store:
      enabled: false
  servicemesh:
    enabled: false
  kubeedge:
    enabled: false
    cloudCore:
      nodeSelector: {"node-role.kubernetes.io/worker": ""}
      tolerations: []
      cloudhubPort: "10000"
      cloudhubQuicPort: "10001"
      cloudhubHttpsPort: "10002"
      cloudstreamPort: "10003"
      tunnelPort: "10004"
      cloudHub:
        advertiseAddress:
          - ""
        nodeLimit: "100"
      service:
        cloudhubNodePort: "30000"
        cloudhubQuicNodePort: "30001"
        cloudhubHttpsNodePort: "30002"
        cloudstreamNodePort: "30003"
        tunnelNodePort: "30004"
    edgeWatcher:
      nodeSelector: {"node-role.kubernetes.io/worker": ""}
      tolerations: []
      edgeWatcherAgent:
        nodeSelector: {"node-role.kubernetes.io/worker": ""}
        tolerations: []
```

### A clear and concise description of what happend.

Hey,

  I'm building a fresh kubernetes platform on raspberry pi  4 (arm64) by levarging Kubesphere and K3S.
The problem occurs when checking sha256sum of k3 files. I think the problem exists becasue of a mix SHA256 sum keys between k3s amd64 and arm64 in kubekey/pkg/files/file.go file:

```
k3s: {
			amd64: {
				"v1.20.2": "ce3055783cf115ee68fc00bb8d25421d068579ece2fafa4ee1d09f3415aaeabf",
				"v1.20.4": "1c7b68b0b7d54f21a9c1727545a7db181668115f161a3986bc137261dd817e98",
				"v1.21.4": "47e686ad5390670da79a467ba94399d72e472364bc064a20fecd3937a8d928b5",
			},
			arm64: {
				"v1.21.4": "b7f8c026c5346b3e894d731f1dc2490cd7281687549f34c28a849f58c62e3e48",
```

Please refer to the additional information k3s file as you notice that arm64 checksum is defined under amd64. I tried to complite kk from the source, unfortuantelly without lucky :) . 
So I hope you can provide a fix or  guidance how to resolv the issue.

Thanks

### Relevant log output

```shell
./kk create cluster -f config-sample.yaml
INFO[20:18:23 UTC] Downloading Installation Files
INFO[20:18:23 UTC] Downloading k3s ...
WARN[20:19:12 UTC] Task failed ...
WARN[20:19:12 UTC] error: SHA256 no match. b7f8c026c5346b3e894d731f1dc2490cd7281687549f34c28a849f58c62e3e48 not in 47e686ad5390670da79a467ba94399d72e472364bc064a20fecd3937a8d928b5  /home/ubuntu/kubesphere/kubekey/v1.21.4/arm64/k3s
Error: Failed to download kube binaries: SHA256 no match. b7f8c026c5346b3e894d731f1dc2490cd7281687549f34c28a849f58c62e3e48 not in 47e686ad5390670da79a467ba94399d72e472364bc064a20fecd3937a8d928b5  /home/ubuntu/kubesphere/kubekey/v1.21.4/arm64/k3s
Usage:
  kk create cluster [flags]

Flags:
      --container-manager string   Container runtime: docker, crio, containerd and isula. (default "docker")
      --download-cmd string        The user defined command to download the necessary binary files. The first param '%s' is output path, the second param '%s', is the URL (default "curl -L -o %s %s")
  -f, --filename string            Path to a configuration file
  -h, --help                       help for cluster
      --skip-pull-images           Skip pre pull images
      --with-kubernetes string     Specify a supported version of kubernetes (default "v1.21.5")
      --with-kubesphere            Deploy a specific version of kubesphere (default v3.2.0)
      --with-local-storage         Deploy a local PV provisioner
  -y, --yes                        Skip pre-check of the installation

Global Flags:
      --debug        Print detailed information (default true)
      --in-cluster   Running inside the cluster

Failed to download kube binaries: SHA256 no match. b7f8c026c5346b3e894d731f1dc2490cd7281687549f34c28a849f58c62e3e48 not in 47e686ad5390670da79a467ba94399d72e472364bc064a20fecd3937a8d928b5  /home/ubuntu/kubesphere/kubekey/v1.21.4/arm64/k3s
```

### Additional information

ubuntu@k8s-master-01:~/kubesphere/kubekey/v1.21.4/arm64$ ls -l
total 47836
-rw-rw-r-- 1 ubuntu ubuntu 48984064 Nov  6 20:19 k3s
ubuntu@k8s-master-01:~/kubesphere/kubekey/v1.21.4/arm64$ pwd
/home/ubuntu/kubesphere/kubekey/v1.21.4/arm64
ubuntu@k8s-master-01:~/kubesphere/kubekey/v1.21.4/arm64$ sha256sum k3s
47e686ad5390670da79a467ba94399d72e472364bc064a20fecd3937a8d928b5  k3s
ubuntu@k8s-master-01:~/kubesphere/kubekey/v1.21.4/arm64$ chmod +x k3s
ubuntu@k8s-master-01:~/kubesphere/kubekey/v1.21.4/arm64$ ./k3s help
NAME:
   k3s - Kubernetes, but small and simple

USAGE:
   k3s [global options] command [command options] [arguments...]

VERSION:
   v1.21.4+k3s1 (3e250fdb)

COMMANDS:
   server         Run management server
   agent          Run node agent
   kubectl        Run kubectl
   crictl         Run crictl
   ctr            Run ctr
   check-config   Run config check
   etcd-snapshot  Trigger an immediate etcd snapshot
   help, h        Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug                     (logging) Turn on debug logs [$K3S_DEBUG]
   --data-dir value, -d value  (data) Folder to hold state default /var/lib/rancher/k3s or ${HOME}/.rancher/k3s if not root
   --help, -h                  show help
   --version, -v               print the version
