### ISSUE TITLE
Operator mode is abnormal in multi-nodes cluster

### ISSUE THREAD

**Issue by pixiake** [kubesphere/kubekey#792]
### What is version of KubeKey has the issue?

v2.0.0-alpha.1

### What is your os environment?

Ubuntu20.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: cluster-ksv
spec:
  hosts:
  - {name: node1, address: 172.20.6.3, internalAddress: 172.20.6.3, user: ubuntu, password: xxx}
  - {name: node2, address: 172.20.6.4, internalAddress: 172.20.6.4, user: ubuntu, password: xxx}
  - {name: node3, address: 172.20.6.5, internalAddress: 172.20.6.5, user: ubuntu, password: xxx}
  roleGroups:
    etcd:
    - node1
    master:
    - node1
    worker:
    - node1
    - node2
    - node3
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    type: k3s
    version: v1.21.6
    clusterName: cluster.local
  network:
    plugin: calico
    calico:
      vethMTU: 1440
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []

```

### A clear and concise description of what happend.

When the configuration file is applied in the cluster installed according to the configuration file above, the kk‘s controller-manager will automatically delete the `etcd` in the `spec.roleGroups`.
