### ISSUE TITLE
`get etcd local certs dir by module cache failed` when recreate cluster  with kk v2.0.0-version(master)

### ISSUE THREAD

**Issue by tanguofu** [kubesphere/kubekey#851]
### What is version of KubeKey has the issue?

./output/kk version version.BuildInfo{Version:"latest+unreleased", GitCommit:"b5a41a021d49cb1bf90d2e2c8a3f042b87e7863a", GitTreeState:"dirty", GoVersion:"go1.16.11"}

### What is your os environment?

centos 7.9

### KubeKey config file

```yaml
only a single node config
```

### A clear and concise description of what happend.

 ./kk create  cluster -f config-sample.yaml -y  --debug

### Relevant log output

```shell
14:36:03 CST success: [node1]
14:36:03 CST [CertsModule] Generate certs script
14:36:03 CST skipped: [node1]
14:36:03 CST [CertsModule] Generate OpenSSL config
14:36:03 CST skipped: [node1]
14:36:03 CST [CertsModule] Exec certs script
14:36:03 CST skipped: [node1]
14:36:03 CST [CertsModule] Synchronize certs file
14:36:03 CST message: [node1]
get etcd local certs dir by module cache failed
```

### Additional information

it seem that`Prepare:  &FirstETCDNode{Not: true},` in `syncCertsFile`  should be  `Prepare:  &new(FirstETCDNode)` ?
```
	execCertsScript := &task.RemoteTask{
		Name:     "ExecCertsScript",
		Desc:     "Exec certs script",
		Hosts:    c.Runtime.GetHostsByRole(common.ETCD),
		Prepare:  new(FirstETCDNode),
		Action:   new(ExecCertsScript),
		Parallel: true,
		Retry:    1,
	}

	syncCertsFile := &task.RemoteTask{
		Name:     "SyncCertsFile",
		Desc:     "Synchronize certs file",
		Hosts:    c.Runtime.GetHostsByRole(common.ETCD),
		Prepare:  &FirstETCDNode{Not: true},
		Action:   new(SyncCertsFile),
		Parallel: true,
		Retry:    1,
	}

	syncCertsToMaster := &task.RemoteTask{
		Name:     "SyncCertsFileToMaster",
		Desc:     "Synchronize certs file to master",
		Hosts:    c.Runtime.GetHostsByRole(common.Master),
		Prepare:  &common.OnlyETCD{Not: true},
		Action:   new(SyncCertsFile),
		Parallel: true,
		Retry:    1,
	}
```

**Comment by 24sama** [comment]
> 14:36:03 CST success: [node1]
14:36:03 CST [CertsModule] Generate certs script
14:36:03 CST skipped: [node1]
14:36:03 CST [CertsModule] Generate OpenSSL config
14:36:03 CST skipped: [node1]
14:36:03 CST [CertsModule] Exec certs script
14:36:03 CST skipped: [node1]
14:36:03 CST [CertsModule] Synchronize certs file
14:36:03 CST message: [node1]
get etcd local certs dir by module cache failed

I see the `node1` skipped nearly all `etcd module`, and you want to install a single node cluster. So, I think maybe there are something wrong with your config file. Does the `node1` have an `etcd` role?

**Comment by tanguofu** [comment]
yes, the cluster-config.yaml is this, as ip is use 'x.x.x.x' instead of.
```
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  -  {name: node1, address: x.x.x.x, internalAddress: x.x.x.x, user: root, password: "xxxx" }
  roleGroups:
    etcd:
    - node1
    master: 
    - node1
    worker:
    - node1
  kubernetes:
    version: v1.21.5
    clusterName: cluster.local
  network:
    plugin: cilium
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: 
    - "https://mirror.ccs.tencentyun.com"
    insecureRegistries: []
  addons: []
```
