### ISSUE TITLE
Error accessing etcd on node of VIP in k8s high availability cluster

### ISSUE THREAD

**Issue by ktpktr0** [kubesphere/kubekey#857]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"1.2.1-rc.1", GitCommit:"5cdc98b", GitTreeState:"", GoVersion:"go1.16.10"}

### What is your os environment?

contos7.9

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: k8s-master1, address: 192.168.9.150, internalAddress: 192.168.9.150, user: root, password: "123"}
  - {name: k8s-master2, address: 192.168.9.151, internalAddress: 192.168.9.151, user: root, password: "123"}
  - {name: k8s-master3, address: 192.168.9.152, internalAddress: 192.168.9.152, user: root, password: "123"}
  - {name: k8s-node1, address: 192.168.9.155, internalAddress: 192.168.9.155, user: root, password: "123"}
  - {name: k8s-node2, address: 192.168.9.156, internalAddress: 192.168.9.156, user: root, password: "123"}
  roleGroups:
    etcd:
    - k8s-master1
    - k8s-master2
    - k8s-master3
    master:
    - k8s-master1
    - k8s-master2
    - k8s-master3
    worker:
    - k8s-node1
    - k8s-node2
  controlPlaneEndpoint:
    ##Internal loadbalancer for apiservers 
    internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.21.5
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

I use the above configuration file to configure the highly available cluster. The cluster seems to be running normally, but the etcd of the VIP node will report an error: does not match any of DNSNames

### Relevant log output

```shell
2021-11-26 04:14:01.012111 I | embed: rejected connection from "192.168.9.153:65036" (error "tls: \"192.168.9.153\" does not match any of DNSNames [\"k8s-master1\" \"localhost\"]", ServerName "", IPAddresses ["192.168.9.150" "127.0.0.1" "::1"], DNSNames ["k8s-master1" "localhost"])
2021-11-26 04:14:01.015309 I | embed: rejected connection from "192.168.9.153:65038" (error "tls: \"192.168.9.153\" does not match any of DNSNames [\"k8s-master1\" \"localhost\"]", ServerName "", IPAddresses ["192.168.9.150" "127.0.0.1" "::1"], DNSNames ["k8s-master1" "localhost"])
```

### Additional information

The error message "does not match any of dnsnames" is always displayed in the master node where the VIP is located

```
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:9d:cb:cd brd ff:ff:ff:ff:ff:ff
    inet 192.168.9.150/16 brd 192.168.255.255 scope global noprefixroute ens192
       valid_lft forever preferred_lft forever
    inet 192.168.9.153/22 scope global ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::a267:a0fa:7db3:d48c/64 scope link tentative noprefixroute dadfailed 
       valid_lft forever preferred_lft forever
    inet6 fe80::2595:4723:8cba:b7a1/64 scope link tentative noprefixroute dadfailed 
       valid_lft forever preferred_lft forever
    inet6 fe80::e300:31a3:fb10:fce4/64 scope link tentative noprefixroute dadfailed 
       valid_lft forever preferred_lft forever
```

**Comment by 24sama** [comment]
Can you try to create a cluster like this? This will make `192.168.9.153` as an LB address to set in `SANs`.
```
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: k8s-master1, address: 192.168.9.150, internalAddress: 192.168.9.150, user: root, password: "123"}
  - {name: k8s-master2, address: 192.168.9.151, internalAddress: 192.168.9.151, user: root, password: "123"}
  - {name: k8s-master3, address: 192.168.9.152, internalAddress: 192.168.9.152, user: root, password: "123"}
  - {name: k8s-node1, address: 192.168.9.155, internalAddress: 192.168.9.155, user: root, password: "123"}
  - {name: k8s-node2, address: 192.168.9.156, internalAddress: 192.168.9.156, user: root, password: "123"}
  roleGroups:
    etcd:
    - k8s-master1
    - k8s-master2
    - k8s-master3
    master:
    - k8s-master1
    - k8s-master2
    - k8s-master3
    worker:
    - k8s-node1
    - k8s-node2
  controlPlaneEndpoint:
    ##Internal loadbalancer for apiservers 
    internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: "192.168.9.153"    ### add here ###
    port: 6443
  kubernetes:
    version: v1.21.5
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: []
```
