### ISSUE TITLE
ubuntu20.04.3 kk安装k8s，检查不通过

### ISSUE THREAD

**Issue by yunnet** [kubesphere/kubekey#945]
### What is version of KubeKey has the issue?

2.0.0-alpha.4

### What is your os environment?

ubuntu 20.04.3 -desktop-amd64

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: k8s
spec:
  hosts:
  - {name: k8s-master, address: 10.8.80.164, internalAddress: 10.8.80.164, port: 2222, user: bis, password: "123456"}
  - {name: k8s-slave1, address: 10.8.88.171, internalAddress: 10.8.88.171, port: 2222, user: bis, password: "123456"}
  - {name: k8s-slave2, address: 10.8.76.191, internalAddress: 10.8.76.191, port: 2222, user: bis, password: "123456"}
  roleGroups:
    etcd:
    - k8s-master
    master:
    - k8s-master
    worker:
    - k8s-slave1
    - k8s-slave2
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.23.0
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: kubeovn
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.
```
./kk create cluster -f cluster.yaml 


 _   __      _          _   __           
| | / /     | |        | | / /           
| |/ / _   _| |__   ___| |/ /  ___ _   _ 
|    \| | | | '_ \ / _ \    \ / _ \ | | |
| |\  \ |_| | |_) |  __/ |\  \  __/ |_| |
\_| \_/\__,_|_.__/ \___\_| \_/\___|\__, |
                                    __/ |
                                   |___/

12:28:46 CST [NodePreCheckModule] A pre-check on nodes
```

定格在这个画面，很久不动，看日志也是这句A pre-check on nodes
不知道如何查找问题？

### Relevant log output

```shell
12:28:46 CST [NodePreCheckModule] A pre-check on nodes
```

### Additional information

root@k8s-master:/opt/kubekey# locale
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:zh
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=

**Comment by pixiake** [comment]
This seems root be caused by the operating system language being zh_CN and using non-root user. This is really a bug，we will fix it later.

Now, there are currently two ways to avoid it.
1. Install with `root`
2. Set `NOPASSWD: ALL` for this user in `/etc/sudoers`

**Comment by yunnet** [comment]
第一种方法，在root用户环境下安装，这个试验无效
第二种，没试过。
谢谢答复。

**Comment by 24sama** [comment]
Hi @yunnet 
Options 1 means:
The user of remote host need to be `root`. For example: 
```
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: k8s
spec:
  hosts: 
  - {name: k8s-master, address: 10.8.80.164, internalAddress: 10.8.80.164, port: 2222, user: root, password: "123456"}
                                                                                              ^

```
