### ISSUE TITLE
ClusterName is alway same to dnsDomain when creating Kubernetes Cluster

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/kubekey#950]
### What is version of KubeKey has the issue?

all version

### What is your os environment?

all 

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
...
  kubernetes:
    version: v1.21.5
    imageRepo: kubesphere
    clusterName: cluster.local
```

### A clear and concise description of what happend.

`ClusterName` and `dnsDomain` are 2 different Kubernetes settings that don't have any relations.  However, Kubekey has configured them as the same as `ClusterName`.

Refer: https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/
