### ISSUE TITLE
proposal ：support set ntp server and timezone  when kk deloy k8s

### ISSUE THREAD

**Issue by tanguofu** [kubesphere/kubekey#951]
### Your current KubeKey version

2.0.0

### Describe this feature

i the difference time of each k8s node should be very small, so it is necessary to enable ntp server.

### Describe the solution you'd like

Now c[]hrony](https://chrony.tuxfamily.org/) is the most  widely applied ntp servers,  this PR add the configs to `cluster-config.yaml`
```
...
  controlPlaneEndpoint:
  ...
  system:
    ntpServers: 
      - time1.cloud.tencent.com
      - ntp.aliyun.com
    timezone: "Asia/Shanghai"
  kubernetes:
....
```
if `system.ntpServers`  was set, add the configs into /etc/chrony.conf
if `system.timezone`  was set , call `timedatectl set-timezone` change the timezone
for keep compatibility if  these not set or the values is empty  just do nothing.
